### ISSUE TITLE
fusermount -u vs NFS; patch included

### ISSUE THREAD

**Issue by oclsc** [libfuse/libfuse#1009]
If a FUSE file system is mounted on an NFS file system with the root_squash option in effect, and any directory in the path leading to the mount point is protected against searching by others, fusermount -u refuses to unmount it.

In the example, arith is a toy FUSE file system: cat X/Y should print X+Y.

This works:
DlS$ ls -ld mnt
drwxr-xr-x 2 norman cdfstaff 4096 Aug 12 11:53 mnt
DlS$ ./arith mnt
DlS$ cat mnt/3/4
7
DlS$ fusermount -u mnt

But this doesn't:
DlS$ ls -ld private private/mnt
drwx------ 3 norman cdfstaff 4096 Aug 12 11:55 private
drwxr-xr-x 2 norman cdfstaff 4096 Aug 12 11:55 private/mnt
DlS$ ./arith private/mnt
DlS$ cat private/mnt/4/5
9
DlS$ fusermount -u private/mnt
fusermount: failed to unmount /h/u1/norman/hack/fuse/private/mnt: Permission denied
DlS$ 

The trouble is in the privilege checks in util/fusermount.c unmount_fuse_locked.  The code drops privs (drop_privs()) before calling chdir_to_parent, so permissions are checked with the correct credentials; then restores them (restore_privs()) before calling umount2, presumably expecting that privs are required for unmounting.  But the full pathname is passed to umount2, so permissions are, in effect, checked again as super-user.  The trouble is that if NFS squash_root is in effect, and some directory in the path forbids access to others, it will then forbid access to the super-user (who for permission purposes is treated as nobody thanks to squash_root), and umount2 fails.

On Linux, drop_privs and restore_privs manipulate not the effective ids but the file-system ids.  If privs are dropped, the effective userid is still zero, so umount2 is still allowed; but the file-system ids are the real user's, so permission checks walking the path are done as that user and will succeed.  (We know they will succeed because chdir_to_parent succeeded.)  So the problem NFS exposes can be mended just by moving restore_privs to come after, rather than before, the umount2 call.

I'm guessing the existing code was written before there were separate fs ids; if all you have to manipulate is the effective ids, running umount2 with privs up is the only option.  And then nobody noticed that using fs ids allowed the NFS-permission problem (which was there all along) to be worked around.

As I wrote the above, I realized that if you try to use the code on a non-Linux system, e.g. one of the BSDs, there's no fsuid so umount has to be called with privs.  But drop_privs and restore_privs are local to fusermount.c, and are written to assume getfsuid/setfsuid exist, so it doesn't matter, right?

My proposed fix is pretty simple; here it is as a diff.  (I'm old-fashioned enough never to have done a pull request so this seems simpler; if you'd rather I learned how, let me know and I'll cope.)

*** util/fusermount.orig.c	Mon Aug 12 12:05:15 2024
--- util/fusermount.c	Mon Aug 12 11:29:04 2024
***************
*** 523,533 ****
  
  	drop_privs();
  	res = chdir_to_parent(copy, &last);
! 	restore_privs();
! 	if (res == -1)
  		goto out;
  
  	res = umount2(last, umount_flags);
  	if (res == -1 && !quiet) {
  		fprintf(stderr, "%s: failed to unmount %s: %s\n",
  			progname, mnt, strerror(errno));
--- 523,535 ----
  
  	drop_privs();
  	res = chdir_to_parent(copy, &last);
! 	if (res == -1) {
! 		restore_privs();
  		goto out;
+ 	}
  
  	res = umount2(last, umount_flags);
+ 	restore_privs();
  	if (res == -1 && !quiet) {
  		fprintf(stderr, "%s: failed to unmount %s: %s\n",
  			progname, mnt, strerror(errno));

Cheers,

Norman Wilson

**Comment by bsbernd** [comment]
Could you please create a pull request? Much easier to read. In fact, the way you posted the patch made it unreadable due to github formatting. At a minimum you would need to format it as code, using 3 back ticks '`' before and after the patch. But a pull request is much easier to review.

**Comment by oclsc** [comment]
Allow me to sigh for the days when plain text just worked!

Will figure out pull requests and make one.  May take a few days.

Thanks!

**Comment by bsbernd** [comment]
Thank you for sending a pull request! We could also send patches by mail, but the list is so much spammed. And to be honest, I personally prefer pull requests - easier to review and easier to update  - avoids issues like today when I sent a fuse kernel patch and had forgotten to refresh the patch - part of the change was missing in my mail - silly me...

Give me a day please to think about if there could be negative effects. So far looks good, especially with your commit explanation (thank for that - I don't have all setfs id details in my head).

**Comment by oclsc** [comment]
No worries; whatever's easier for you!

Glad to chat further if helpful.  It is kind of subtle.  The big spew of text I left at the top of this issue has more detail, I think, if it's readable.

And no rush.  It matters to us here (personal account but the problem discovered in my job at a university), but I've compiled my own copy with the fix and distributed it to our systems.  Which also means it will get more exercised the next time an instructor uses FUSE in a course.

Cheers!

**Comment by bsbernd** [comment]
The patch was merged, I think we can close this.
