### ISSUE TITLE
Disk I/O speed difference when mount fuse-based system(mergerfs)

### ISSUE THREAD

**Issue by pahome** [libfuse/libfuse#101]
I found something weird when I want to test the IO speed through fuse-based system.
Mine machine is Ubuntu 4.4.0-38 x86_64
fio_version = 2.14

I mount a **raid 0(4 x ssd)** in ~/a, a **sshfs** in ~/b.And I use **mergerfs** to mount them in ~/mnt
The job file is originally belonged to ~/a/jobfile, so I will see it in ~/mnt/jobfile.
And I test the ~/mnt/jobfile by fio config file.

...................................Condition 1......................................
When I command: **mergerfs -o allow_other -o direct_io ~/a:~/b ~/mnt** , and monitor the I/O by `iostat -xd 1`
```
Read:
Device    rkB/s     wkB/s    %util
~/a       1200     0         98.00
Write:
Device    rkB/s     wkB/s    %util
~/a       100       400      98.00
```
....................................Condition 2...........................
When I command: **mergerfs -o allow_other ~/a:~/b ~/mnt** , and monitor the I/O by iostat -xd 1
```
Read:
Device    rkB/s     wkB/s    %util
~/a       1200      0        98.00
Write:
Device    rkB/s     wkB/s    %util
~/a       0         1000     98.00   <----- that's my expected result before
```

I thought I can speed up writing by using option **-o direct_io** but not working, and the speed of write decrease!

But I dont found anything about the detail or influence of option **-o direct_io** ?

thx for help :)

**Comment by Nikratio** [comment]
If you think there is a problem in FUSE, please attempt to reproduce it with one of the examples (ideally passthrough_ll or passthrough_fh). Your current setup has too many layers to help you -- how do you know that the problem is with libfuse, rather than e.g. mergerfs?
