### ISSUE TITLE
Consider restricting Github wiki write access

### ISSUE THREAD

**Issue by velsinki** [libfuse/libfuse#1025]
It looks like the Github wiki has public write access. I don't know if this is intended? A user posted a spam page 2 weeks ago and I just removed it.

You could consider restricting write access to the wiki in the future perhaps.

**Comment by bsbernd** [comment]
Thanks @velsinki ! And sorry for my late reply, had seen your message, had been busy and a half week on vacation - forgot about it when I came back.

Hmm, so github doesn't provide much options for wiki restrictions - would be good if it had an option that maintainers need to verify modifications. I now set the option `Restrict editing to users in teams with push access only` but that is very restrictive.

**Comment by bsbernd** [comment]
Btw, how did you notice the SPAM, just by reading the wiki or did you get any notification?

**Comment by velsinki** [comment]
I just happened to read the Wiki and saw the spam page ;)

**Comment by velsinki** [comment]
You can submit pull requests for the Wiki too I believe, that's a way to manage the limited access.
