### ISSUE TITLE
passthrough_hp with CAP_SYS_ADMIN does not handle O_DIRECT

### ISSUE THREAD

**Issue by hanwen** [libfuse/libfuse#1027]
The passthrough_hp example does not work correctly when using the passthrough backing FD feature with O_DIRECT. Repro:

```
$ rm -rf /tmp/mnt /tmp/orig && mkdir /tmp/mnt /tmp/orig && dd if=/dev/zero of=/tmp/orig/file bs=1024 count=1024 && sudo ./example/passthrough_hp --foreground /tmp/orig /tmp/mnt & (sleep 1; sudo dd if=/tmp/mnt/file of=/dev/null count=1024 bs=1024 iflag=direct; echo "result: $?"; sudo umount -f  /tmp/mnt)
[1] 55958
1024+0 records in
1024+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00682801 s, 154 MB/s
ERROR: fuse_passthrough read failed.
dd: error reading '/tmp/mnt/file': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.000720046 s, 0.0 kB/s
result: 1
```

This is because `sfs_read` assumes that any call when `passthrough` is set is some sort of error, however, it is expected when using `O_DIRECT` ? As a fix,  I tried

```
-    if (fs.passthrough && !fs.direct_io) {
-        cerr << "ERROR: fuse_passthrough read failed." << endl;
+    if (fs.passthrough && !fs.direct_io && !fi->direct_io) {
+        cerr << "ERROR: fuse_passthrough read failed. " <<  endl;
```

to fix this, but somehow the `fi->direct_io` flag gets stomped between the open and read call. I am not familiar enough with libfuse to further debug this.

**Comment by joannekoong** [comment]
Hi @hanwen. I think this is because you need to set the `--direct-io` flag when you run passthrough_hp. Eg

```
[vmuser@myvm build]$  rm -rf /tmp/mnt /tmp/orig && mkdir /tmp/mnt /tmp/orig && dd if=/dev/zero of=/tmp/orig/file bs=1024 count=1024 && sudo ./example/passthrough_hp --foreground --direct-io /tmp/orig /tmp/mnt & (sleep 1; sudo dd if=/tmp/mnt/file of=/dev/null count=1024 bs=1024 iflag=direct; echo "result: $?"; sudo umount -f  /tmp/mnt)
[3] 2786
1024+0 records in
1024+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00323187 s, 324 MB/s
1024+0 records in
1024+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0501036 s, 20.9 MB/s
result: 0
```

**Comment by bsbernd** [comment]
@joannekoong it sets this automatically when O_DIRECT is detected
```
    /* Enable direct_io when open has flags O_DIRECT to enjoy the feature
       parallel_direct_writes (i.e., to get a shared lock, not exclusive lock,
       for writes to the same file). */
    if (fi->flags & O_DIRECT)
	    fi->direct_io = 1;
```

**Comment by bsbernd** [comment]
@hanwen I will look into it later. Please note that fs.direct_io / fi->direct_io relates to the fuse flag FOPEN_DIRECT_IO. As written above, nowadays we set FOPEN_DIRECT_IO (in examples/) when O_DIRECT is detected in order to make FOPEN_PARALLEL_DIRECT_WRITES to work (shared kernel inode lock instead of exclusive lock).

**Comment by joannekoong** [comment]
> @joannekoong it sets this automatically when O_DIRECT is detected

That sets `fi->direct_io` but the read for passthrough is gated on `fs.direct_io` which only gets set via the config option
```
    if (fs.passthrough && !fs.direct_io) {
        cerr << "ERROR: fuse_passthrough read failed." << endl;
        fuse_reply_err(req, EIO);
        return;
    }
```
which i believe is where this error is coming from

**Comment by bsbernd** [comment]
Ah right, too distracted today. I guess we need to store the fi->direct_io state into the passthrough_hp inode. As I said, I will look later, looks like not today, maybe tomorrow evening.

**Comment by bsbernd** [comment]
Much later than planned, this should address it: https://github.com/libfuse/libfuse/pull/1031
