### ISSUE TITLE
Ubuntu 18.04 froze, then fsckd file system scan stuck during reboot (Ctrl+C doesn’t cancel). 

### ISSUE THREAD

**Issue by anirbanpaulcompany** [libfuse/libfuse#1042]
After installing fuse, 
Sudo apt-get install fuse
This happen

![17273627880249159031427152896779](https://github.com/user-attachments/assets/605f7889-c2bb-4052-b5ce-95b6405ab055)

**Comment by bsbernd** [comment]
I don't see what is the relation of libfuse, please open a bug for your distribution (and you will need to debug what systemd does)
