### ISSUE TITLE
FUSE_USE_VERSION issues in example

### ISSUE THREAD

**Issue by rockeet** [libfuse/libfuse#1051]
In `example/passthrough_hp.cc`, the `FUSE_USE_VERSION` is 3.12, but it use `fuse_passthrough_open` which is newer.

Should `FUSE_USE_VERSION` be defined as a newer version?

**Comment by bsbernd** [comment]
No, it is not an issue. FUSE_USE_VERSION defines the API version, if there are API differences. But there is no API update. We could set 317, but it won't make a difference.

**Comment by rockeet** [comment]
> No, it is not an issue. FUSE_USE_VERSION defines the API version, if there are API differences. But there is no API update. We could set 317, but it won't make a difference.

I see, very thanks!
