### ISSUE TITLE
filler accepts duplicate filenames

### ISSUE THREAD

**Issue by GiorgosXou** [libfuse/libfuse#1062]
just happened to find out that if I `filler(buf, "tag", ...);` a file-name more than once, the file appears multiple times instead of once. Is this supposed to happend? and if so, is it possible to switch-off\prevent this behaviour somehow internally? *(since [I imagine] libfuse internally keeps track of inodes)* 

![image](https://github.com/user-attachments/assets/aa48e275-307a-4bb3-bcfc-9cb76e0b87af)

**Comment by ashleypittman** [comment]
I was surprised by this as well that there's nothing to stop it, but yes I can confirm I've seen this behaviour and that no, libfuse does not track inodes or directory entries, at least in the low-level API.

**Comment by trapexit** [comment]
It is "supposed to happen" in that the OS is perfectly fine presenting that information. The underlying data structure is a simple linear memory buffer. There is no keeping track of any of the data filled. That is your responsibility. Technically a readdir can be rewind'ed and it is really up to the filesystem to handle that properly. And even if you use telldir/seekdir the directory could have changed and I don't believe there is any guarantee that you won't end up getting the duplicate entries from readdir.

What I'm trying to say is that it is the responsibility of both the producer and consumer to deal with such things.

**Comment by GiorgosXou** [comment]
Ok,  it makes sense,  thanks.

> There is no keeping track of any of the data filled...

True, I keep forgetting about this 😅

> In my union filesystem I have to create these temporary sets to ensure I don't include multiple entries...

*(before closing this issue)* could you point me to some parts of your code where you utilize those sets? *(I'm interested to see some details on how you worked around it)*

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/blob/latest-release/src/fuse_readdir_seq.cpp#L123
https://github.com/trapexit/mergerfs/blob/latest-release/src/hashset.hpp

Be warned that I use a vendored and heavily modified version of libfuse.

I'm just using khash. At the time it was one of the faster hashmaps/sets I knew of. But I hash the filename and store the 64bit int hash. Yes, there is risk of collision but I ran it across millions of files and never had one so I felt it was a reasonably safe space / perf tradeoff.

I probably need to revisit all this but it's worked fine for years.

**Comment by GiorgosXou** [comment]
Nice, thanks again. 👋

*(PS. [here's](https://jacksonallan.github.io/c_cpp_hash_tables_benchmark/) an interesting link to some recent benchmarks on C\C++ hashmaps)*
