### ISSUE TITLE
Installation verification error

### ISSUE THREAD

**Issue by noah8627** [libfuse/libfuse#1068]
when i use meson setup ..,the following error is displayed
![未命名 2](https://github.com/user-attachments/assets/6984830f-dcbf-4759-ba22-ea27ba09df05)
this is version of my machine
![Uploading WechatIMG125.jpg…]()
I'm sure I downloaded the file from the correct address

**Comment by bsbernd** [comment]
That is not an issue, there is something on your system that does not let meson find the directory for udev. You can manually set udevdir or just continue without it.
