### ISSUE TITLE
libfuse android problem

### ISSUE THREAD

**Issue by pauloacribeiro92** [libfuse/libfuse#108]
Hi guys,
Im trying to compile libfuse for android from [CyanogenMod/android_external_fuse ](https://github.com/CyanogenMod/android_external_fuse). 

It compiles without problem when im building as a SHARED LIBRARY, but when i try to build it as a STATIC LIBRARY I get this error` "version node not found for symbol fuse_lowlevel_new@FUSE_2.5"`, . I have the version script, and im caling it with 

> common_ldflags :=  -Wl,--version-script,$(LIB_PATH_ABS)/fuse_versionscript 
> LOCAL_LDFLAGS := $(common_ldflags)
> 

So im building as a SHARED LIBRARY, but im no sure if this can be a problem as i get an error when I trie to build as STATIC. Anyone knows the how to correct the error? 

Im also building the hello example, as a SHARED LIBRARY, I have replaced  the main() with a function that i call from java, I pass a string of the folder where the fs will be mounted:
```
... rest of the code ...
//replaced main with this
int mount_fs(	int argc, char *argv[]) {

	return fuse_main(argc, argv, &hello_oper, NULL);
}

JNIEXPORT jstring JNICALL
Java_com_pauloribeiro_testlibfusecm12_MainActivity_test(JNIEnv *env, jobject instance, jstring s_) {
	const char *s = (*env)->GetStringUTFChars(env, s_, 0);

	char *mounfolder = "/mountfolder";
	char mountdir[256];
	strcpy(mountdir, s);
	strcat(mountdir, mounfolder);
	char* argv[6];
	argv[0] = "hello";
	argv[1] = "-s";
    argv[2] = "-f";
    argv[3] = "-o";
    argv[4] = "allow_other";
    argv[5] = mountdir;
    struct stat st = {0};

	if (stat(mountdir, &st) == -1) {
		int status = mkdir(mountdir, 0755);
        __android_log_print(ANDROID_LOG_DEBUG, "LOG_TAG", "mkdir mount status: %d", status);
	}


    char returnv[1024];
	int res = mount_fs(6, argv);

    sprintf(returnv, "Return fuse_main() : %d. dir: %s", res, argv[5]);


	(*env)->ReleaseStringUTFChars(env, s_, s);

	return (*env)->NewStringUTF(env, returnv);
}
```

But i get an error. After some time doing debugging from c to logcat e found the error: 
`"fuse: failed to open /dev/fuse: Permission denied".`

Android.mk:
```
LOCAL_PATH` := $(call my-dir)
LIB_PATH_ABS := $(call my-dir)/libfuse/lib
LIB_PATH_REL := libfuse/lib

common_src_files := \
	$(LIB_PATH_REL)/buffer.c \
	$(LIB_PATH_REL)/cuse_lowlevel.c \
	$(LIB_PATH_REL)/fuse.c \
	$(LIB_PATH_REL)/fuse_kern_chan.c \
	$(LIB_PATH_REL)/fuse_loop.c \
	$(LIB_PATH_REL)/fuse_loop_mt.c \
	$(LIB_PATH_REL)/fuse_lowlevel.c \
	$(LIB_PATH_REL)/fuse_mt.c $(LIB_PATH_REL)/fuse_opt.c \
	$(LIB_PATH_REL)/fuse_session.c \
	$(LIB_PATH_REL)/fuse_signals.c \
	$(LIB_PATH_REL)/helper.c \
	$(LIB_PATH_REL)/mount.c \
	$(LIB_PATH_REL)/mount_util.c \
	$(LIB_PATH_REL)/ulockmgr.c

common_c_includes := \
	$(LIB_PATH_ABS)/../android \
	$(LIB_PATH_ABS)/../include


common_shared_libraries := \
	libutils

common_cflags := \
	-D_FILE_OFFSET_BITS=64 \
	-DFUSE_USE_VERSION=26 \
    -fno-strict-aliasing

common_ldflags := \
     -Wl,--version-script,$(LIB_PATH_ABS)/fuse_versionscript

include $(CLEAR_VARS)
LOCAL_MODULE := libfuse
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(common_src_files)
LOCAL_C_INCLUDES := $(common_c_includes)
LOCAL_EXPORT_C_INCLUDES := $(common_c_includes)
LOCAL_STATIC_LIBRARIES := $(common_shared_libraries)
LOCAL_CFLAGS := $(common_cflags) -fPIC
LOCAL_EXPORT_CFLAGS := $(common_cflags) -fPIC
LOCAL_LDFLAGS := $(common_ldflags)
LOCAL_CLANG := true
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_SHARED_LIBRARIES := libfuse
LOCAL_MODULE    := hello
LOCAL_SRC_FILES := hello.c
LOCAL_CLANG := true
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog

include $(BUILD_SHARED_LIBRARY)
```

Java/Android:
```
	static {
		System.loadLibrary("fuse");
		System.loadLibrary("hello");
	}

	public native String test(String s);

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		TextView tv = (TextView) findViewById(R.id.text);
		File f = getApplicationContext().getFilesDir();
		tv.setText(test(f.toString()));
	}
}
```
Can anyone help me? I'm tying to put this to work for 6 straight days.

I really need this to compile, As I need to write an Android App for my Master Thesis that uses fuse to mount a filesystem with files from the cloud.

**Comment by Nikratio** [comment]
Uh, not sure what to do with this. As you have said yourself, you have a problem with some forked version of libfuse that's included with Cyanogen, so posting this on the libfuse bugtracker is unlikely to help. Also, it seems you don't actually found a bug but just need help with correct usage. Maybe there is Cyanogen mailing list you could use? You can also try posting on fuse-devel, but I wouldn't get my hopes up too much.

**Comment by mdmoore313** [comment]
I got the same error. It's due to the versionmap file being included with the source, if you delete it and delete the preprocessor tags that reference the error symbols the error should go away.
