### ISSUE TITLE
test_passthrough FAILED

### ISSUE THREAD

**Issue by noamshalev** [libfuse/libfuse#111]
Hi, I just downloaded libfuse and followed the Installation section.
As it says, I use 
`python3 -m pytest test/`
to test it.

The first 4 tests pass, however - the fifth test fails:
> test/test_examples.py::test_passthrough[True-passthrough] FAILED

and I get the output:

> ...
> 40 [open(-, O_RDWR | O_CREAT, 0200)] OK
>  41 [open(-, O_RDWR | O_CREAT, 0000)] OK
>  42 [open(-, O_RDWR | O_CREAT | O_EXCL, 0600)] OK
>  43 [open(+, O_RDWR | O_CREAT | O_EXCL, 0600)] OK
>  44 [open(-, O_RDWR | O_CREAT | O_EXCL, 0000)] OK
>  45 [open(+, O_RDWR | O_CREAT | O_EXCL, 0000)] OK
>  46 [open_acc(O_RDONLY) mode: 0600 message: 'Success'] OK
>  47 [open_acc(O_WRONLY) mode: 0600 message: 'Success'] OK
>  48 [open_acc(O_RDWR) mode: 0600 message: 'Success'] OK
>  49 [open_acc(O_RDONLY) mode: 0400 message: 'Success'] OK
>  50 [open_acc(O_RDONLY | O_TRUNC) mode: 0400 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  51 [open_acc(O_WRONLY) mode: 0400 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  52 [open_acc(O_RDWR) mode: 0400 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  53 [open_acc(O_RDONLY) mode: 0200 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  54 [open_acc(O_WRONLY) mode: 0200 message: 'Success'] OK
>  55 [open_acc(O_RDWR) mode: 0200 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  56 [open_acc(O_RDONLY) mode: 0000 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  57 [open_acc(O_WRONLY) mode: 0000 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  58 [open_acc(O_RDWR) mode: 0000 message: 'Permission denied'] do_test_open_acc() - open should have failed
>  59 [open(O_CREAT) in read-only directory] OK
>  60 [open(O_CREAT | O_EXCL) in read-only directory] OK
>  61 [open(O_CREAT | O_WRONLY) in read-only directory] OK
>  62 [open(O_CREAT | O_TRUNC) in read-only directory] OK
> 8 tests failed

How can I fix it?

**Comment by Nikratio** [comment]
Good question. Are you running as root or regular user? Which kernel version? What file system are you using for /tmp and the fuse directory?

**Comment by noamshalev** [comment]
Running as root. 
Kernel version 3.16.0, ext4.

**Comment by Nikratio** [comment]
Thanks! There was a bug running the tests as root, the fix will be included in the next release. As long as the tests run fine as a regular user, you can ignore the failures as root.
