### ISSUE TITLE
Look into FUSE_LSEEK operation

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#115]
`fs/fuse/file.c` defines a `FUSE_LSEEK` operation. However, there is no such support in libfuse. We need to look into this.

**Comment by Nikratio** [comment]
Support exists only in GlusterFS so far, but should be added to libfuse. See

https://github.com/gluster/glusterfs/blob/master/xlators/mount/fuse/src/fuse-bridge.c
 https://sourceforge.net/p/fuse/mailman/message/34227449/

**Comment by Nikratio** [comment]
Relevant kernel commit: 0b5da8d

**Comment by amosonn** [comment]
I didn't see this issue (and opened a dup) because a search for "seek" didn't yield it. Now it should.
