### ISSUE TITLE
Add support for FUSE_POSIX_ACL

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#117]
Introduced in commit 60bcc8, but no userspace support yet.

**Comment by jpandre** [comment]
What kind of userspace support are you foreseeing ?
The recent commit is for supporting the Posix ACLs within the kernel, so that the userspace has nothing special to do, and the change makes no difference for file system doing the job themselves.

**Comment by Nikratio** [comment]
I haven't looked at in in detail, I just noticed that there is a new `FUSE_POSIX_ACL` capability flag that userspace doesn't know about. So at minimum we should make that flag available for filesystems.

**Comment by Nikratio** [comment]
According to the kernel commit, userspace still needs to keep the file mode in  in sync, and ensure correct inheritance of default ACLs when new filesystem nodes are created.

This is, however, a bit unfortunate because it would require userspace to re-construct ACLs from the xattr representation. I'll have to take a second look at the discussion about this, I thought this wouldn't be necessary.
