### ISSUE TITLE
Publish FUSE documentation generated using Doxygen

### ISSUE THREAD

**Issue by marcinsulikowski** [libfuse/libfuse#12]
Is there any place in the Internet where HTML version of FUSE library documentation can be found? I was using http://fuse.sourceforge.net/doxygen/ which was very convenient, but there is nothing there now. If the project moved to GitHub, how about moving the HTML documentation here? GitHub has a nice mechanism for serving static HTML pages (https://pages.github.com/) which can be used to make the documentation available again -- just create a new repository libfuse/libfuse.github.io and push HTML files there. It would be very convenient to have the documentation for all the official FUSE releases available in this way.

**Comment by Nikratio** [comment]
Done, should be available on http://libfuse.github.io/doxygen.
