### ISSUE TITLE
fuse blocks in fuse_file_write_iter when acquiring mutex

### ISSUE THREAD

**Issue by optyfr** [libfuse/libfuse#125]
Hello
I got this today on an NFS server that was only sharing S3QL mounts (8 shares), it seems to be locked in FUSE, so I don't know if it's S3QL related (nothing special in mount.log), FUSE related, or NFSd related, ... May there be something wrong in parameters that could lead to this?

It is a Debian Jessie up to date, with S3QL 2.21, and only NFSv3 connections were used
The only solution I found to unblock was to reset the server then fsck all to get it up again

Any idea?

Nov 29 14:25:09 shares kernel: [541757.931571] INFO: task nfsd:6712 blocked for more than 120 seconds.
Nov 29 14:25:09 shares kernel: [541757.931629]       Not tainted 3.16.0-4-amd64 #1
Nov 29 14:25:09 shares kernel: [541757.931649] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Nov 29 14:25:09 shares kernel: [541757.931680] nfsd            D ffff88003ba504a8     0  6712      2 0x00000000
Nov 29 14:25:09 shares kernel: [541757.931718]  ffff88003ba50050 0000000000000046 0000000000012f40 ffff88003b3dffd8
Nov 29 14:25:09 shares kernel: [541757.931753]  0000000000012f40 ffff88003ba50050 ffff8800036860e8 ffff88003b3dfb40
Nov 29 14:25:09 shares kernel: [541757.931787]  ffff8800036860ec ffff88003ba50050 00000000ffffffff ffff8800036860f0
Nov 29 14:25:09 shares kernel: [541757.931820] Call Trace:
Nov 29 14:25:09 shares kernel: [541757.931849]  [<ffffffff815151d5>] ? schedule_preempt_disabled+0x25/0x70
Nov 29 14:25:09 shares kernel: [541757.931877]  [<ffffffff81516c33>] ? __mutex_lock_slowpath+0xd3/0x1c0
Nov 29 14:25:09 shares kernel: [541757.931905]  [<ffffffff8101255e>] ? __switch_to+0xde/0x5a0
Nov 29 14:25:09 shares kernel: [541757.931929]  [<ffffffff81516d3b>] ? mutex_lock+0x1b/0x2a
Nov 29 14:25:09 shares kernel: [541757.932053]  [<ffffffffa01b836f>] ? fuse_file_write_iter+0x8f/0x2b0 [fuse]
Nov 29 14:25:09 shares kernel: [541757.932086]  [<ffffffff81514951>] ? __schedule+0x2b1/0x6f0
Nov 29 14:25:09 shares kernel: [541757.932111]  [<ffffffff811aa0c0>] ? new_sync_read+0xa0/0xa0
Nov 29 14:25:09 shares kernel: [541757.932135]  [<ffffffff811aa1bf>] ? do_iter_readv_writev+0x5f/0x90
Nov 29 14:25:09 shares kernel: [541757.932161]  [<ffffffff811ab71b>] ? do_readv_writev+0xbb/0x240
Nov 29 14:25:09 shares kernel: [541757.932187]  [<ffffffffa01b82e0>] ? fuse_perform_write+0x4b0/0x4b0 [fuse]
Nov 29 14:25:09 shares kernel: [541757.932221]  [<ffffffffa01b82e0>] ? fuse_perform_write+0x4b0/0x4b0 [fuse]
Nov 29 14:25:09 shares kernel: [541757.932252]  [<ffffffffa01b628f>] ? fuse_open_common+0xcf/0xe0 [fuse]
Nov 29 14:25:09 shares kernel: [541757.932279]  [<ffffffff811a82b7>] ? do_dentry_open+0x257/0x330
Nov 29 14:25:09 shares kernel: [541757.932334]  [<ffffffffa03f28b9>] ? nfsd_vfs_write.isra.12+0x99/0x360 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932366]  [<ffffffffa03f5fb1>] ? nfsd_write+0xf1/0x110 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932399]  [<ffffffffa03fbe5c>] ? nfsd3_proc_write+0xac/0x130 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932469]  [<ffffffffa03eed32>] ? nfsd_dispatch+0xb2/0x200 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932565]  [<ffffffffa0352d3b>] ? svc_process_common+0x41b/0x670 [sunrpc]
Nov 29 14:25:09 shares kernel: [541757.932636]  [<ffffffffa03ee630>] ? nfsd_destroy+0x70/0x70 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932704]  [<ffffffffa035309c>] ? svc_process+0x10c/0x160 [sunrpc]
Nov 29 14:25:09 shares kernel: [541757.932773]  [<ffffffffa03ee6ef>] ? nfsd+0xbf/0x130 [nfsd]
Nov 29 14:25:09 shares kernel: [541757.932834]  [<ffffffff810894bd>] ? kthread+0xbd/0xe0
Nov 29 14:25:09 shares kernel: [541757.932897]  [<ffffffff81089400>] ? kthread_create_on_node+0x180/0x180
Nov 29 14:25:09 shares kernel: [541757.932962]  [<ffffffff815184d8>] ? ret_from_fork+0x58/0x90
Nov 29 14:25:09 shares kernel: [541757.933560]  [<ffffffff81089400>] ? kthread_create_on_node+0x180/0x180

**Comment by Nikratio** [comment]
This looks like a bug in the fuse kernel module to me.

This GitHub project is primarily for *libfuse*, the userspace library. I'm happy to keep track of kernel issues in this  issue tracker as well, but please note that it's quite unlikely that reporting kernel issues here will be sufficient to get them fixed. 

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, e.g. [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) or [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel).

**Comment by Nikratio** [comment]
After reviewing the activity on kernel bugs reported on this tracker, I've come to the conclusion that there actually isn't much point in tracking most of these bugs here. Mostly there is only an initial report, so it's unclear if the problem was reported upstream and/or fixed, and the issue never gets closed.
