### ISSUE TITLE
Use semantic versioning to define the releases

### ISSUE THREAD

**Issue by piranna** [libfuse/libfuse#126]
At this moment the 3.x releases are market with things like `3.0.0rc3`, that don't follow the semver format. Please add an hyphen to make it to be like `3.0.0-rc3`.

**Comment by Nikratio** [comment]
I don't like using dashes for this purpose, because it conflicts with Debian's use of the dash to separate upstream version from Debian version.

In any case, there probably won't be RC candidates again until FUSE 4.0, so this is water under the bridge :-).
