### ISSUE TITLE
fuse3: `mount.fuse3` manpage should match its binary name

### ISSUE THREAD

**Issue by anatol** [libfuse/libfuse#129]
The default name of the fuse3 binary is `mount.fuse3`. Currently the installed manpage name is `/usr/share/man/man8/mount.fuse.8.gz`, it should match the binary name i.e. `/usr/share/man/man8/mount.fuse3.8.gz`

**Comment by Nikratio** [comment]
This manpage does not actually document the `mount.fuse` program. Maybe a better name for the manpage would be appropriate, but I'm not sure if that's enough of a reason to rename...

**Comment by anatol** [comment]
Currently fuse2 and fuse3 packages install the same file `/usr/share/man/man8/mount.fuse.8.gz`. How package maintainers suppose to resolve this issue? Please advice.

**Comment by Nikratio** [comment]
Please take  a look at the ChangeLog: https://github.com/libfuse/libfuse/blob/fuse_3_0_bugfix/ChangeLog.rst
