### ISSUE TITLE
Cannot build example/ because 'config.h'

### ISSUE THREAD

**Issue by maxtortime** [libfuse/libfuse#13]
When I clone GitHub repo(master branch) and build example directory. like on 'hello.c'
```sh
gcc -Wall hello.c `pkg-config fuse --cflags --libs` -o hello
```
But I failed. So I downloaded release v2.9.5 and I succeeded build.

I think that this repo missed 'config.h'.

**Comment by jafffy** [comment]
Can you put your compile error messages?

**Comment by Nikratio** [comment]
When building from git, you need to run `makeconf.sh` first.
