### ISSUE TITLE
How can I build this under windows using cygwin ?

### ISSUE THREAD

**Issue by AdminOfLife** [libfuse/libfuse#134]
I'm trying to compile under Windows using сygwin, but eventually do make-j8 command error occurs

> ../include/fuse_kernel.h:759:41: error: expected expression before 'uint32_t'
>   #define FUSE_DEV_IOC_CLONE _IOR (229, 0, uint32_t).

Please help deal with this problem, which is already just trying to build library, but this error does not allow it to make

**Comment by Nikratio** [comment]
FUSE does not support cygwin, sorry. I'm not sure it would even make sense - does the Windows kernel support the FUSE protocol?
