### ISSUE TITLE
install

### ISSUE THREAD

**Issue by glazkow** [libfuse/libfuse#135]
commands
$ ./configure
$ make
$ Sudo make install
not work in the console displays
root @ hostname: / usr / src / libfuse # ./configure
-bash: ./configure: No such file or directory
root @ hostname: / usr / src / libfuse #

**Comment by Nikratio** [comment]
Sorry, I don't follow. Could you please copy and paste the exact commands that you typed and errors that you got?

**Comment by Nikratio** [comment]
(please feel free to re-open with more information)

**Comment by glazkow** [comment]
git clone https://github.com/libfuse/libfuse.git
cd /usr/src/libfuse
root @ hostname: / usr / src / libfuse # ./configure
-bash: ./configure: No such file or directory

**Comment by glazkow** [comment]
git clone  https://github.com/libfuse/libfuse.git
cd /usr/src/libfuse
root @ hostname: / usr / src / libfuse # ./configure
-bash: ./configure: No such file or directory

**Comment by Nikratio** [comment]
When you are building from git. you need to run ./makeconf.sh first.

**Comment by lordbeerus0505** [comment]
I am not able to run your package, could you provide a detailed procedure, the one on README doesnt work for me. Running on ubuntu 17.10

**Comment by Nikratio** [comment]
Thanks for reporting this! However, without giving a little more information about what you've tried and what doesn't work there isn't much I can do to help. Unrelated to that, please also use the mailing list for this kind of question. Attaching them to a closed bug makes them rather invisible :-).
