### ISSUE TITLE
Document minimum required Meson version

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [libfuse/libfuse#138]
When following the installation guide, this is what happens:

:~/Desktop/fuse3/build$ meson ..
The Meson build system
Version: 0.29.0
Source dir: ~/Desktop/fuse3
Build dir: ~/Desktop/fuse3/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: libfuse3
Native c compiler: cc (gcc 5.4.0-6ubuntu1)

Meson encountered an error in file meson.build, line 18, column 4:
Unknown method "set_quoted" in object.

**Comment by Nikratio** [comment]
Thanks for the report! Probably your Mesion verson is too old. I'll document the minimum required version.

**Comment by Rondom** [comment]
Not familiar with meson, but I assume [there is a way to define a minimum meson-version in the code](https://github.com/mesonbuild/meson/wiki/Reference%20manual#project). 

Of course, it can still be documented for those people who do read the docs.
