### ISSUE TITLE
Makefile does not support `--program-suffix` configure option

### ISSUE THREAD

**Issue by harvv** [libfuse/libfuse#140]
This is for version 3.0.0-bugfix.

using --program-suffix as a parameter to ./configure seems to omit the suffix provided when generating the 'install' rule in the Makefile, which leads to 'make' attempting to operate on a missing file.  Excerpt from 'make install' run:

chmod: cannot access ‘/opt/bin/fusermount3’: No such file or directory
make[4]: [install-exec-hook] Error 1 (ignored)

(i.e. it is referring to an "undecorated" fusermount3 filename, when really the file is fusermount3<suffix>)

**Comment by Nikratio** [comment]
Uh, is there actually a usecase for using this option?

I'd be happy to apply a patch, but I don't think I will ever look into this.

**Comment by Nikratio** [comment]
Closing this for now. Feel free to reopen with a patch if someone needs this feature.
