### ISSUE TITLE
FUSE_CAP_AUTO_INVAL_DATA ignores attr_timeout

### ISSUE THREAD

**Issue by rorybolt** [libfuse/libfuse#142]
Implementing a "do nothing" file system in 3.0.0pre0 and running fio with 4k random reads and queue depth 32 I observed performance of ~ 400K IOPS

Running the exact same test on the same hardware, the release version only gets ~ 100K IOPS

fio command:
fio --ioengine=libaio --iodepth=32 --direct=1 --invalidate=1 --name=zerofile --size=600m --rw=randread --numjobs=1 --time_based --runtime=20

"do nothing" file system (modified hello_ll.c) attached...
[test.zip](https://github.com/libfuse/libfuse/files/781213/test.zip)

NOTE: Further testing indicates this performance drop was introduced between rc1 and rc3. 

RESOLVED:  This is a side effect of the change to call getattr on every read. Clearing the FUSE_CAP_AUTO_INVAL_DATA flag in init will give the previous level of performance. Given that this is such a large performance hit, this should probably be called out in the documentation...

**Comment by Nikratio** [comment]
Uhm, your example sets the attr_timeout to 1 second, so I think even with `FUSE_CAP_AUTO_INVAL_DATA`, it should not be calling *getattr()* on every read.

**Comment by Nikratio** [comment]
Which kernel version are you running? With 4.9, I am getting only one *getattr* call per second (using the unmodified `hello_ll` shipped with FUSE):

```
$ ./hello_ll -d -s ~/tmp/mnt
FUSE library version: 3.1.0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003fffb
max_readahead=0x00020000
   INIT: 7.26
   flags=0x00009029
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   time_gran=0
   unique: 1, success, outsize: 80
unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 11593
   unique: 2, error: -38 (Function not implemented), outsize: 16
[...]
```

In another console, with Python:

```
fd = os.open('tmp/mnt/hello')
In [29]: for i in range(10):
    ...:     os.read(fd, 1)
```

gives just

```
unique: 152, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 4009
   unique: 152, success, outsize: 144
unique: 153, opcode: OPEN (14), nodeid: 2, insize: 48, pid: 4009
   unique: 153, success, outsize: 32
unique: 154, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 154, success, outsize: 120
unique: 155, opcode: READ (15), nodeid: 2, insize: 80, pid: 4009
   unique: 155, success, outsize: 29
unique: 156, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 156, success, outsize: 120
```


while

```
os.lseek(fd, 0, 0)
for i in range(10):
    time.sleep(1.1)
    os.read(fd, 1)
```

gives

```unique: 157, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 157, success, outsize: 120
unique: 158, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 158, success, outsize: 120
unique: 159, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 159, success, outsize: 120
unique: 160, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 160, success, outsize: 120
unique: 161, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 161, success, outsize: 120
unique: 162, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 162, success, outsize: 120
unique: 163, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 163, success, outsize: 120
unique: 164, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 164, success, outsize: 120
unique: 165, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 165, success, outsize: 120
unique: 166, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 4009
   unique: 166, success, outsize: 120
```

**Comment by Nikratio** [comment]
Lacking further information, I'm closing this issue for now. Please feel free to reopen if you can provide more info.
