### ISSUE TITLE
How to deliver offset ,size in fuse callback function?

### ISSUE THREAD

**Issue by alsjfk** [libfuse/libfuse#143]
I wrote a c++ program with read like this:
read(fd_test,buf,19);
but in xmp_read(const char *path, char *buf, size_t size, off_t offset,struct fuse_file_info *fi)
the size and offset couldn't get the offset and size?
why?

**Comment by Nikratio** [comment]
Thanks for your interest in FUSE! Could you please send your question to FUSE mailing list
(https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
