### ISSUE TITLE
FUSE mount ignores suid/dev mount options when auto_unmount is specified

### ISSUE THREAD

**Issue by jjobi** [libfuse/libfuse#148]
FUSE mount is ignoring suid/dev mount options when auto_unmount option is specified.

**Comment by Nikratio** [comment]
Could you provide more information on how/when this fails? It seems to work with the examples:

```
$ ./passthrough_fh -o nodev ~/tmp/mnt
$ echo foo > ~/tmp/mnt/dev/null 
-bash: /home/nikratio/tmp/mnt/dev/null: Permission denied

$ fusermount -u ~/tmp/mnt
$ ./passthrough_fh -o nodev,auto_unmount ~/tmp/mnt

$ echo foo > ~/tmp/mnt/dev/null 
-bash: /home/nikratio/tmp/mnt/dev/null: Permission denied
```

**Comment by jjobi** [comment]
fuse_parse_cmdline() and fuse_level_low() when invoked with "-o suid,dev,auto_unmount" in the arguments, the file systems gets mounted with "nosuid,nodev".  You can see the output of mount command to verify.  "suid,dev" options get dropped somewhere in between.  If "auto_unmount" is not specified, then the file system gets mounted with the provided mount options.  I tested this with fuse.2.9.7.

**Comment by Nikratio** [comment]
I see. When you run as root, fuse normally does not call `fusermount` but uses the mount system call directly. When you specify `auto_unmount`, it goes through `fusermount` instead. However, `fusermount` is a setuid binary that is normally called by regular users, so it cannot in general accept `suid` or `dev` options.

It may be possible for `fusermount3` to check if it was actually called as root (rather than running as root because of being setuid) and, in that case, accept the `dev` and `suid` options. Patches welcome :-).

**Comment by Nikratio** [comment]
Now that this is at least documented, turning it into an enhancement request...

**Comment by jjobi** [comment]
I could get this working with the following change

fuse-3.0.0/util/fusermount.c  2016-11-29 08:26:29.000000000 -0800
fuse-3.0.0/util/fusermount.c.new        2017-03-21 19:18:33.489382420 -0700
***************
*** 715,721 ****
                    char **mnt_optsp)
  {
        int res;
!       int flags = MS_NOSUID | MS_NODEV;
        char *optbuf;
        char *mnt_opts = NULL;
        const char *s;
--- 715,721 ----
                    char **mnt_optsp)
  {
        int res;
!     int flags = getuid() ? (MS_NOSUID | MS_NODEV) : 0;
        char *optbuf;
        char *mnt_opts = NULL;
        const char *s;

**Comment by Nikratio** [comment]
I hope you know that your patch introduces a big security hole. With it, ordinary users are able to mount their filesystems with suid and dev enabled - i.e., you are effectively giving root access to every user who can mount FUSE filesystems.

**Comment by pallavagarwal07** [comment]
Wouldn't getuid() line prevent that?
getuid *should* return the real uid of the user (not the euid which would be 0)

**Comment by paulrobello** [comment]
I have a project that would benefit from this being resolved.
Is there any plan for this?

**Comment by matthiasgoergens** [comment]
https://github.com/libfuse/libfuse/pull/759 has one way to implement @jjobi's suggestion without opening a security can-of-worms.

It's not pretty, though.

**Comment by Nikratio** [comment]
Actually, the above proposal (setting flags dependent on getuid) looks like it should work in practice.

However, the security implications are big so I do not want to commit this merely on the basis that it "looks okay". The solution with the separate binary is less elegant, but also less risky.

**Comment by matthiasgoergens** [comment]
@Nikratio I thought a bit more about the solution using two binaries, but found a simpler one.  It breaks out the watcher for `auto_unmount` to be used separately.  That might be useful for other applications as well.

(It might be worth doing a bigger refactor to put that watcher into its own binary, in the end?)
