### ISSUE TITLE
meson missing in release files ?

### ISSUE THREAD

**Issue by kyrios123** [libfuse/libfuse#153]
Hello,

I just downloaded the latest version of libfuse (version 3.0.0).
I wanted to build and install it using the recommended version of the README.md (Meson and Ninja) but it appears the `meson.build` files are missing in the tarball !?
(or perhaps there is something I missed?)

Thanks!

**Comment by Nikratio** [comment]
Meson support is currently only in Git (that's why you can see it on the homepage), but was not yet included in the last release. It will be in the next one.

**Comment by kyrios123** [comment]
Ok! thanks for the quick answer !
