### ISSUE TITLE
lazy interface: user_data goes into a black hole

### ISSUE THREAD

**Issue by nobrowser** [libfuse/libfuse#155]
Hi,

all the examples in the distribution using the "lazy" interface (i.e. `fuse_main`) pass `NULL` for the `user_data` argument.  Is it intended to be useful after all?  'Cause there seems to be no way to retrieve it from the actual filesystem operations. There is `fuse_get_context()` which returns a structure with the `fuse` object pointer, and if that structure and the `fuse_fs` structure were transparent to programs, that would work because the original `user_data` pointer is stored in the `fuse_fs`.  But the structures are opaque :-(

An easy fix would be to provide a new function `fuse_get_user_data` that would just chase the pointers without exposing the structures.  I can write a patch, but I was wondering maybe if I misunderstood.  I was trying to use `user_data` to pass information derived from command line flags (specific to my filesystem) down to the operations.  Is there a different recommended way to do that?

**Comment by Nikratio** [comment]
I don't understand. `fuse_get_context()` returns an object of type `struct fuse_context`. This type is defined in `fuse.h`, i.e. accessible to your project. And the `private_data` field contains your private data.

`fuse_main()` is deliberately kept simple. I guess the silent assumption is that if you use `fuse_main()`, then you can also just use a global variable for your private data. However, you can still return private data from your `init()` handler. Or, you implement your own main function that calls `fuse_new` with the right parameters.

Am I missing something?

**Comment by nobrowser** [comment]
Well, I think we're both missing a couple of things.

First, what _I_ missed was that `fuse_fs_init` sets `private_data` to `user_data`.  I had to look at the source code to learn that; it is not documented anywhere I can see, so from the POV of a library user who wants to treat the library as a black box, it doesn't exist.

Second, I think that _your_ point about `fuse_main` isn't valid because, after all, `fuse_main` _does_ take the `user_data` arg.  It has to be there for _some_ purpose, right?  But just reading the docs and examples, such purpose is not forthcoming.

I guess this is just a simple documentation deficiency, now.

Thanks for replying.
