### ISSUE TITLE
Unlink test failure in passthrough

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#157]
On travis, the passthrough example still fails with an outdated st_nlink count when removing a hardlink:

https://travis-ci.org/libfuse/libfuse/builds/220776242

**Comment by Nikratio** [comment]
As a first step, we need to determine if this affects just `passthrough`, or also `passthrough_fh` (and maybe `passthrough_ll`). This is a litlte difficult - I just configured Travis to keep running after the first failed test - but now everything passes.

**Comment by Nikratio** [comment]
In https://travis-ci.org/libfuse/libfuse/builds/236116701, only `passthrough` is affected.

**Comment by Nikratio** [comment]
This very much looks like a race condition (note that at least in the above example, the test worked with debugging output enabled which slows things down). I just don't see where the race condition could come from. The kernel should be forwarding every stat() call to the filesystem.

**Comment by trapexit** [comment]
Could it be due to the async nature of unlink in the high level api? `hard_remove`?

**Comment by Nikratio** [comment]
Good question. If the file was renamed instead of unlinked, we would indeed get the same symptoms. However, hard_rename should only have an effect if the file is currently open - and the test certainly doesn't open it. So this would mean that something external to the test is - at some times - opening the testfile.

**Comment by Nikratio** [comment]
On the other hand, if the kernel does not enqueue a `release` request right after the file has been closed, it may be possible for the `unlink` and `stat` requests to sneak in before that.  Need to check the kernel sources...

Alternatively, when running multi-threaded the thread executing the `release` may complete only after `unlink` and `stat`, despite it being enqueued earlier. In this case, disabling multi-threading should fix the issue.

**Comment by Nikratio** [comment]
I couldn't decipher the kernel code, asked on linux-fsdevel for help.

**Comment by Nikratio** [comment]
I think I have a pretty good idea of why this is happening and how to fix it now. Unfortunately, reproducing the problem seems rather complicated. Therefore, I have committed the fix without being able to test it. We'll see if the problem pops up on Travis again.
