### ISSUE TITLE
Fuse requesting higher size than filesize

### ISSUE THREAD

**Issue by ultimate-tester** [libfuse/libfuse#158]
In the read method, I wonder why the size parameter can be greater than the actual file size.
Using tail -c 500 on a file inside the filesystem will result on a file request larger than the actual file size. To counter this one would need a check to limit the size to the actual file size. One does not know the filesize inside the read method, or do you? Getting the filesize might take a long time and will definitely block the read method for a long time. Am I supposed to keep my own file struct in FUSE purely to know the filesize at the read method? How did others implement this?

**Comment by Nikratio** [comment]
If you don't know the file size, then the kernel (or userspace) certainly does not know it either. So how are they supposed to ensure that the size parameter is less than that?

This sounds more like a question for the fuse-devel mailing list than a bug in fuse, so I'm closing this for now.
