### ISSUE TITLE
fuse_main() resets SIGPIPE back to SIG_DFL after SIG_IGN set by caller

### ISSUE THREAD

**Issue by DavidButterfield** [libfuse/libfuse#160]
(Noticed while reading code; not verified by execution.)
Referring to https://github.com/libfuse/libfuse/blob/master/lib/fuse_signals.c

Suppose the caller of fuse_main() has already ignored SIGPIPE, e.g.:

```
    struct sigaction act = (struct sigaction) { .sa_handler = SIG_IGN };
    int rc = sigaction(SIGPIPE, &act, NULL);
```

Then during fuse_main() initialization, I believe set_one_signal_handler() -- called from fuse_set_signal_handlers() -- will correctly skip setting the SIGPIPE signal, because the signal is not currently set to SIG_DFL.

But later at fuse thread shutdown, it looks like the call from fuse_remove_signal_handlers() to set_one_signal_handler(SIGPIPE, SIG_IGN, 1) will "remove" the SIG_IGN SIGPIPE signal setting that was set by the *caller* of fuse_main(), thus not leaving the signal the way it originally found it.  That does not seem optimal.

```
static int set_one_signal_handler(int sig, void (*handler)(int), int remove)
{
    struct sigaction sa;
    struct sigaction old_sa;

    memset(&sa, 0, sizeof(struct sigaction));
    sa.sa_handler = remove ? SIG_DFL : handler;
    sigemptyset(&(sa.sa_mask));
    sa.sa_flags = 0;

    if (sigaction(sig, NULL, &old_sa) == -1) {
        perror("fuse: cannot get old signal handler");
        return -1;
    }  

    if (old_sa.sa_handler == (remove ? handler : SIG_DFL) &&
        sigaction(sig, &sa, NULL) == -1) {
        perror("fuse: cannot set signal handler");
        return -1;
    }  
    return 0;
}

void fuse_remove_signal_handlers(struct fuse_session *se)
{   ...
    set_one_signal_handler(SIGPIPE, SIG_IGN, 1);
}
```

**Comment by Nikratio** [comment]
Thanks for the report! I think you are right.

**Comment by Nikratio** [comment]
The documentation for `fuse_remove_signal_handlers` says: "*Restore default signal handlers*" - so the function actually behaves exactly as documented.

**Comment by DavidButterfield** [comment]
>
> The documentation for fuse_remove_signal_handlers says: "*Restore default
> signal handlers*" - so the function actually behaves exactly as
> documented.
>
C'mon, the current behavior is clearly unreasonable.  Think of the comments
you'd write above client code written to work around it!

And "restore" should be interpreted in terms of fuse's own behavior, not
that
of the main program on some other thread.  It isn't "restoring" if it puts
it
"back" into a different state than it found it.

The documentation probably was taken from the code.  It should be fixed too.

This probably doesn't affect most use cases where the purpose of the program
is to provide a filesystem.  In my case the program is a usermode server
using
fuse to provide an administrative interface that looks similar to a /proc
interface
as used by a kernel module.

This is a multi-threaded network server that starts and stops the fuse
thread
dynamically.  The symptom is a killer SIGPIPE coming in after shutting down
the fuse thread, even though my main program had explicitly set SIGPIPE to
SIG_IGN as necessary for socket I/O.  This does not seem like reasonable
behavior.

I have an adequate workaround.  But you still might want to improve fuse.

**Comment by Nikratio** [comment]
Huh? I assume you didn't see that the issue was already fixed? Or is there something that you dislike about the fix?

**Comment by DavidButterfield** [comment]
> I assume you didn't see that the issue was already fixed?

Right.  I just went by the messages I received "behaves exactly as
documented"
and "closed".  I didn't notice a "fixed" message.  Maybe that was implicit
in the
"via" part of the "closed" message?
