### ISSUE TITLE
how is max_write argument working?

### ISSUE THREAD

**Issue by sagarfan** [libfuse/libfuse#161]
given -o big_writes -o max_write=1048576 as command-line argument
but i did not find any changes than before.
             
static int xmp_write(const char *_path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)
this is the write function.
print size parameter, max value is 128k.

how to specify a larger size for write request?

**Comment by trapexit** [comment]
You can't. big_write will use 128k by default which is the largest value
allowed due to a hard coded limit in the FUSE driver. AFAIK the only way to
increase it is to change the driver.

There are a few hidden limits in FUSE that should really be documented
better.
