### ISSUE TITLE
A question about max write size

### ISSUE THREAD

**Issue by bastenlee** [libfuse/libfuse#162]
Hi Ａｌｌ,
	Is it possible to change the maximum write size more than 128K by
modifying fuse kernel/user-level code?

	Our project implements a fuse client to access a distributed storage.
We can change FUSE_MAX_PAGES_PER_REQ to bigger value to get the expected
read size(say, 4M) in one go, but the write size is still limited to
128K. The request size matters because our distributed storage is an
object storage with the object size much bigger than 128K.
We don't want the client request to be split, because split requests
will be considered multiple requests to the distributed storage, for
example, with object size 4M, a 4M request will be split into 32 storage
requests, the overhead is considerably large.

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is
a question about how to use fuse rather than a bug report. Please
use the fuse mailing list for this purpose. 
To subscribe, please visit https://lists.sourceforge.net/lists/listinfo/fuse-devel.
