### ISSUE TITLE
Threads and file descriptors

### ISSUE THREAD

**Issue by ng-marcus** [libfuse/libfuse#163]
I've been using fuse in multi-threaded mode along with the hiredis library.   In single threaded mode all works well, but in multi-threaded mode, the Redis server keeps indicating that the client has closed the connection.  I see this happening in tcpdump when the socket is closed.  All redis calls are wrapped in a mutex for thread safety.

The main thread when opening a redis connection gets an fd of 4.  I spotted the threads that came later got fd0 and up, and any thread where the redis connection was on fd0 suffered from the server closing the socket on it.

Looking in fuse_lowlevel.c in fuse_session_mount, I see the comment "Make sure file descriptors 0, 1 and 2 are open, otherwise chaos would ensue" and it makes some opens of /dev/null to move the fd id up to 3.

I've worked around the issue by throwing away my redis connections until I get a socket > 2 but as far as I can see fuse_session_mount is only called once per process, not per thread, so my question is why does the first thread need to skip these file descriptors (I guess they are related to stdin, stout, steer) and should this happen per thread?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is
a question about how to use fuse rather than a bug report. Please
use the fuse mailing list for this purpose. 
To subscribe, please visit https://lists.sourceforge.net/lists/listinfo/fuse-devel.

**Comment by ng-marcus** [comment]
In case anyone comes across this, the problem was of course mine.   FD zero should have given the game away earlier - I was closing an uninitialised file handle which of course comes out as a zero, and so I was sabotaging myself!   The fuselib works great!
