### ISSUE TITLE
Dealing with mount namespaces

### ISSUE THREAD

**Issue by t123yh** [libfuse/libfuse#164]
I have a sandbox that uses a mount namespace. I want to mount fuse inside that mount space, but leave the fuse server outside the mount namespace. (i.e. I want the actual `mount` to be executed inside my namespace)

Is that possibe? If not, what's the best solution?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Please use the fuse mailing list for this purpose.  To subscribe, please visit https://lists.sourceforge.net/lists/listinfo/fuse-devel.
