### ISSUE TITLE
Installation of libfuse-fuse-3.0.1.tar.gz

### ISSUE THREAD

**Issue by vgadhadaran** [libfuse/libfuse#165]
what are installation step for libfuse-fuse-3.0.1.tar.gz?

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Please use the fuse mailing list for this purpose. To subscribe, please visit https://lists.sourceforge.net/lists/listinfo/fuse-devel.
