### ISSUE TITLE
Error in the file of fuse_common.h

### ISSUE THREAD

**Issue by rmbeer** [libfuse/libfuse#168]
/usr/include/fuse3/fuse_common.h:744:69: error: anchura negativa en el campo de bits ‘_fuse_off_t_must_be_64bit_dummy_struct::_fuse_off_t_must_be_64bit’
  { unsigned _fuse_off_t_must_be_64bit:((sizeof(off_t) == 8) ? 1 : -1); };

This line can't compiling if the result is -1, not exist a size of -1 for the type of variable....

**Comment by trapexit** [comment]
That's intentional. Read the variable name. It's a compile time assert.

**Comment by rmbeer** [comment]
Then how to fix it? I need use the functions of fuse3, but this need 64bit instead of 32bit...

**Comment by rmbeer** [comment]
you must remember that fuse3 must adapt to the system and not backwards. If you or anyone hope that convert all apps to 64bits for the fuse3 then you are very wrongs.

**Comment by Rondom** [comment]
Whenever you compile something on 32bit, you should use  -D_FILE_OFFSET_BITS=64

**Comment by rmbeer** [comment]
yes, but is a bad idea. you have the stat() and stat64() for this. Also you can't use the 64bit from 32bit or 16bit size, is redundant.

**Comment by trapexit** [comment]
Why is it a bad idea? It's standard practice to enable transparent 64bit sizes and syscalls on 32 or 64 bit platforms. And 16bit isn't supported.

**Comment by rmbeer** [comment]
why not is compatible with machines of 32bit and 16bit, the fuse3 only work in 64bit, if the machine work only 32bit can work fine, but waste 4 bytes with 0s...

**Comment by trapexit** [comment]
It does work out  32bit machines. It just expects large file support. libc already manages the selection of syscalls. You generally shouldn't be calling the 64bit version explicitly.

**Comment by Rondom** [comment]
Those four bits are certainly not "wasted" given that files larger than 2 GB are commonplace also on 32-bit platforms.
Even if you claim that you will never encounter a file larger than 2 GB, you won't be able to deal with 64bit-inode numbers on 32bit because ino_t is 32bit if you don't set ` -D_FILE_OFFSET_BITS=64 `. This problematic because you will not even notice until you encounter an inode larger than 32bit.

**Comment by Nikratio** [comment]
As said in an earlier comment, this is not a bug but working as expected. As for how to compile libfuse on a 32-bit system, please use the mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel).
