### ISSUE TITLE
Take a 0 size from readdirplus()

### ISSUE THREAD

**Issue by rmbeer** [libfuse/libfuse#170]
Not say nothing in the document about of size_t = 0 where enter in the function...
Also in the examples not is prepared for support this value of size_t, always make memory with calloc() without check this value.

**Comment by Nikratio** [comment]
I am not sure what you are trying to say. Could you be more specific? Maybe provide an example that doesn't work as you expect?

I'm closing this issue for now, please feel free to re-open with additional information.
