### ISSUE TITLE
Building errors with Ninja

### ISSUE THREAD

**Issue by Le-Sir** [libfuse/libfuse#175]
Building with Meson seems to be working:
> Niemand:libfuse-master myname$ meson build
> The Meson build system
> Version: 0.40.1
> Source dir: /Users/myname/Downloads/libfuse-master
> Build dir: /Users/myname/Downloads/libfuse-master/build
> Build type: native build
> Project name: libfuse3
> Native c compiler: cc (clang 8.1.0)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Checking for function "fork": YES
> Checking for function "fstatat": YES
> Checking for function "openat": YES
> Checking for function "readlinkat": YES
> Checking for function "pipe2": NO
> Checking for function "splice": NO
> Checking for function "vmsplice": NO
> Checking for function "posix_fallocate": NO
> Checking for function "fdatasync": NO
> Checking for function "utimensat": NO
> Checking for function "setxattr": YES
> Checking for function "iconv": NO
> Checking whether type "struct stat" has member "st_atim": NO
> Checking whether type "struct stat" has member "st_atimespec": YES
> Configuring config.h using configuration
> Dependency threads found: YES
> Library dl found: YES
> Program install_helper.sh found: YES (/Users/myname/Downloads/libfuse-master/util/install_helper.sh)
> Build targets in project: 24

However, when I run Ninja in the build folder, I get a lot of errors:
> Niemand:build myname$ ninja
> [9/59] Compiling c object 'lib/fuse3@sha/fuse_loop_mt.c.o'
> ../lib/fuse_loop_mt.c:317:2: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
>         sem_init(&mt.finish, 0, 0);
>         ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/semaphore.h:55:5: note: 'sem_init' has been explicitly marked deprecated here
> int sem_init(sem_t *, int, unsigned int) __deprecated;
>     ^
> ../lib/fuse_loop_mt.c:341:2: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
>         sem_destroy(&mt.finish);
>         ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/semaphore.h:53:5: note: 'sem_destroy' has been explicitly marked deprecated here
> int sem_destroy(sem_t *) __deprecated;
>     ^
> 2 warnings generated.
> [12/59] Compiling c object 'lib/fuse3@sha/fuse_lowlevel.c.o'
> ../lib/fuse_lowlevel.c:2976:35: warning: unused parameter 'req' [-Wunused-parameter]
> int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
>                                   ^
> ../lib/fuse_lowlevel.c:2976:44: warning: unused parameter 'size' [-Wunused-parameter]
> int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
>                                            ^
> ../lib/fuse_lowlevel.c:2976:56: warning: unused parameter 'list' [-Wunused-parameter]
> int fuse_req_getgroups(fuse_req_t req, int size, gid_t list[])
>                                                        ^
> 3 warnings generated.
> [15/59] Compiling c object 'example/passthrough@exe/passthrough.c.o'
> ../example/passthrough.c:423:12: warning: implicit declaration of function 'lsetxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lsetxattr(path, name, value, size, flags);
>                   ^
> ../example/passthrough.c:432:12: warning: implicit declaration of function 'lgetxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lgetxattr(path, name, value, size);
>                   ^
> ../example/passthrough.c:440:12: warning: implicit declaration of function 'llistxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = llistxattr(path, list, size);
>                   ^
> ../example/passthrough.c:448:12: warning: implicit declaration of function 'lremovexattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lremovexattr(path, name);
>                   ^
> 4 warnings generated.
> [16/59] Compiling c object 'util/fusermount3@exe/util_mount_util.c.o'
> FAILED: util/fusermount3@exe/util_mount_util.c.o 
> cc  '-Iutil/fusermount3@exe' '-Iutil' '-I../util' '-I.' '-I../' '-Ilib' '-I../lib' '-Iinclude' '-I../include' '-Xclang' '-fcolor-diagnostics' '-pipe' '-D_REENTRANT' '-DHAVE_CONFIG_H' '-Wall' '-Wextra' '-Wno-sign-compare' '-Wstrict-prototypes' '-Wmissing-declarations' '-Wwrite-strings' '-O2' '-g' '-fno-strict-aliasing' '-MMD' '-MQ' 'util/fusermount3@exe/util_mount_util.c.o' '-MF' 'util/fusermount3@exe/util_mount_util.c.o.d' -o 'util/fusermount3@exe/util_mount_util.c.o' -c util/mount_util.c
> util/mount_util.c:24:10: fatal error: 'mntent.h' file not found
> #include <mntent.h>
>          ^
> 1 error generated.
> [18/59] Compiling c object 'example/passthrough_fh@exe/passthrough_fh.c.o'
> ../example/passthrough_fh.c:511:12: warning: implicit declaration of function 'lsetxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lsetxattr(path, name, value, size, flags);
>                   ^
> ../example/passthrough_fh.c:520:12: warning: implicit declaration of function 'lgetxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lgetxattr(path, name, value, size);
>                   ^
> ../example/passthrough_fh.c:528:12: warning: implicit declaration of function 'llistxattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = llistxattr(path, list, size);
>                   ^
> ../example/passthrough_fh.c:536:12: warning: implicit declaration of function 'lremovexattr' is invalid in C99 [-Wimplicit-function-declaration]
>         int res = lremovexattr(path, name);
>                   ^
> 4 warnings generated.
> [19/59] Compiling c object 'util/fusermount3@exe/fusermount.c.o'
> FAILED: util/fusermount3@exe/fusermount.c.o 
> cc  '-Iutil/fusermount3@exe' '-Iutil' '-I../util' '-I.' '-I../' '-Ilib' '-I../lib' '-Iinclude' '-I../include' '-Xclang' '-fcolor-diagnostics' '-pipe' '-D_REENTRANT' '-DHAVE_CONFIG_H' '-Wall' '-Wextra' '-Wno-sign-compare' '-Wstrict-prototypes' '-Wmissing-declarations' '-Wwrite-strings' '-O2' '-g' '-fno-strict-aliasing' '-MMD' '-MQ' 'util/fusermount3@exe/fusermount.c.o' '-MF' 'util/fusermount3@exe/fusermount.c.o.d' -o 'util/fusermount3@exe/fusermount.c.o' -c ../util/fusermount.c
> ../util/fusermount.c:24:10: fatal error: 'mntent.h' file not found
> #include <mntent.h>
>          ^
> 1 error generated.
> [20/59] Compiling c object 'lib/fuse3@sha/mount_bsd.c.o'
> FAILED: lib/fuse3@sha/mount_bsd.c.o 
> cc  '-Ilib/fuse3@sha' '-Ilib' '-I../lib' '-I.' '-I../' '-Iinclude' '-I../include' '-Xclang' '-fcolor-diagnostics' '-pipe' '-D_REENTRANT' '-DHAVE_CONFIG_H' '-Wall' '-Wextra' '-Wno-sign-compare' '-Wstrict-prototypes' '-Wmissing-declarations' '-Wwrite-strings' '-O2' '-g' '-fno-strict-aliasing' '-pthread' '-DFUSE_USE_VERSION=30' '-DFUSERMOUNT_DIR="{}"' '-MMD' '-MQ' 'lib/fuse3@sha/mount_bsd.c.o' '-MF' 'lib/fuse3@sha/mount_bsd.c.o.d' -o 'lib/fuse3@sha/mount_bsd.c.o' -c ../lib/mount_bsd.c
> ../lib/mount_bsd.c:105:29: warning: unused parameter 'outargs' [-Wunused-parameter]
>                                struct fuse_args *outargs)
>                                                  ^
> ../lib/mount_bsd.c:124:19: error: use of undeclared identifier 'SPECNAMELEN'
>         char device_path[SPECNAMELEN + 12];
>                          ^
> ../lib/mount_bsd.c:129:24: error: use of undeclared identifier 'SPECNAMELEN'
>         snprintf(device_path, SPECNAMELEN + 12, _PATH_DEV "%s", dev);
>                               ^
> ../lib/mount_bsd.c:182:55: warning: incompatible pointer types passing 'unsigned int *' to parameter of type 'size_t *' (aka 'unsigned long *') [-Wincompatible-pointer-types]
>         if (sysctlbyname("vfs.fuse.init_backgrounded", &ibg, &len, NULL, 0))
>                                                              ^~~~
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/sys/sysctl.h:760:48: note: passing argument to parameter here
> int     sysctlbyname(const char *, void *, size_t *, void *, size_t);
>                                                    ^
> 2 warnings and 2 errors generated.
> [21/59] Compiling c object 'lib/fuse3@sha/fuse.c.o'
> ninja: build stopped: subcommand failed.

**Comment by Nikratio** [comment]
libfuse does not support MacOS. You are probably looking for OSXFUSE.
