### ISSUE TITLE
Kernel Panic with fuse on redhat 6.8.4

### ISSUE THREAD

**Issue by rkotha5** [libfuse/libfuse#176]
Hello,

I am seeing kernel panic very often (every couple of days) with fuse on Redhat version 6.8.4

Kernel version is : 2.6.32-642

libfuse version: libfuse.so.2.8.3

The following is the call trace

Call Trace:
 <IRQ> 
 [<ffffffff814d88fe>] ? tcp_v4_rcv+0x4ee/0x950
 [<ffffffff814b5080>] ? ip_local_deliver_finish+0x0/0x2d0
 [<ffffffff814b515d>] ? ip_local_deliver_finish+0xdd/0x2d0
 [<ffffffff814b53e8>] ? ip_local_deliver+0x98/0xa0
 [<ffffffff814b48ad>] ? ip_rcv_finish+0x12d/0x440
 [<ffffffff814b4e35>] ? ip_rcv+0x275/0x350
 [<ffffffff81479801>] ? __netif_receive_skb+0x201/0x590
 [<ffffffff8147d668>] ? netif_receive_skb+0x58/0x60
 [<ffffffff8147d770>] ? napi_skb_finish+0x50/0x70
 [<ffffffff8147dd89>] ? napi_gro_receive+0x39/0x50
 [<ffffffffa01b0f60>] ? igb_poll+0x6c0/0xfe0 [igb]
 [<ffffffffa06057f6>] ? destroy_conntrack+0xd6/0x160 [nf_conntrack]
 [<ffffffff814aa117>] ? nf_conntrack_destroy+0x17/0x30
 [<ffffffffa0604fc4>] ? death_by_timeout+0x84/0x160 [nf_conntrack]
 [<ffffffff8108ed54>] ? cascade+0x84/0xb0
 [<ffffffff8147f293>] ? net_rx_action+0x103/0x300
 [<ffffffff81085275>] ? __do_softirq+0xe5/0x230
 [<ffffffff8100c38c>] ? call_softirq+0x1c/0x30
 [<ffffffff8100fca5>] ? do_softirq+0x65/0xa0
 [<ffffffff81085105>] ? irq_exit+0x85/0x90
 [<ffffffff81552e7a>] ? smp_apic_timer_interrupt+0x4a/0x60
 [<ffffffff8100bc13>] ? apic_timer_interrupt+0x13/0x20
 <EOI> 
 [<ffffffff8154bfee>] ? _spin_lock+0x1e/0x30
 [<ffffffffa05d923a>] ? fuse_dev_do_write+0xaa/0x5b0 [fuse]
 [<ffffffff81065614>] ? check_preempt_wakeup+0x1a4/0x260
 [<ffffffff81074d8b>] ? enqueue_task_fair+0xfb/0x100
 [<ffffffffa05d9a30>] ? fuse_dev_write+0x0/0x70 [fuse]
 [<ffffffffa05d9a9c>] ? fuse_dev_write+0x6c/0x70 [fuse]
 [<ffffffff8119985b>] ? do_sync_readv_writev+0xfb/0x140
 [<ffffffff8106c530>] ? wake_up_state+0x10/0x20
 [<ffffffff810a68a0>] ? autoremove_wake_function+0x0/0x40
 [<ffffffff8112eb7f>] ? filemap_fdatawait+0x2f/0x40
 [<ffffffffa04f9eab>] ? nfs_attribute_cache_expired+0x1b/0x70 [nfs]
 [<ffffffff8123aa96>] ? security_file_permission+0x16/0x20
 [<ffffffff8119a906>] ? do_readv_writev+0xd6/0x1f0
 [<ffffffff8119aa66>] ? vfs_writev+0x46/0x60
 [<ffffffff8119ab91>] ? sys_writev+0x51/0xd0
 [<ffffffff810ee28e>] ? __audit_syscall_exit+0x25e/0x290
 [<ffffffff8100b0d2>] ? system_call_fastpath+0x16/0x1b
Code: 00 00 00 01 74 05 e8 42 c3 d5 ff c9 c3 55 48 89 e5 0f 1f 44 00 00 b8 00 00 01 00 f0 0f c1 07 0f b7 d0 c1 e8 10 39 c2 74 0e f3 90 <0f> b7 17 eb f5 83 3f 00 75 f4 eb df c9 c3 0f 1f 40 00 55 48 89 

The hosts process about 25reqs/sec. 

Any thoughts on what could be wrong? Appreciate any help in this direction. 

Regards

**Comment by Nikratio** [comment]
Thanks for the report!


As far as I can tell, this is a problem with *FUSE*, the Linux kernel module. This GitHub project is primarily for *libfuse*, the userspace library. I'm happy to keep track of kernel issues in this  issue tracker as well, but please note that it's quite unlikely that reporting kernel issues here will be sufficient to get them fixed. 

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, e.g. [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) or [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel).

**Comment by Rondom** [comment]
In this specific case you might also file a ticket with Red Hat considering that their 2.6.32 kernel is quite heavily patched and others might just as well tell you to reproduce with a recent kernel.
