### ISSUE TITLE
Init script is installed in /usr/local/etc, not /etc

### ISSUE THREAD

**Issue by TomBugnon** [libfuse/libfuse#178]
Hi all,
I'm trying to install fuse and have followed the steps advised:
`meson`
`ninja`
`sudo python3 -m pytest test/` (all passed)
 but I receive an error during the ninja install:

`sudo ~/divers_apps/ninja/ninja install`
returns:

> [0/1] Installing files.
> Installing lib/libfuse3.so.3.0.0 to /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.0.0
> Installing util/fusermount3 to /usr/local/bin/fusermount3
> Installing util/mount.fuse3 to /usr/local/sbin/mount.fuse3
> Installing fuse.h to /usr/local/include/fuse3
> Installing fuse_common.h to /usr/local/include/fuse3
> Installing fuse_lowlevel.h to /usr/local/include/fuse3
> Installing fuse_opt.h to /usr/local/include/fuse3
> Installing cuse_lowlevel.h to /usr/local/include/fuse3
> Installing /home/tom/divers_apps/fuse/fuse-3.0.2/doc/fusermount3.1 to /usr/local/share/man/man1
> Installing /home/tom/divers_apps/fuse/fuse-3.0.2/doc/mount.fuse.8 to /usr/local/share/man/man8
> Installing /home/tom/divers_apps/fuse/build/meson-private/fuse3.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
> Running custom install script '/home/tom/divers_apps/fuse/fuse-3.0.2/util/install_helper.sh etc bin lib/x86_64-linux-gnu'
> update-rc.d: error: unable to read /etc/init.d/fuse3
> 

Would you by chance have any idea?
Thanks!

**Comment by Nikratio** [comment]
That's odd. The install script first installs the init script, and then runs update-rc.d. However, in your case update-rc.d claims that the script hasn't been installed.

Could you post the output of `ls -l /etc/init/fuse3`?

**Comment by Nikratio** [comment]
Hmm. Maybe the script got installed in `/usr/local`.. could you please also run `ls -l /usr/local/etc/init.d/fuse3`

**Comment by TomBugnon** [comment]
Thanks for the quick response.
Indeed it looks like this is the issue, `/etc/init.d/fuse3` doesn't exist.
`ls -l /usr/local/etc/init.d/fuse3` returns 

> -rwxr-xr-x 1 root root 1894 juin  21 14:54 /usr/local/etc/init.d/fuse3

**Comment by Nikratio** [comment]
Oh, ok. Move the file to `/etc/init.d` and call `update-rc.d fuse3 start 34 S . start 41 0 6 .` and you should be good.

I'll try to fix this in the next release.

**Comment by Nikratio** [comment]
1894 is the file size, not the year.

**Comment by TomBugnon** [comment]
I'm afraid it still doesn't work but I'm not sure whether the issue is related... 

`sudo ~/divers_apps/ninja/ninja install` now returns
> [0/1] Installing files.
> Installing lib/libfuse3.so.3.0.0 to /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.0.0
> Installing util/fusermount3 to /usr/local/bin/fusermount3
> Installing util/mount.fuse3 to /usr/local/sbin/mount.fuse3
> Installing fuse.h to /usr/local/include/fuse3
> Installing fuse_common.h to /usr/local/include/fuse3
> Installing fuse_lowlevel.h to /usr/local/include/fuse3
> Installing fuse_opt.h to /usr/local/include/fuse3
> Installing cuse_lowlevel.h to /usr/local/include/fuse3
> Installing /home/tom/divers_apps/fuse/fuse-3.0.2/doc/fusermount3.1 to /usr/local/share/man/man1
> Installing /home/tom/divers_apps/fuse/fuse-3.0.2/doc/mount.fuse.8 to /usr/local/share/man/man8
> Installing /home/tom/divers_apps/fuse/build/meson-private/fuse3.pc to /usr/local/lib/x86_64-linux-gnu/pkgconfig
> Running custom install script '/home/tom/divers_apps/fuse/fuse-3.0.2/util/install_helper.sh etc bin lib/x86_64-linux-gnu'
> update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
> update-rc.d: warning: stop runlevel arguments (0 6) do not match fuse3 Default-Stop values (none)
>

**Comment by Nikratio** [comment]
Huh? Why do you think it didn't work? The warnings are just that, warnings. Not errors :-).

**Comment by TomBugnon** [comment]
Indeed it works beautifully. Thanks for ending a day of afp struggle.
Tom

**Comment by Daqu** [comment]
I got the same problem, thanks to your discussion!

**Comment by barani008** [comment]
Hi, I got the same problem. And I am getting an error like this, when I try to run the command you provided. Can you please help?

ubuntu@biofs:~/libfuse/build$ sudo mv /usr/local/etc/init.d/fuse3 /etc/init.d/
ubuntu@biofs:~/libfuse/build$ sudo update-rc.d fuse3 start 34 S . start 41 0 6 .
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: stop runlevel arguments (0 6) do not match fuse3 Default-Stop values (none)
insserv: script fuse3: service fuse already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header

**Comment by m3rcury6** [comment]
just got the same issue. following instructions above

**Comment by gautamworah96** [comment]
Moving the file and running the update-rc.d command works beautifully! Thanks.

**Comment by Rayoluo** [comment]
Thanks!!

**Comment by iamorphen** [comment]
FYI the original issue still occurs with libfuse 3.6.0 on at least Ubuntu 16 for me.

**Comment by Nikratio** [comment]
Could you please open a new issue (preferably together with a pull request)? This thread is rather unwieldy, it's no longer clear what "the issue" is.

**Comment by iamorphen** [comment]
Unfortunately I have no corresponding PR, but I've opened #427 to track the issue referred to by the title of this issue.
