### ISSUE TITLE
Tests fail when /tmp is on BTRFS

### ISSUE THREAD

**Issue by hWorblehat** [libfuse/libfuse#180]
When using BTRFS as the base filesystem for /tmp, tests that run `test_mkdir` in test_syscalls.c fail. This is because BTRFS doesn't track the link count of directories (see [here](https://btrfs.wiki.kernel.org/index.php/Project_ideas#Track_link_count_for_directories)), so the `check_nlink(testdir, 2)` check fails, as `nlink` is reported as 1.

Since this problem shouldn't occur very often, I'd suggest a simple build configuration option that unsets a preprocessor symbol `TMP_DIR_FS_TRACKS_DIR_NLINK`, and then you could switch on that in the test code. I haven't proposed a PR as I'm not familiar with the meson/ninja system, so I don't know how to implement it.

**Comment by jpandre** [comment]
IMHO the check should be bypassed based on a command-line argument, not according to a compile time decision. File system developers who have to apply the same test on several implementations do not want specialized test executables. I also suggest to keep the test and, according to option, issue a non-fatal warning if it fails.
