### ISSUE TITLE
passthrough_ll no longer builds on some architectures

### ISSUE THREAD

**Issue by spotrh** [libfuse/libfuse#185]
As a result of https://github.com/libfuse/libfuse/commit/8641db4af724682fb1c922cbecf6c7e1dfe1a71c , some architectures (e.g. i686, armv7hl) no longer build properly. They fail with:

```
passthrough_ll.c:55:1: error: static assertion failed: "fuse: off_t must be 64bit"
_Static_assert(sizeof(fuse_ino_t) == sizeof(uintptr_t), "fuse: off_t must be 64bit");
```

The assert itself is not to blame, indeed, off_t is not 64bit on those platforms, however, this check means the fuse build no longer succeeds on 32bit platforms. Either the assert needs to be conditionalized to only apply on 64bit architectures, removed, or passthrough_ll.c should be conditionalized so that it is not built on 32bit platforms.

**Comment by Nikratio** [comment]
Actually, *off_t* should be 64 bit on most 32 bit systems as well. Maybe the actual problem is a missing definition of something like `-DFILE_OFFSET_BITS=64` - I need to look that up.

**Comment by spotrh** [comment]
I think -D_FILE_OFFSET_BITS=64 is the right answer for fuse in general, but it doesn't make this check pass (probably because it is not changing the size of uintptr_t, only off_t).

**Comment by Nikratio** [comment]
Alright, the above commit should fix the problem for regular 32 bit systems. It turns out that the error message was wrong.

Please let me know if there is still a problem on armv7hl.
