### ISSUE TITLE
assemble message

### ISSUE THREAD

**Issue by lalith12** [libfuse/libfuse#186]
CC       fuse.lo
/tmp/ccchNgWM.s: Assembler messages:

/tmp/ccchNgWM.s:6: Error: unknown pseudo-op: `.symver'

/tmp/ccchNgWM.s:7: Error: unknown pseudo-op: `.symver'

copiled in cygwin

**Comment by Nikratio** [comment]
Thanks for the report!

I assume Cigwin means the host operating system is Windows? In that case there is no point in running libfuse, since Windows doesn't have FUSE support in the kernel.

Please re-open if I got something wrong.

**Comment by trapexit** [comment]
Those wanting a libfuse API in Windows should be using WinFSP: https://github.com/billziss-gh/winfsp

**Comment by Nikratio** [comment]
Thanks @trapexit!
