### ISSUE TITLE
Error specifying subtype: "/bin/sh: <subtype>: command not found"

### ISSUE THREAD

**Issue by Balletie** [libfuse/libfuse#19]
When specifying the subtype to the mount command with e.g. `mount -t fuse.bindfs`, I get the following error:

```
/bin/sh: bindfs: command not found
```

It occurs on this line in `mount.fuse`: https://github.com/libfuse/libfuse/blob/e6e7a249c5c70187144dd9cd3767801ed05a1763/util/mount.fuse.c#L228

If I turn the subtype to a full path of an executable, it works, e.g. `mount -t fuse./path/to/bindfs`.  But obviously only if the path itself does not contain any dots.

I have two questions:

1. Why is it running `/bin/sh/` instead of running the executable directly?
2. Why not use `execvp`, which searches in the PATH variable for the executable. This way it would find `bindfs` in my case.

__Disclaimer__: I am using NixOS, which does weird things with executable paths. This is probably why the bug has not occurred in other operating systems

**Comment by Nikratio** [comment]
I think you assume more logic than there is. If you call `mount -t <foo>`, it looks for a mount helper called `mount.<foo>`. So if `<foo>` is `fuse.bindfs`, it looks for `mount.fuse.bindfs`.  These semantics have nothing to do with fuse.

**Comment by Balletie** [comment]
But if that's the case, why does it end up throwing this error inside the `mount.fuse` executable?

**Comment by Nikratio** [comment]
No idea. But if it's not documented, then you shouldn't rely on it.

**Comment by Balletie** [comment]
Alright thanks. I inspected the code of mount, and I saw that if it does not find `mount.fuse.bindfs`, it looks for the type without the subtype instead (`mount.fuse`). So this is why it ends up inside `mount.fuse`.

Would you consider searching the PATH for a `bindfs` a good option/solution? Or do you think that fuse will end up doing too much?

I also saw that there is a problem in the `bindfs` packaging in NixOS: it does not create a `mount.fuse.bindfs` executable or symlink like you said. I'm going to see if I can fix it on their side.

Thanks again :)

**Comment by Nikratio** [comment]
On Feb 18 2016, Skip <notifications@github.com> wrote:
> Alright thanks. I inspected the code of mount, and I saw that if it
> does not find `mount.fuse.bindfs`, it looks for the type without the
> subtype instead (`mount.fuse`). So this is why it ends up inside
> `mount.fuse`.
>
> Would you consider searching the PATH for a `bindfs` a good option/solution? Or do you think that fuse will end up doing too much?

Not in principle. But I'd need to see an actual patch to be sure.

Best,
-Nikolaus

-- 
GPG encrypted emails preferred. Key id: 0xD113FCAC3C4E599F
Fingerprint: ED31 791B 2C5C 1613 AF38 8B8A D113 FCAC 3C4E 599F

             »Time flies like an arrow, fruit flies like a Banana.«
