### ISSUE TITLE
Fuse mount directory is getting corrupted on starting daemon.

### ISSUE THREAD

**Issue by BharathB23** [libfuse/libfuse#196]
When we start FUSE daemon, the mount directory is getting corrupted.

ls -l /
ls: cannot access /kms: Permission denied
d??????????   ? ?        ?            ?            ? kms

/kms fuse mount point created was working normally and changed it's state like above suddenly.
on restarting the daemon and even after unmounting or rebooting the node, it returns back to the same state.

Please let me know, what could cause this.

**Comment by Nikratio** [comment]
Thanks for the report!

However, libfuse doesn't actually come with a daemon. Are you talking about one of the example filesystems? If so, please specify which one, which version, and how you are calling it. Please also try running in foreground (`-f` option) and see if that changes something.

**Comment by BharathB23** [comment]
Thanks for the response Nikratio.

Daemon is our own which has the fuse filesystem implementations, mainly the fuse operations .getattr, .readdir, .open and .read.

/kms is the mount point we are using to store our data.

We have defined daemon as a systemd service. When the service is started filesystem is unmounted and also during startup to be safer, again is unmounted.

**Comment by Nikratio** [comment]
Well, unless you can reproduce the problem with one of the example filesystems that come with libfuse, this is most likely a bug in your filesystem rather than libfuse. So there's little we can do here.
