### ISSUE TITLE
Configurable thread pool for high level API

### ISSUE THREAD

**Issue by trapexit** [libfuse/libfuse#2]
Currently the thread pool for the high level API will grow as needed but threads will self destruct if after their handling of a request there is greater than [10 threads](https://github.com/libfuse/libfuse/blob/master/lib/fuse_loop_mt.c#L120). The overhead of doing so is probably much greater than the request handled and limits throughput.

The max number of threads should be configurable and maybe a smarter algo used which perhaps cleans up threads if unused for a time rather than checking every request.

**Comment by jirutka** [comment]
I see that you’ve already implemented it for mergerfs: https://github.com/trapexit/mergerfs/commit/75ed37a11a5977cb64a901d153831e51ce459191. Why you haven’t sent it to upstream (don’t see any PR)?

I’m working on Alpine package for mergerfs and wants to avoid building it with bundled libfuse, so I was thinking about applying this patch to our libfuse package. Is it safe or it may break some other programs using libfuse?

**Comment by trapexit** [comment]
I did not perform the change in a backwards compatible way, I changed other behaviors with regard to threading, and v2.9.7 is no longer actively developed. 

I very purposefully included libfuse because I wanted to control the version. Many of my users are on platforms which have very old versions of libfuse. Going back to libfuse 2.8.x. It significantly increased the support cost for myself and users.

I understand the concern but given the complexity (and importance of stability) of libfuse I'd not want it versioned outside my project. I in fact started prototyping replacing it completely but embedding it was a easier solution.

Does the bigger binary size and slight memory increase really matter that much?

**Comment by jirutka** [comment]
Alpine Linux is not Debian, our repository is not a museum. ;) We currently package libfuse 2.9.7 (it’ll be in the upcoming stable release).

It’s not just about binary size, but also security, maintenance etc. If some security or other bug is revealed in libfuse, we need to patch it at single place, libfuse package, not dozens of packages for software whose developers decided to bundle dependencies. Most Linux distributions forbids bundled dependencies and allows it only in specific cases.

**Comment by trapexit** [comment]
Yes, I'm aware of the standard arguments and complaints but these aren't statistically likely events. Besides how is this all that different then if there was a security issue within mergerfs and I failed to address it? If I forked libfuse would that be better? Not for me or my users. Not for maintainers. If I replaced libfuse completely and had my own library (embedded or not) would that be materially different? No. Is there even greater risk of security issues if I did? Probably. 

Sorry but unless someone can provide me with a solution that provides the stability, control, and simplicity of support I get from embedding libfuse I don't see anything changing. Alpine might not be Debian but I suspect there's a massive difference in the number of Debian mergerfs users and Alpine mergerfs users in favor of the former. If there's demand I'll create my own packages for Alpine just as I do for Debian... [but even Debian seems to have accepted what I've done.](https://packages.debian.org/search?keywords=mergerfs)

**Comment by jirutka** [comment]
> how is this all that different then if there was a security issue within mergerfs and I failed to address it?

It’s not.

> If I forked libfuse would that be better?

You’ve already did it. You maintain your own fork inside mergerfs repository, instead of contributing the needed change to upstream.

> If I replaced libfuse completely and had my own library (embedded or not) would that be materially different?

That’d be a different situation.

> If there's demand I'll create my own packages for Alpine just as I do for Debian.

That’s not needed, someone has already created package for mergerfs and contributed it to Alpine’s aports repository. I just wanted to get rid of the bundled library before moving it into stable branch, that’s why I asked about it.

There are many cons and pros around bundling libraries and I’m not interested to discuss it here. Just imagine how it would look if every developer use this approach and there were dozens variants of libfuse with various modifications…

**Comment by trapexit** [comment]
> Just imagine how it would look if every developer use this approach and there were dozens variants of libfuse with various modifications…

If those modifications which can't be upstreamed or have other valid reasons to be separate then I have no problem with it. Some libraries are specifically designed to always be embedded / statically linked. I've long been a supporter of static linkage, vendored apps, and containers for complicated software as a means to ease deployment and reduce complexity and risk of bugs being introduced outside your control. Not every system is NixOS. For something as critical as a filesystem, the handling of people's data, I will err on the side of stability as often as possible.

I can look at reworking the changes to be backwards compatible at some point and try to upstream them but that's a low priority relative to other improvements and the testing of libfuse3. I'd still embed libfuse though because many of my users are on older platforms.

**Comment by Nikratio** [comment]
I believe this has been addressed in the work around commit 8de32bc.
