### ISSUE TITLE
which fuse version support in linux kernel  3.10.0

### ISSUE THREAD

**Issue by candyzone** [libfuse/libfuse#201]
Before update kernel, i use fuse-2.7.3 in linux kernel 2.6.32, it works,
Now, kernel is 3.10.0, fuse doesn't work, is the fuse version need to update?

**Comment by Nikratio** [comment]
No, old fuse versions should work with new kernels and vice versa.

As far as I can tell, this is also a question about how to use fuse rather than a bug report. Please
use the fuse mailing list for this purpose. To subscribe, please visit https://lists.sourceforge.net/lists/listinfo/fuse-devel.
