### ISSUE TITLE
'fuse3' not found even when installed (OSX)

### ISSUE THREAD

**Issue by Tommsy64** [libfuse/libfuse#204]
I am following the installation instructions in `README.md`. 
MacOS version `10.12.6`

Both `meson ..` and autotools `./configure` report that `fuse3` is not found.
I have tried installing OSX Fuse v3.6.3 from https://osxfuse.github.io/ and with Homebrew, with and without the MacFUSE compatibility layer, and with/without restarting after each installation.

From autotools:
```
configure: error: Package requirements (fuse3 >= 3.1 glib-2.0 gthread-2.0) were not met:
No package 'fuse3' found
```
From Meson:
```
The Meson build system
Version: 0.42.0
Source dir: ~/Downloads/sshfs-3.2.0
Build dir: ~/Downloads/sshfs-3.2.0/build
Build type: native build
Project name: sshfs
Native C compiler: cc (clang 8.1.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring sshfs.1 using configuration
WARNING: The variable(s) 'UNMOUNT_COMMAND' in the input file 'sshfs.1.in' are not present in the given configuration data
Configuring config.h using configuration
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Dependency fuse3 found: NO

Meson encountered an error in file meson.build, line 48, column 0:
Dependency 'fuse3' not found, tried Extra Frameworks and Pkg-Config:

Native dependency 'fuse3' not found
```

**Comment by Nikratio** [comment]
There is no FUSE 3 for OS X yet. Until that is available, you need to stick with SSHFS 2.x.

**Comment by Night46** [comment]
It seams that there is a FUSE3 for mac (https://osxfuse.github.io/)
though even after installing "osxfuse-3.6.3" it still produces the same error:
"Native dependency 'fuse3' not found"

Seems that this version of FUSE3 not satisfying meson requirements, any thoughts on why?

**Comment by Nikratio** [comment]
This is an unfortunate naming issue. OSXFUSE issues its own versioning scheme. As far as I know, OSXFUSE 3.6.3 still only implements the libfuse 2.9.x API.

**Comment by Night46** [comment]
True, unfortunate naming issue.
just checked the local lib dir and it only has libfuse v2
