### ISSUE TITLE
fuse_lowlevel_ops::open : must set fi->direct_io = 1 if fill fi->fh

### ISSUE THREAD

**Issue by h1467792822** [libfuse/libfuse#209]
in fuse_lowlevel_ops::open, I must fill fi->fh with my special data. I can normally read the file less than 12 times, after that , libfuse don't send read request after open returned ( I got this information with debug mode) .

to fix this issue, I must set fi->direct_io = 1  in fuse_lowlevel_ops::open.

**Comment by Nikratio** [comment]
Thanks for the report! Can you reproduce this with one of the example filesystems?

**Comment by h1467792822** [comment]
/*
  FUSE: Filesystem in Userspace
  Copyright (C) 2001-2007  Miklos Szeredi <miklos@szeredi.hu>

  This program can be distributed under the terms of the GNU GPL.
  See the file COPYING.

  gcc -Wall hello_ll.c `pkg-config fuse --cflags --libs` -o hello_ll
*/

#define FUSE_USE_VERSION 26

#include <fuse_lowlevel.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>

static const char *hello_str = "Hello World!\n";
static const char *hello_name = "hello";

static int hello_stat(fuse_ino_t ino, struct stat *stbuf)
{
	stbuf->st_ino = ino;
	switch (ino) {
	case 1:
		stbuf->st_mode = S_IFDIR | 0755;
		stbuf->st_nlink = 2;
		break;

	case 2:
		stbuf->st_mode = S_IFREG | 0444;
		stbuf->st_nlink = 1;
		stbuf->st_size = strlen(hello_str);
		break;

	default:
		return -1;
	}
	return 0;
}

static void hello_ll_getattr(fuse_req_t req, fuse_ino_t ino,
			     struct fuse_file_info *fi)
{
	struct stat stbuf;

	(void) fi;

	memset(&stbuf, 0, sizeof(stbuf));
	if (hello_stat(ino, &stbuf) == -1)
		fuse_reply_err(req, ENOENT);
	else {
		if(fi && fi->fh) {
			stbuf.st_size = strlen((char*)fi->fh);
		}
		fuse_reply_attr(req, &stbuf, 1.0);
	}
}

static void hello_ll_lookup(fuse_req_t req, fuse_ino_t parent, const char *name)
{
	struct fuse_entry_param e;

	if (parent != 1 || strcmp(name, hello_name) != 0)
		fuse_reply_err(req, ENOENT);
	else {
		memset(&e, 0, sizeof(e));
		e.ino = 2;
		e.attr_timeout = 1.0;
		e.entry_timeout = 1.0;
		hello_stat(e.ino, &e.attr);

		fuse_reply_entry(req, &e);
	}
}

struct dirbuf {
	char *p;
	size_t size;
};

static void dirbuf_add(fuse_req_t req, struct dirbuf *b, const char *name,
		       fuse_ino_t ino)
{
	struct stat stbuf;
	size_t oldsize = b->size;
	b->size += fuse_add_direntry(req, NULL, 0, name, NULL, 0);
	b->p = (char *) realloc(b->p, b->size);
	memset(&stbuf, 0, sizeof(stbuf));
	stbuf.st_ino = ino;
	fuse_add_direntry(req, b->p + oldsize, b->size - oldsize, name, &stbuf,
			  b->size);
}

#define min(x, y) ((x) < (y) ? (x) : (y))

static int reply_buf_limited(fuse_req_t req, const char *buf, size_t bufsize,
			     off_t off, size_t maxsize)
{
	if (off < bufsize)
		return fuse_reply_buf(req, buf + off,
				      min(bufsize - off, maxsize));
	else
		return fuse_reply_buf(req, NULL, 0);
}

static void hello_ll_readdir(fuse_req_t req, fuse_ino_t ino, size_t size,
			     off_t off, struct fuse_file_info *fi)
{
	(void) fi;

	if (ino != 1)
		fuse_reply_err(req, ENOTDIR);
	else {
		struct dirbuf b;

		memset(&b, 0, sizeof(b));
		dirbuf_add(req, &b, ".", 1);
		dirbuf_add(req, &b, "..", 1);
		dirbuf_add(req, &b, hello_name, 2);
		reply_buf_limited(req, b.p, b.size, off, size);
		free(b.p);
	}
}

static void hello_ll_open(fuse_req_t req, fuse_ino_t ino,
			  struct fuse_file_info *fi)
{
	static int times;
	if (ino != 2)
		fuse_reply_err(req, EISDIR);
	else if ((fi->flags & 3) != O_RDONLY)
		fuse_reply_err(req, EACCES);
	else {
		char* buf = malloc(1024);
		snprintf(buf,1024,"hello,world[oldfh: %p],%d\n",(void*)fi->fh_old, times++);
		fi->fh = (unsigned long) buf;
		// if not set direct_io = 1 , kernel don't send read request after open returned at the 13th times.
		fi->direct_io = 1;
		fuse_reply_open(req, fi);
		printf("open: %p", buf);
	}
}

static void hello_ll_read(fuse_req_t req, fuse_ino_t ino, size_t size,
			  off_t off, struct fuse_file_info *fi)
{
	(void) fi;

	assert(ino == 2);
	char* buf = (char*)fi->fh;
	reply_buf_limited(req, buf, strlen(buf), off, size);
	printf("read: %p", buf);
}

static void hello_ll_release(fuse_req_t req, fuse_ino_t ino,
			  struct fuse_file_info *fi)
{
	printf("release: %p", (void*)fi->fh);
	free((char*)fi->fh);
	fi->fh = 0;

	// if not call fuse_reply_err, kernel don't send release request after read/flush returned at the 13th times.
	fuse_reply_err(req,0); 
}

static struct fuse_lowlevel_ops hello_ll_oper = {
	.lookup		= hello_ll_lookup,
	.getattr	= hello_ll_getattr,
	.readdir	= hello_ll_readdir,
	.open		= hello_ll_open,
	.read		= hello_ll_read,
	.release	= hello_ll_release,
};

int main(int argc, char *argv[])
{
	struct fuse_args args = FUSE_ARGS_INIT(argc, argv);
	struct fuse_chan *ch;
	char *mountpoint;
	int err = -1;

	if (fuse_parse_cmdline(&args, &mountpoint, NULL, NULL) != -1 &&
	    (ch = fuse_mount(mountpoint, &args)) != NULL) {
		struct fuse_session *se;

		se = fuse_lowlevel_new(&args, &hello_ll_oper,
				       sizeof(hello_ll_oper), NULL);
		if (se != NULL) {
			if (fuse_set_signal_handlers(se) != -1) {
				fuse_session_add_chan(se, ch);
				err = fuse_session_loop(se);
				fuse_remove_signal_handlers(se);
				fuse_session_remove_chan(ch);
			}
			fuse_session_destroy(se);
		}
		fuse_unmount(mountpoint, ch);
	}
	fuse_opt_free_args(&args);

	return err ? 1 : 0;
}

**Comment by h1467792822** [comment]
I modified hello_ll.c to reproduce this issue:

#define FUSE_USE_VERSION 26

#include <fuse_lowlevel.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>

static const char *hello_str = "Hello World!\n";
static const char *hello_name = "hello";

static int hello_stat(fuse_ino_t ino, struct stat *stbuf)
{
	stbuf->st_ino = ino;
	switch (ino) {
	case 1:
		stbuf->st_mode = S_IFDIR | 0755;
		stbuf->st_nlink = 2;
		break;

	case 2:
		stbuf->st_mode = S_IFREG | 0444;
		stbuf->st_nlink = 1;
		stbuf->st_size = strlen(hello_str);
		break;

	default:
		return -1;
	}
	return 0;
}

static void hello_ll_getattr(fuse_req_t req, fuse_ino_t ino,
			     struct fuse_file_info *fi)
{
	struct stat stbuf;

	(void) fi;

	memset(&stbuf, 0, sizeof(stbuf));
	if (hello_stat(ino, &stbuf) == -1)
		fuse_reply_err(req, ENOENT);
	else {
		if(fi && fi->fh) {
			stbuf.st_size = strlen((char*)fi->fh);
		}
		fuse_reply_attr(req, &stbuf, 1.0);
	}
}

static void hello_ll_lookup(fuse_req_t req, fuse_ino_t parent, const char *name)
{
	struct fuse_entry_param e;

	if (parent != 1 || strcmp(name, hello_name) != 0)
		fuse_reply_err(req, ENOENT);
	else {
		memset(&e, 0, sizeof(e));
		e.ino = 2;
		e.attr_timeout = 1.0;
		e.entry_timeout = 1.0;
		hello_stat(e.ino, &e.attr);

		fuse_reply_entry(req, &e);
	}
}

struct dirbuf {
	char *p;
	size_t size;
};

static void dirbuf_add(fuse_req_t req, struct dirbuf *b, const char *name,
		       fuse_ino_t ino)
{
	struct stat stbuf;
	size_t oldsize = b->size;
	b->size += fuse_add_direntry(req, NULL, 0, name, NULL, 0);
	b->p = (char *) realloc(b->p, b->size);
	memset(&stbuf, 0, sizeof(stbuf));
	stbuf.st_ino = ino;
	fuse_add_direntry(req, b->p + oldsize, b->size - oldsize, name, &stbuf,
			  b->size);
}

#define min(x, y) ((x) < (y) ? (x) : (y))

static int reply_buf_limited(fuse_req_t req, const char *buf, size_t bufsize,
			     off_t off, size_t maxsize)
{
	if (off < bufsize)
		return fuse_reply_buf(req, buf + off,
				      min(bufsize - off, maxsize));
	else
		return fuse_reply_buf(req, NULL, 0);
}

static void hello_ll_readdir(fuse_req_t req, fuse_ino_t ino, size_t size,
			     off_t off, struct fuse_file_info *fi)
{
	(void) fi;

	if (ino != 1)
		fuse_reply_err(req, ENOTDIR);
	else {
		struct dirbuf b;

		memset(&b, 0, sizeof(b));
		dirbuf_add(req, &b, ".", 1);
		dirbuf_add(req, &b, "..", 1);
		dirbuf_add(req, &b, hello_name, 2);
		reply_buf_limited(req, b.p, b.size, off, size);
		free(b.p);
	}
}

static void hello_ll_open(fuse_req_t req, fuse_ino_t ino,
			  struct fuse_file_info *fi)
{
	static int times;
	if (ino != 2)
		fuse_reply_err(req, EISDIR);
	else if ((fi->flags & 3) != O_RDONLY)
		fuse_reply_err(req, EACCES);
	else {
		char* buf = malloc(1024);
		snprintf(buf,1024,"hello,world[oldfh: %p],%d\n",(void*)fi->fh_old, times++);
		fi->fh = (unsigned long) buf;
		// if not set direct_io = 1 , kernel don't send read request after open returned at the 13th times.
		fi->direct_io = 1;
		fuse_reply_open(req, fi);
		printf("open: %p", buf);
	}
}

static void hello_ll_read(fuse_req_t req, fuse_ino_t ino, size_t size,
			  off_t off, struct fuse_file_info *fi)
{
	(void) fi;

	assert(ino == 2);
	char* buf = (char*)fi->fh;
	reply_buf_limited(req, buf, strlen(buf), off, size);
	printf("read: %p", buf);
}

static void hello_ll_release(fuse_req_t req, fuse_ino_t ino,
			  struct fuse_file_info *fi)
{
	printf("release: %p", (void*)fi->fh);
	free((char*)fi->fh);
	fi->fh = 0;

	// if not call fuse_reply_err, kernel don't send release request after read/flush returned at the 13th times.
	fuse_reply_err(req,0); 
}

static struct fuse_lowlevel_ops hello_ll_oper = {
	.lookup		= hello_ll_lookup,
	.getattr	= hello_ll_getattr,
	.readdir	= hello_ll_readdir,
	.open		= hello_ll_open,
	.read		= hello_ll_read,
	.release	= hello_ll_release,
};

int main(int argc, char *argv[])
{
	struct fuse_args args = FUSE_ARGS_INIT(argc, argv);
	struct fuse_chan *ch;
	char *mountpoint;
	int err = -1;

	if (fuse_parse_cmdline(&args, &mountpoint, NULL, NULL) != -1 &&
	    (ch = fuse_mount(mountpoint, &args)) != NULL) {
		struct fuse_session *se;

		se = fuse_lowlevel_new(&args, &hello_ll_oper,
				       sizeof(hello_ll_oper), NULL);
		if (se != NULL) {
			if (fuse_set_signal_handlers(se) != -1) {
				fuse_session_add_chan(se, ch);
				err = fuse_session_loop(se);
				fuse_remove_signal_handlers(se);
				fuse_session_remove_chan(ch);
			}
			fuse_session_destroy(se);
		}
		fuse_unmount(mountpoint, ch);
	}
	fuse_opt_free_args(&args);

	return err ? 1 : 0;
}

**Comment by h1467792822** [comment]
2 issues:

**Comment by h1467792822** [comment]
hello_ll_open:
// if not set direct_io = 1 , kernel don't send read request after open returned at the 13th times.
fi->direct_io = 1;

hello_ll_release( I added): 
// if not call fuse_reply_err, kernel don't send release request after read/flush returned at the 13th times.
fuse_reply_err(req,0);

**Comment by Nikratio** [comment]
Can you please attach the patch or the modified file? Thanks

(Your previous message that contained the entire file verbatim which made it unreadable, so I deleted it)

**Comment by h1467792822** [comment]
--- hello_ll.c	2013-07-01 15:40:39.000000000 +0800
+++ hello_ll.c.new	2017-09-28 09:13:03.019000000 +0800
@@ -53,8 +53,12 @@
 	memset(&stbuf, 0, sizeof(stbuf));
 	if (hello_stat(ino, &stbuf) == -1)
 		fuse_reply_err(req, ENOENT);
-	else
+	else {
+		if(fi && fi->fh) {
+			stbuf.st_size = strlen((char*)fi->fh);
+		}
 		fuse_reply_attr(req, &stbuf, 1.0);
+	}
 }
 
 static void hello_ll_lookup(fuse_req_t req, fuse_ino_t parent, const char *name)
@@ -126,12 +130,20 @@
 static void hello_ll_open(fuse_req_t req, fuse_ino_t ino,
 			  struct fuse_file_info *fi)
 {
+	static int times;
 	if (ino != 2)
 		fuse_reply_err(req, EISDIR);
 	else if ((fi->flags & 3) != O_RDONLY)
 		fuse_reply_err(req, EACCES);
-	else
+	else {
+		char* buf = malloc(1024);
+		snprintf(buf,1024,"hello,world[oldfh: %p],%d\n",(void*)fi->fh_old, times++);
+		fi->fh = (unsigned long) buf;
+		// if not set direct_io = 1 , kernel don't send read request after open returned at the 13th times.
+		fi->direct_io = 1;
 		fuse_reply_open(req, fi);
+		printf("open: %p", buf);
+	}
 }
 
 static void hello_ll_read(fuse_req_t req, fuse_ino_t ino, size_t size,
@@ -140,7 +152,20 @@
 	(void) fi;
 
 	assert(ino == 2);
-	reply_buf_limited(req, hello_str, strlen(hello_str), off, size);
+	char* buf = (char*)fi->fh;
+	reply_buf_limited(req, buf, strlen(buf), off, size);
+	printf("read: %p", buf);
+}
+
+static void hello_ll_release(fuse_req_t req, fuse_ino_t ino,
+			  struct fuse_file_info *fi)
+{
+	printf("release: %p", (void*)fi->fh);
+	free((char*)fi->fh);
+	fi->fh = 0;
+
+	// if not call fuse_reply_err, kernel don't send release request after read/flush returned at the 13th times.
+	fuse_reply_err(req,0); 
 }
 
 static struct fuse_lowlevel_ops hello_ll_oper = {
@@ -149,6 +174,7 @@
 	.readdir	= hello_ll_readdir,
 	.open		= hello_ll_open,
 	.read		= hello_ll_read,
+	.release	= hello_ll_release,
 };
 
 int main(int argc, char *argv[])

**Comment by Nikratio** [comment]
Please take a look at the mess you just posted.

**Comment by h1467792822** [comment]
it is not an issue of libfuse
