### ISSUE TITLE
Tags don't match download tar

### ISSUE THREAD

**Issue by pwaller** [libfuse/libfuse#21]
Hi! Welcome to github. Nice to find you here.

I've just hit upon a minor annoyance, and it might be good to correct it sooner rather than later. I'm scripting something which builds fuse, and it looks something like (pseudocode):

```
FUSE_VERSION=2.9.5
FUSE_HASH=ab1231231232113213123
curl https://github.com/libfuse/libfuse/releases/download/fuse-$VERSION/fuse-$VERSION.tar.gz
verify-hash fuse-$VERSION $FUSE_HASH
tar zxf fuse-$VERSION.tar.gz
cd fuse-$VERSION
```

The only annoyance with this is that the download URL follows the git tag. Since the git tags have underscores, the link is:

```
https://github.com/libfuse/libfuse/releases/download/fuse_2_9_5/fuse-2.9.5.tar.gz
```

So it's not possible to just update one `$FUSE_VERSION`, you also have to update the URL separately, to represent the `fuse_2_9_5` part. It would be nice to just have the one variable to update. Is it possible to use `fuse-2.9.5` tags instead? It would make life easier.

Thanks for your consideration, and I won't be disappointed if you decline.

**Comment by Nikratio** [comment]
Sounds reasonable, will do in the future.

**Comment by pwaller** [comment]
Thanks!
