### ISSUE TITLE
Installing failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by tksuoran** [libfuse/libfuse#212]
On stock Ubuntu 16.04, installing building/installing with meson does not produce working sshfs for example. Building and installing proceeds fine (after manually installing latest meson). However, sshfs --version says:

shfs: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory

This happens because installation has placed libfuse to /usr/local/lib/x86_64-linux-gnu/ and that path is not searched for libraries in stock Ubuntu 16.04 system.

When I built libfuse/sshfs with autotools, this issue did not happen. But autotools support has been dropped so this is no longer an option. I am not 100% sure if this issue is in libfuse or meson or ninja or Ubuntu. But I sure would like to get it fixed.

**Comment by Starkmann** [comment]
Same here

**Comment by Rondom** [comment]
I am not that familiar with Meson yet and have not looked into this very closely, but I think I recall that at least cmake detects automatically that libdir is lib under /usr/local/ and lib/<multiarch-triplet> under /usr/. Thus, I think this is something to bring up with the meson-folks.

**Comment by Rondom** [comment]
https://github.com/mesonbuild/meson/issues/2197

**Comment by tuzhucheng** [comment]
Can temporarily get around by doing this?

```
meson configure -D libdir=lib
```

**Comment by hellvesper** [comment]
`sudo ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.2.0 /lib/x86_64-linux-gnu/libfuse.so.3`
or 
`sudo ln -s /usr/local/lib/libfuse3.so.3.2.0 /lib/x86_64-linux-gnu/libfuse3.so.3` 
if you installed fuse with `meson configure -D libdir=lib`
should fix this

**Comment by tksuoran** [comment]
Fix? No. That is a workaround at best. A real fix is still needed.

**Comment by basickarl** [comment]
I've tried this and still getting:
```
Depends: libfuse3 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by basickarl** [comment]
Here are some built packages, how safe they are who knows: https://get.onedata.org/apt/ubuntu/trusty/pool/main/libf/libfuse3/

**Comment by Nikratio** [comment]
I believe Meson gets the library path (`/usr/local/lib/x86_64-linux-gnu`) for installing libfuse from the operating system (aka Ubuntu). When installing sshfs, it gets the library search path from ld.so. Is `usr/local/lib/x86_64-linux-gnu` included in your `/etc/ld.so.conf` or `/etc/ld.so.conf.d/*.conf`? If not, does adding it there fix the problem?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Comment by gautamworah96** [comment]
Creating the symlink from the libfuse3.so.3.2.0 to the file in /lib folder works!

**Comment by vbulchandani** [comment]
I am still getting this issue with latest build.  Followed the step carefully, but failed. It should be kept as open.

**Comment by phanirithvij** [comment]
@Nikratio 
```
cat /etc/ld.so.conf.d/*.conf 
```
```
# Multiarch support
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu
# libc default configuration
/usr/local/lib
# Multiarch support
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```

`/usr/lib/x86_64-linux-gnu` is already in `/etc/ld.so.conf.d/x86_64-linux-gnu.conf`

**Comment by phanirithvij** [comment]
```
ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.9.1 /lib/x86_64-linux-gnu/libfuse3.so.3
```
fixed it for me

**Comment by tsuu32** [comment]
My solution:
```
sudo ldconfig
```

**Comment by jmtysonjr** [comment]
Ran into this today. My fix:
``
$ sudo ln -s /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3 /lib/x86_64-linux-gnu/libfuse3.so.3
``

**Comment by 2reenact** [comment]
I did all the solutions I could found in this issue. but they didn't worked.
but I could solve this problem with re-installing pytest to python3 pytest.
`pip3 install pytest`
then I re-installed libfuse from `ninja` step.
finally I could make the example codes and my FUSE run.

**Comment by 2reenact** [comment]
I did all the solutions I could found in this issue. but they didn't worked.
but I could solve this problem with re-installing pytest to python3 pytest.
`pip3 install pytest`
then I re-installed libfuse from `ninja` step.
and finally I could make the example codes and my FUSE run.

**Comment by 2reenact** [comment]
I did all the solutions I could found in this issue. but they didn't worked.
but I could solve this problem with re-installing pytest to python3 pytest.
pip3 install pytest
then I re-installed libfuse from ninja step.
and finally I could make the example codes and my FUSE run.
