### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#213]
We need to check if every file specifies whether `COPYING` or `COPYING.LIB` applies, and fix references to LGPL2 (`COPYING.LIB` contains LGPLv2.1)

**Comment by chrisd8088** [comment]
This would be great -- I spent some time today tracking down which license applied to the library part of FUSE, and as the FAQ (which used to have some helpful text describing which license applied to which part of FUSE) was deleted in 7a93cf05, it's a bit hard to determine quickly.  One can trust Wikipedia, or look at the headers of the source code files, but it would be great to have it spelled out on the home page or in another prominent place in the docs.

Thank you for maintaining FUSE, it's much appreciated!

**Comment by chrisd8088** [comment]
Hey, thanks very much, this is great!  Thanks very much for the fast response!
