### ISSUE TITLE
should perform math check

### ISSUE THREAD

**Issue by jsoref** [libfuse/libfuse#222]
If think this:
https://github.com/libfuse/libfuse/blob/ae2cb7bd98f2f63b1b86320d7b8f0622d9a971d9/util/mount.fuse.c#L43

Needs a guard, specifically:
```c
	if (optlen >= (SIZE_MAX - cmdlen - 4)/4) {
		fprintf(stderr, "%s: argument too long\n", progname);
		exit(1);
	}
```

**Comment by Nikratio** [comment]
You are right, thanks!
