### ISSUE TITLE
test_passthrough atime check fails

### ISSUE THREAD

**Issue by bryongloden** [libfuse/libfuse#224]
Hi, I just downloaded libfuse and followed the Installation section. As it says, I tried the two cases
```
$
$ sudo python3 -m pytest test/
$
```
 and
```
$ sudo chown root:root util/fusermount3
$ sudo chmod 4755 util/fusermount3
$ python3 -m pytest test/
```
while testing it.

In each case, the first 18 tests pass, however the 19th test fails:
> test/test_examples.py::test_passthrough[False-passthrough] FAILED
> and i get output:
> ============================= test session starts ==============================
> platform linux -- Python 3.5.3, pytest-3.2.5, py-1.5.2, pluggy-0.4.0 -- /usr/bin/python3
> cachedir: test/.cache
> rootdir: /tmp/fuse-3.2.1/build/test, inifile: pytest.ini
> collecting ... collected 29 items
> 
> test/test_ctests.py::test_write_cache[False] PASSED
> test/test_ctests.py::test_write_cache[True] PASSED
> test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED
> test/test_ctests.py::test_notify1[True-invalidate_path] PASSED
> test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED
> test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED
> test/test_ctests.py::test_notify1[False-invalidate_path] PASSED
> test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED
> test/test_ctests.py::test_notify_file_size[True] PASSED
> test/test_ctests.py::test_notify_file_size[False] PASSED
> test/test_examples.py::test_hello[hello-options0] PASSED
> test/test_examples.py::test_hello[hello-options1] PASSED
> test/test_examples.py::test_hello[hello_ll-options0] PASSED
> test/test_examples.py::test_hello[hello_ll-options1] PASSED
> test/test_examples.py::test_passthrough_ll[False-False] PASSED
> test/test_examples.py::test_passthrough_ll[False-True] PASSED
> test/test_examples.py::test_passthrough_ll[True-False] PASSED
> test/test_examples.py::test_passthrough_ll[True-True] PASSED
> test/test_examples.py::test_passthrough[False-passthrough] FAILED
> =========================== short test summary info ============================
> FAIL test/test_examples.py::test_passthrough[False-passthrough]
> 
> =================================== FAILURES ===================================
> _____________________ test_passthrough[False-passthrough] ______________________
> Traceback (most recent call last):
>   File "/tmp/fuse-3.2.1/build/test/test_examples.py", line 154, in test_passthrough
>     tst_utimens(work_dir, ns_tol=1000)
>   File "/tmp/fuse-3.2.1/build/test/test_examples.py", line 596, in tst_utimens
>     assert abs(fstat.st_atime - atime) < 1e-3
> AssertionError: assert 0.2799999713897705 < 0.001
>  +  where 0.2799999713897705 = abs((1511721208.0 - 1511721208.28))
>  +    where 1511721208.0 = os.stat_result(st_mode=16877, st_ino=32909, st_dev=37, st_nlink=2, st_uid=0, st_gid=0, st_size=1024, st_atime=1511721208, st_mtime=1511721123, st_ctime=1511721166).st_atime
> !!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
> ===================== 1 failed, 18 passed in 19.46 seconds =====================
> 

How can I fix it? For background, it fails if I run as root and regular user. Furthermore, the following could be helpful information:

> root@debian:/tmp# uname -r
> 4.9.0-4-686-pae
> root@debian:/tmp# uname -a
> Linux debian 4.9.0-4-686-pae #1 SMP Debian 4.9.51-1 (2017-09-28) i686 GNU/Linux
> root@debian:/tmp# mount | grep /tmp
> /dev/sda7 on /tmp type ext4 (rw,relatime,data=ordered)
> root@debian:/tmp# fdisk -l | grep /sda7
> /dev/sda7       13451264 14221311   770048  376M 83 Linux

Thanks in advance.

**Comment by Nikratio** [comment]
That's odd. I don't have any immediate insights, but I think you can probably still safely run libfuse. There is just something strange going on with the timestamp accuracy in one of the examples...
