### ISSUE TITLE
Hard Link creation brakes mount point

### ISSUE THREAD

**Issue by g-fusion** [libfuse/libfuse#226]
Hello,

Using FUSE-2.9.2 and mounting NFS. Then I am trying to create hard link (using standard ln command) which breaks the mount point and finished with an error "Segmentation fault". If you try to browse the mount point, it says : "Transport endpoint is not connected". Same test executed from Java small test app (using 1.8) and creating hard links. Sometimes it works, sometimes it breaks. What I noticed is that when it works, inodes are not the same for source and target. It breaks easily if you cleanup before you recreate your links and you clean up source first.
Now this is really odd. It seems pretty straight forward scenario to me and I was wondering if I am missing something here. Full Debug trace  from fuse :

------------------
LOOKUP /links
getattr /links
   NODEID: 2
   unique: 52, success, outsize: 144
unique: 53, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 3672321
   unique: 53, success, outsize: 32
unique: 54, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 3672321
readdir[0] from 0
   unique: 54, success, outsize: 112
unique: 55, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 3672321
   unique: 55, success, outsize: 16
unique: 56, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
   unique: 56, success, outsize: 16
unique: 57, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 3672321
getattr /links
   unique: 57, success, outsize: 120
unique: 58, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 3672321
LOOKUP /links/f.txt
getattr /links/f.txt
   NODEID: 3
   unique: 58, success, outsize: 144
unique: 59, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3717281
getattr /
   unique: 59, success, outsize: 120
unique: 60, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3717281
LOOKUP /h.txt
getattr /h.txt
   unique: 60, error: -2 (No such file or directory), outsize: 16
unique: 61, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3717281
LOOKUP /links
getattr /links
   NODEID: 2
   unique: 61, success, outsize: 144
unique: 62, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 3717281
LOOKUP /links/f.txt
getattr /links/f.txt
   NODEID: 3
   unique: 62, success, outsize: 144
unique: 63, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3717281
LOOKUP /h.txt
getattr /h.txt
   unique: 63, error: -2 (No such file or directory), outsize: 16
unique: 64, opcode: LINK (13), nodeid: 1, insize: 54, pid: 3717281
link /links/f.txt /h.txt
Segmentation fault
------------------

**Comment by Nikratio** [comment]
Thanks for the report! Are you aware that fuse is just providing a framework for the development of filesystems, but not a filesystem itself? It sounds as if you are working with a specific filesystem that crashes for you. Whoever develops that filesystem should be able to help you.

Feel free to re-open if I misunderstood!
