### ISSUE TITLE
Centos compilation failure

### ISSUE THREAD

**Issue by PhilipOrleans** [libfuse/libfuse#227]
Although I installed libfuse prior, and it did compile and install fine, when I run
meson ..
on sshfs-sshfs-3.3.1/build
it fails with
Native dependency 'fuse3' not found

Also my kernel has fuse loaded.
I have a fuse3 dir in /include and /usr/include, with the headers, but meson does not use them, where should they be?

**Comment by Nikratio** [comment]
Thanks for the report! You probably installed libfuse 2.x rather than 3.x. If you have further questions, please use the mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel). Thanks!
