### ISSUE TITLE
Filesystem causing softlocks on Linux 3.16

### ISSUE THREAD

**Issue by ma9e** [libfuse/libfuse#236]
I'm trying to use the httpfs2 filesystem ([here](https://sourceforge.net/projects/httpfs/files/httpfs2/)) with Linux 3.16.47 and fuse 2.9.7. Not sure if the processor has anything to do with it, but it's SuperH.

The problem we're seeing is that somewhere after httpfs2 forks, something like 8/10 times, it prints out "fuse: writing device: Invalid argument". After this, any attempt to read the filesystem softlocks the console and requires a power cycle. It seems to work more frequently on the first attempt.

httpfs2 works okay on Linux 4.1.12, so it seems like the fuse driver in older versions might be defective. Is there anything else I can provide or look at to help debug this from your perspective? Any assistance you can provide is hugely appreciated.

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid this sounds like a kernel bug that has been fixed for a while. So short of convincing someone to backport the fix to Linux 3.16, there isn't much that can be done.

**Comment by ma9e** [comment]
Hi Nik, thanks for the reply. I think we are looking into backporting the fix. Would you mind providing a high-level overview of what needs to be done?

**Comment by Nikratio** [comment]
I wouldn't mind, but I can't. I work mostly on libfuse rather than the kernel module, I don't know which commit fixed the issue, and kernel 3.16 is from 2015 or so. Sorry.
