### ISSUE TITLE
Typo in the comments( fuse_lowlevel.h file)

### ISSUE THREAD

**Issue by PhaneendraReddy** [libfuse/libfuse#237]
NOT IMPORTANT:

FILE:  fuse-3.2.1/include/fuse_lowlevel.h 
LINE: 1446  * See documentation of `fuse_add_direntryt()` for more details.
The comment should say "fuse_add_direntry(" instead of "fuse_add_direntryt("

**Comment by Nikratio** [comment]
Thanks, looks like it's already fixed!
