### ISSUE TITLE
Let a regular user use /bin/umount to unmount fuse mounts.

### ISSUE THREAD

**Issue by toojays** [libfuse/libfuse#246]
If I have an entry such as the following in /etc/fstab:
```
mini.toojays.net:/home /srv/mini/home fuse.sshfs uid=toojays,user,noauto 0 0
```
and the appropriate permission on the mount point (/srv/mini/home in this example), I can mount as a regular user:
```
toojays@nugget:~$ mount /srv/mini/home
toojays@nugget:~$ mount | grep mini
mini.toojays.net:/home on /srv/mini/home type fuse.sshfs (rw,nosuid,nodev,noexec,relatime,user_id=1000,group_id=1000,user=toojays)
```

But I can't use umount to unmount.
```
toojays@nugget:~$ umount /srv/mini/home 
umount: /srv/mini/home: Permission denied
```

Of course I can unmount with ``fusermount -u /srv/mini/home``. So this is not really a big deal. Just weird that I can use the standard tool to mount, but not to unmount.

This issue came up a decade or so ago: https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/871w0vev6h.fsf%40frosties.localdomain/#msg20070192
In that thread there was some discussion about making this work by specifying a ``uhelper=`` script in mtab. It seems pretty easy to create a uhelper script that would just forward its arguments to fusermount. Unfortunately this can't just be added to the fstab, as fuse doesn't like it.
```
toojays@nugget:~$ mount /srv/mini/home
fuse: unknown option `uhelper=fuse'
```
In  [Ubuntu bug 1117348](https://bugs.launchpad.net/ubuntu/+source/fuse/+bug/1117348) Loïc Minier found that editing the mtab after mount to add the uhelper argument had the desired effect.

IMO the ideal thing would be for all fuse mounts to have a default uhelper=fuse which would invoke an umount->fusermount forwarding script. But even if fuse were to just allow the user to specify a uhelper script, that would be an improvement here.

**Comment by Nikratio** [comment]
Sounds like a good idea. Would you be able to provide pull request?

**Comment by rianhunter** [comment]
I've posted a PR to util-linux to update the `umount` command to support unmounting FUSE mounts natively. https://github.com/karelzak/util-linux/pull/705

**Comment by Nikratio** [comment]
Cool, thanks!

**Comment by karelzak** [comment]
The uhelper= is problematic -- this mount option is maintained in userspace, it means it's useless in some use-cases like namespaces, chroots, etc. It seems better to add support for FUSE to libmount natively.

**Comment by ukleinek** [comment]
> The uhelper= is problematic -- this mount option is maintained in userspace, it means it's useless in some use-cases like namespaces, chroots, etc. It seems better to add support for FUSE to libmount natively.

I don't see why this is problematic. The concept of uhelper works fine for "automatic media mounting for desktop users". And if you mount a device (or fuse fs) from one namespace or chroot I would expect that unmounting from another is allowed to be problematic and never the less works fine most of the time anyhow because in that other namespace unmounting works in the same way as in the original one.

**Comment by ukleinek** [comment]
FTR: Before noticing this issue, I reported the same wish to Debian: https://bugs.debian.org/913230

**Comment by ukleinek** [comment]
> And nowadays mount options are not maintained in userspace. At least on my system `/etc/mtab` is a link to `../proc/self/mounts`.

After digging some more this turned out to be wrong. The uhelper stuff is taken from `/run/mount/utab`, not the kernel. So I was able to unmount a fuse fs after writing an entry for my mount to this file. Ugly.

**Comment by karelzak** [comment]
I'm working on support within umount(8), karelzak/util-linux#705  ... it should be done this week.

**Comment by rianhunter** [comment]
This was fixed in https://github.com/karelzak/util-linux/commit/5fea669e9ef0a08804f72bb40f859f239f68c30a, latest versions of util-linux support this. You may close this issue.

**Comment by Nikratio** [comment]
Cool, thanks!
