### ISSUE TITLE
fusermount: include "FUSE options" in help output

### ISSUE THREAD

**Issue by blueyed** [libfuse/libfuse#256]
`fusermount -h` displays:
```
fusermount: [options] mountpoint
Options:
 -h		    print help
 -V		    print version
 -o opt[,opt...]   mount options
 -u		    unmount
 -q		    quiet
 -z		    lazy unmount
```

While `example/hello -h` includes:
```
FUSE options:
…
    -o allow_other         allow access to other users
…    -o [no_]splice_read    use splice to read from the fuse device
```

I think the help for fusermount should include all the options, too - e.g. in a "mount options" section.

I've noticed this when seeing `fuse_ll_opts` (https://github.com/libfuse/libfuse/blob/a0c14264e99491406f8a346b50903dadaccaa6f8/lib/fuse_lowlevel.c#L2473-L2502) and wondering where it was used.
Does fuse itself use it somewhere? (only the `fusermount` and `mount.fuse` programs are shipped with distributions it seems)

**Comment by Nikratio** [comment]
Thanks for the report! `fusermount` should only be used for un-mounting fuse filesystems, not for mounting them. Thus, including mount options in the `--help` output would be rather confusing.

(The fact that libfuse happens to internally use `fusermount` for mounting in some situations is an implementation detail that may change at any time).

**Comment by blueyed** [comment]
I see.
Thanks for your reply.
Is there another place where all those options could be shown/documented then?
I think all of them should be in the man page (`fuse(8)`), and maybe `mount.fuse`, too?
I had a rather hard time looking up what python-llfuse's `default_options` set refers to / means.

**Comment by Nikratio** [comment]
Documentation for libfuse is at http://libfuse.github.io/, the mount options are documented at e.g. http://libfuse.github.io/doxygen/fuse__common_8h.html#af5431cea3c9a8490cefe087cb8089cd9.

Patches to improve layout and visibility are welcome. The documentation is generated from the header files (e.g. https://github.com/libfuse/libfuse/blob/master/include/fuse_common.h#L448) using Doxygen.
