### ISSUE TITLE
Please add systemd service file

### ISSUE THREAD

**Issue by gcsideal** [libfuse/libfuse#261]
SysV init.d scripts depreciated for a while. Would be good if FUSE ship a Systemd Service file.

**Comment by Nikratio** [comment]
Is this actually necessary? I think loading the fuse module in the init script is an anti-feature (there's /etc/modules for that), and isn't mounting of the control filesystem (/sys/fs/fuse/connections) already handled by systemd/udev automatically (similar to /dev/shm, /sys/fs/cgroup/* etc).

**Comment by Nikratio** [comment]
From systemd-devel:

systemd already contains a .mount unit for this
(sys-fs-fuse-connections.mount), which is pulled in automatically when
the kmod is loaded, see 99-systemd.rules. Hence you shouldn't need to
have any further script or such in place, it should already get
mounted out of the box.
