### ISSUE TITLE
write_buf null mem pointers with FUSE_CAP_WRITEBACK_CACHE

### ISSUE THREAD

**Issue by igremmer** [libfuse/libfuse#265]
I was testing FUSE_CAP_WRITEBACK_CACHE and started getting null buffers during write_buf operations (in_buf->buf[0].mem is null).  The feature itself looks great and will be a good fit for my project.  I am using Ubuntu 18.04 64 bit and head libfuse from github.  To recreate the issue you can use the passthrough_ll.c example and enable writeback in main():
```
  struct lo_data lo = { .debug = 0,
    	                      .writeback = 1 };
```

Mount the filesystem:

>   ./passthrough_ll -d /tmp/passthrough

Run a dd operation:

>   cd /tmp/passthrough
>   dd if=/dev/zero of=zeros10.bin bs=128K count=10

I modified the write_buf function to log the pointer values.  See the null mem values.  I spaced this out a bit to show the relevant lines.

> FUSE library version: 3.2.4
> unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
> INIT: 7.26
> flags=0x001ffffb
> max_readahead=0x00020000
> lo_init: activating writeback
>    INIT: 7.26
>    flags=0x0001f039
>    max_readahead=0x00020000
>    max_write=0x00020000
>    max_background=0
>    congestion_threshold=0
>    time_gran=1
>    unique: 1, success, outsize: 80
> unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 8105
>    unique: 2, success, outsize: 120
> unique: 3, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 8105
>    unique: 3, success, outsize: 120
> unique: 4, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 8105
>    unique: 4, error: -38 (Function not implemented), outsize: 16
> unique: 5, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 31299
> lo_lookup(parent=1, name=zeros10.bin)
>   1/zeros10.bin -> 139757027855984
>    unique: 5, success, outsize: 144
> unique: 6, opcode: OPEN (14), nodeid: 139757027855984, insize: 48, pid: 31299
> lo_open(ino=139757027855984, flags=33281)
>    unique: 6, success, outsize: 32
> unique: 7, opcode: GETXATTR (22), nodeid: 139757027855984, insize: 68, pid: 31299
>    unique: 7, error: -38 (Function not implemented), outsize: 16
> unique: 8, opcode: SETATTR (4), nodeid: 139757027855984, insize: 128, pid: 31299
>    unique: 8, error: -38 (Function not implemented), outsize: 16
> unique: 9, opcode: GETATTR (3), nodeid: 139757027855984, insize: 56, pid: 31299
>    unique: 9, success, outsize: 120
> unique: 10, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> BEFORE: off: (0), bufv: (0x7f1bbd089e40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
> AFTER: off: (0), bufv: (0x7f1bbd089e40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
>    unique: 10, success, outsize: 24
> unique: 11, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> BEFORE: off: (131072), bufv: (0x7f1bbd88ae40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
> unique: 12, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> BEFORE: off: (262144), bufv: (0x7f1bbd089e40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
> AFTER: off: (131072), bufv: (0x7f1bbd88ae40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
>    unique: 11, success, outsize: 24
> unique: 13, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> unique: 14, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> BEFORE: off: (524288), bufv: (0x7f1bbd88ae40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
>
>
> BEFORE: off: (393216), bufv: (0x7f1bbc888e40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 11, pos 0 **// mem is nil**
>
>
> unique: 15, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
>
>
> BEFORE: off: (655360), bufv: (0x7f1bafffee40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 13, pos 0 **// mem is nil**
>
>
> AFTER: off: (262144), bufv: (0x7f1bbd089e40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
>    unique: 12, success, outsize: 24
> unique: 16, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
> BEFORE: off: (786432), bufv: (0x7f1bbd089e40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
> AFTER: off: (524288), bufv: (0x7f1bbd88ae40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
>    unique: 14, success, outsize: 24
> unique: 17, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
>
>
> BEFORE: off: (917504), bufv: (0x7f1baf7fde40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 15, pos 0 **// mem is nil**
>
>
> unique: 18, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
>
>
> AFTER: off: (393216), bufv: (0x7f1bbc888e40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 11, pos 0 **// mem is nil**
>
>
> BEFORE: off: (1048576), bufv: (0x7f1bbd88ae40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
>    unique: 13, success, outsize: 24
> unique: 19, opcode: WRITE (16), nodeid: 139757027855984, insize: 131152, pid: 0
>
>
> BEFORE: off: (1179648), bufv: (0x7f1bbc888e40, count 1, idx 0, off 0), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 11, pos 0
>
>
> AFTER: off: (655360), bufv: (0x7f1bafffee40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 13, pos 0
>
>
>    unique: 15, success, outsize: 24
> unique: 20, opcode: SETATTR (4), nodeid: 139757027855984, insize: 128, pid: 31299
>    unique: 20, error: -38 (Function not implemented), outsize: 16
> AFTER: off: (786432), bufv: (0x7f1bbd089e40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6a1010, fd 7, pos 0
>    unique: 16, success, outsize: 24
> AFTER: off: (917504), bufv: (0x7f1baf7fde40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 15, pos 0
>    unique: 17, success, outsize: 24
> AFTER: off: (1048576), bufv: (0x7f1bbd88ae40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, mem 0x7f1bbe6c3010, fd 5, pos 0
>    unique: 18, success, outsize: 24
> AFTER: off: (1179648), bufv: (0x7f1bbc888e40, count 1, idx 1, off 131072), buf[0]: (size 131072, flags 2, **mem (nil)**, fd 11, pos 0
>    unique: 19, success, outsize: 24
> unique: 21, opcode: RELEASE (18), nodeid: 139757027855984, insize: 64, pid: 0
>    unique: 21, success, outsize: 16

Here is the modified write_buf function:
```
static void lo_write_buf(fuse_req_t req, fuse_ino_t ino,
			 struct fuse_bufvec *in_buf, off_t off,
			 struct fuse_file_info *fi)
{
	(void) ino;
	ssize_t res;
	struct fuse_bufvec out_buf = FUSE_BUFVEC_INIT(fuse_buf_size(in_buf));

	out_buf.buf[0].flags = FUSE_BUF_IS_FD | FUSE_BUF_FD_SEEK;
	out_buf.buf[0].fd = fi->fh;
	out_buf.buf[0].pos = off;

        // in_buf->buf[0].mem is occasionally, randomly null
	fprintf(stderr, "BEFORE: off: (%ld), bufv: (%p, count %ld, idx %ld, off %ld), buf[0]: (size %ld, flags %d, mem %p, fd %d, pos %ld\n", 
		off,
	 	in_buf, in_buf->count, in_buf->idx, in_buf->off,
		in_buf->buf[0].size, in_buf->buf[0].flags, in_buf->buf[0].mem, in_buf->buf[0].fd, in_buf->buf[0].pos);
		
        // when the mempointer is null, this just returns early
	res = fuse_buf_copy(&out_buf, in_buf, 0);

	fprintf(stderr, "AFTER: off: (%ld), bufv: (%p, count %ld, idx %ld, off %ld), buf[0]: (size %ld, flags %d, mem %p, fd %d, pos %ld\n", 
		off,
	 	in_buf, in_buf->count, in_buf->idx, in_buf->off,
		in_buf->buf[0].size, in_buf->buf[0].flags, in_buf->buf[0].mem, in_buf->buf[0].fd, in_buf->buf[0].pos);

	if(res < 0)
		fuse_reply_err(req, -res);
	else
		fuse_reply_write(req, (size_t) res);
}
```

**Comment by Nikratio** [comment]
It's not a bug, it's a feature. I only have my phone at moment so I can't be very precise, but there's more to this structure than just a pointer. There's also a file descriptor and accessor functions. Take as look at the header files.

**Comment by igremmer** [comment]
Thanks for your help.  I was trying to understand fuse_buf_copy, but instead, based on your advice, I just used it directly, and it is working now.
Thank you!
