### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [libfuse/libfuse#272]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “get_string_opt”](https://github.com/libfuse/libfuse/blob/055fcec831aff1037f5240f50481827b847f8cfa/util/fusermount.c#L699 "Update candidate").

**Comment by Nikratio** [comment]
Thanks for the report! Would you be able to provide a pull request that fixes the issue?
