### ISSUE TITLE
Write performance drops when testing with passthrough_ll and writeback cache on

### ISSUE THREAD

**Issue by sjzlsr** [libfuse/libfuse#279]
Recently I'm testing with passthough_ll and writeback cache on, and found out that the performance drops significantly comparing to that in local file system.

Linux kernel: 4.17.12
libfuse version: 3.2.5

Reproduce:
```bash
./passthrough_ll -o writeback /mnt/fuse/
```

Performance:
```text
[root@A01-R20-I31-77-8S5FKM2 example]# dd if=/dev/zero of=/mnt/fuse/tmp/test001 bs=1M count=2000
^C2+0 records in
2+0 records out
2097152 bytes (2.1 MB) copied, 14.3527 s, 146 kB/s
```

I checked the kernel trace log, and found out that balance_dirty_pages is triggered in every single write, which is very time consuming.

```bash
echo 1 > /sys/kernel/debug/tracing/events/writeback/balance_dirty_pages/enable
cat /sys/kernel/debug/tracing/trace
```

```text
              dd-19067 [001] .... 195295.568097: balance_dirty_pages: bdi 0:42: limit=3180390 setpoint=2782421 dirty=5 bdi_setpoint=0 bdi_dirty=32 dirty_ratelimit=32 task_ratelimit=0 dirtied=32 dirtied_pause=32 paused=0 pause=33 period=33 think=0 cgroup_ino=1
              dd-19067 [001] .... 195295.602029: balance_dirty_pages: bdi 0:42: limit=3180390 setpoint=2782421 dirty=5 bdi_setpoint=0 bdi_dirty=33 dirty_ratelimit=32 task_ratelimit=0 dirtied=1 dirtied_pause=0 paused=0 pause=34 period=34 think=1 cgroup_ino=1
              dd-19067 [001] .... 195295.637026: balance_dirty_pages: bdi 0:42: limit=3180390 setpoint=2782421 dirty=5 bdi_setpoint=0 bdi_dirty=34 dirty_ratelimit=32 task_ratelimit=0 dirtied=1 dirtied_pause=0 paused=0 pause=35 period=35 think=1 cgroup_ino=1
```

I suppose this is not as expected. Would you please take a look at the issue? Thanks
[trace.txt](https://github.com/libfuse/libfuse/files/2269781/trace.txt)

**Comment by Nikratio** [comment]
Thanks for the report!

As far as I can tell, this is a problem with the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.

**Comment by stapelberg** [comment]
Just found this issue. We’re discussing this at the kernel level at https://lore.kernel.org/linux-fsdevel/CANnVG6kZzN1Ja0EmxG3pVTdMx8Kf8fezGWBtCYUzk888VaFThg@mail.gmail.com/
