### ISSUE TITLE
Avoid use of reserved identifiers

### ISSUE THREAD

**Issue by HalosGhost** [libfuse/libfuse#28]
According to the C standard section 17.6.4.3.2 ("Global Names"):

> Certain sets of names and function signatures are always reserved to the implementation:
* Each name that contains a double underscore __ or begins with an underscore followed by an uppercase letter (2.12) is reserved to the implementation for any use.
* Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

Below is a list of ``define``s which violate this section (by using reserved identifiers):

```
include/fuse_common.h:#define _FUSE_COMMON_H_
include/fuse_opt.h:#define _FUSE_OPT_H_
include/fuse_lowlevel.h:#define _FUSE_LOWLEVEL_H_
include/cuse_lowlevel.h:#define _CUSE_LOWLEVEL_H_
include/fuse.h:#define _FUSE_H_
include/fuse_kernel.h:#define _LINUX_FUSE_H
```

Simply removing the leading ``_`` corrects this issue.

**Comment by Nikratio** [comment]
Sounds reasonable, thanks for reporting! Could you also provide a pull request?

**Comment by HalosGhost** [comment]
@Nikratio, can do! I'm glad to see that this is something you are open to! I will open a PR for it tonight.
