### ISSUE TITLE
forget not called on file system shutdown

### ISSUE THREAD

**Issue by noahdesu** [libfuse/libfuse#292]
I recently noticed that when using the low-level interface I'm not receiving forget/multi_forget calls on shutdown (e.g. fusermount -u). Is this expected, or is destroy used for this type of clean-up that happens at shutdown even though the lookup counts may be positive.

**Comment by Nikratio** [comment]
Thanks for the report! I think this ins answered by http://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html#a97de3962fc55f136c6bd48183705dbe8 - if not, feel free to reopen.
