### ISSUE TITLE
write() after release()

### ISSUE THREAD

**Issue by Adonai** [libfuse/libfuse#295]
This is one of the files being rsynced, roughly in the middle of the overall process.
I see following in the debug output:

```
unique: 459221, opcode: CREATE (35), nodeid: 4358, insize: 103, pid: 8654
create flags: 0x80c1 /mega/whatever-dir/whatever-file 0100600 umask=0000
   create[0] flags: 0x80c1 /mega/whatever-dir/whatever-file
getattr /mega/whatever-dir/whatever-file
   NODEID: 15944
   unique: 459221, success, outsize: 160
unique: 459222, opcode: FLUSH (25), nodeid: 15944, insize: 64, pid: 8654
flush[0]
   unique: 459222, success, outsize: 16
unique: 459223, opcode: RELEASE (18), nodeid: 15944, insize: 64, pid: 0
unique: 459224, opcode: OPEN (14), nodeid: 15944, insize: 48, pid: 8654
open flags: 0x8002 /mega/whatever-dir/whatever-file
release[0] flags: 0x8001
   open[0] flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 459224, success, outsize: 32
   unique: 459223, success, outsize: 16
unique: 459225, opcode: SETATTR (4), nodeid: 15944, insize: 128, pid: 8534
getattr /mega/whatever-dir/whatever-file
   unique: 459225, success, outsize: 120
unique: 459226, opcode: WRITE (16), nodeid: 15944, insize: 88, pid: 11192
write[0] 8 bytes to 0 flags: 0x8002
```

So it seems release is executed after open, and then it tries to write to released file.  
Yes, the program is multithreaded. Is there anything to be done? What are usual workarounds for this?

**Comment by Nikratio** [comment]
Thanks for the report! This should not happen. Could you provide a small example program that reproduces the problem?

**Comment by Nikratio** [comment]
(Note that, if this is indeed a bug, then it most likely is in the Linux kernel and would have to be fixed there)

**Comment by Adonai** [comment]
Ouch, that's hard... you'll possibly need my custom filesystem and an account in a cloud provider, is that feasible? or should I try to reproduce this on other well-known filesystem ?

**Comment by Adonai** [comment]
Some context that's relevant even if I fail to reproduce this:
System info:
```
System:    Host: house-of-maker Kernel: 4.18.5-arch1-1-ARCH x86_64 bits: 64 Desktop: KDE Plasma 5.13.5 
           Distro: Arch Linux 
Machine:   Type: Desktop Mobo: ASRock model: X370 K4 UEFI: American Megatrends 
           v: P4.70 date: 04/18/2018 
CPU:       8-Core: AMD Ryzen 7 1700X type: MT MCP speed: 2553 MHz min/max: 2200/3400 MHz 
Network:   Card-1: Intel I211 Gigabit Network driver: igb 
Drives:    Local Storage: total: 4.31 TiB used: 1.73 TiB (40.0%) 
Info:      Processes: 398 Uptime: 10d 1h 20m Memory: 31.41 GiB used: 7.89 GiB (25.1%) Shell: zsh inxi: 3.0.20 
```

Usage info:

* [marcfs](https://gitlab.com/Kanedias/MARC-FS) filesystem in ~/remote/mailru
* encfs filesystem at ~/remote/mailru/mega, decrypted data at ~/remote/mailru-decrypted
* The logs in original report are obtained from upper-level marcfs filesystem, `whatever-dir` and `whatever-file` in realite are quite long encrypted file names
* The rsync is done with source from photo archive outside of decrypted encfs dir and with destination inside it.

The offending rsync code seems to be the following:

**receiver.c**
```cpp
   fd2 = open_tmpfile(fnametmp, fname, file);    // <------ here mktemp creates and closes the tmpfile then rsync reopens it            
   if (fd2 != -1)                                            
       cleanup_set(fnametmp, partialptr, file, fd1, fd2);    
    ...<snip>...
    /* recv file data */                                      
    recv_ok = receive_data(f_in, fnamecmp, fd1, st.st_size,   
               fname, fd2, F_LENGTH(file));      // <-------- here the fd2 is written to   
   
```

**Comment by Adonai** [comment]
Couldn't reproduce that with any other filesystem. Tried sshfs, fuse-zip, mcachefs

**Comment by Adonai** [comment]
Looks like it was caused by the presence of `fuse_operations.create` callback.

After removing it everything came back to normal, no issues. The libfuse used fallback implementation with MKNOD + OPEN and after flush it was always ordered correctly.

```
LOOKUP /mega/whatever-dir/whatever-file
getattr /mega/whatever-dir/whatever-file
   unique: 359290, error: -2 (No such file or directory), outsize: 16
unique: 359291, opcode: MKNOD (8), nodeid: 15670, insize: 103, pid: 26336
mknod /mega/whatever-dir/whatever-file 0100600 0x0 umask=0000
getattr /mega/whatever-dir/whatever-file
   NODEID: 17518
   unique: 359291, success, outsize: 144
unique: 359292, opcode: OPEN (14), nodeid: 17518, insize: 48, pid: 26336
open flags: 0x8001 /mega/whatever-dir/whatever-file
   open[0] flags: 0x8001 /mega/whatever-dir/whatever-file
   unique: 359292, success, outsize: 32
unique: 359293, opcode: FLUSH (25), nodeid: 17518, insize: 64, pid: 26336
flush[0]
   unique: 359293, success, outsize: 16
unique: 359294, opcode: RELEASE (18), nodeid: 17518, insize: 64, pid: 0
release[0] flags: 0x8001
unique: 359295, opcode: OPEN (14), nodeid: 17518, insize: 48, pid: 26336
open flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 359294, success, outsize: 16
   open[0] flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 359295, success, outsize: 32
unique: 359296, opcode: FLUSH (25), nodeid: 17518, insize: 64, pid: 26336
flush[0]
   unique: 359296, success, outsize: 16
unique: 359297, opcode: RELEASE (18), nodeid: 17518, insize: 64, pid: 0
release[0] flags: 0x8002
unique: 359298, opcode: OPEN (14), nodeid: 17518, insize: 48, pid: 26198
open flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 359297, success, outsize: 16
   open[0] flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 359298, success, outsize: 32
unique: 359299, opcode: SETATTR (4), nodeid: 17518, insize: 128, pid: 26189
getattr /mega/whatever-dir/whatever-file
   unique: 359299, success, outsize: 120
unique: 359300, opcode: WRITE (16), nodeid: 17518, insize: 88, pid: 26336
write[0] 8 bytes to 0 flags: 0x8002
   write[0] 8 bytes to 0
   unique: 359300, success, outsize: 24
```

**Comment by Adonai** [comment]
No, this didn't completely go away, I still get this sometimes:
```
unique: 1582585, opcode: RELEASE (18), nodeid: 30534, insize: 64, pid: 0
unique: 1582586, opcode: OPEN (14), nodeid: 30534, insize: 48, pid: 26336
release[0] flags: 0x8002
open flags: 0x8002 /mega/whatever-dir/whatever-file
   open[0] flags: 0x8002 /mega/whatever-dir/whatever-file
   unique: 1582586, success, outsize: 32
   unique: 1582585, success, outsize: 16
```

**Comment by Nikratio** [comment]
CREATE() counts as OPEN(), so you'll get a RELEASE() call for create as well. Maybe that explains it?

**Comment by Adonai** [comment]
@Nikratio unfortunately no, now without CREATE I still hit this bug once in a while.

Not very critical at the moment so if I won't hit some sort of enlightenment in a week or so, please close this.

**Comment by AlexHighTower** [comment]
Hi

have the same issue with fuse 2.9.4 and marcfs

```
open[0] flags: 0x8002 /<file>.w2kTo4
release[0] flags: 0x8001
   unique: 169610, success, outsize: 32
unique: 169611, opcode: SETATTR (4), nodeid: 675, insize: 128, pid: 6907
getattr /<file>.w2kTo4
   unique: 169609, success, outsize: 16
```

it is reproduced 100% if to upload big amount of files via rsync after few minutes

**Comment by Adonai** [comment]
Looks like it's not related to encfs being mounted atop marcfs

**Comment by Adonai** [comment]
@Nikratio, can we make you a test account for marcfs and provide replication steps?

**Comment by Nikratio** [comment]
Thanks for the offer! I don't think this would help much though. As I said above, libfuse is just a gateway between the kernel and the filesystem, it does not create or inhibit any requests. So if you are getting write() requests for a file that hasn't been opened, this needs to be debugged and fixed in the linux kernel. The best way to get issues addressed is therefore to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel).

**Comment by Adonai** [comment]
@Nikratio, understood. Btw thanks for the awesome lib!

Guess it's time for me to dig out my old Linux repo again. You can never have too many kernel commits, eh.

P.S. Please visit IRC channel time to time, there are poor people drowning in questions out there.

**Comment by Adonai** [comment]
@Nikratio `#fuse` at Freenode IRC

**Comment by Nikratio** [comment]
@Adonai Sorry, that question was badly phrased. What I meant is: is that channel referenced anywhere on the website or the docs? I sadly don't have time to help with anything over IRC, so if there are pointers to it, they ought to be removed.

**Comment by Adonai** [comment]
@Nikratio understood

Contacted linux-fsdevel list, looks like it's my fault in the end.
