### ISSUE TITLE
fuse internal error: node 0 not found

### ISSUE THREAD

**Issue by limetech** [libfuse/libfuse#299]
This happens when multiple NFS clients are executing operations against a FUSE file system.  Each nfsd has up to 12 threads and it takes anywhere from minutes to hours to occur.  Does not matter what the value of the 'remember' mount option is set to, -1, 0, 300, 600 - eventually same internal error is hit.

Does not happen with 4.14 kernel, but does happen with 4.18 kernel, with FUSE versions 2.9.7 and 2.9.8, using high-level interface.

I apologize in advance for no logs and not more detailed info.  We are in process of bisecting kernel, but of course this is very time-consuming.  I thought I'd throw the issue out there in case a recent kernel change might ring a bell with someone.

**Comment by Nikratio** [comment]
Thanks for the report!

As far as I can tell, this is a problem with the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.
