### ISSUE TITLE
Allow for 'fh' to be set from any function

### ISSUE THREAD

**Issue by trapexit** [libfuse/libfuse#3]
Currently fuse_file_info.fh can only be set on open/create/opendir but it'd be useful to be able to change the value from any function in which fuse_file_info is used.

Is there a reason the structure passed in is a copy rather than the original? If parts of it are read only it should be on the user not to change them or separate out into one const and one non-const struct.

**Comment by Nikratio** [comment]
I think the reason is that `fh` is returned to the FUSE kernel module, which reads it only in responses to open-create/opendir. So changing the value in other request handlers would not have any effect.

However, I haven't checked the code yet.

**Comment by trapexit** [comment]
I wouldn't have thought the kernel had anything to do with keeping track of such things. I currently work around the problem by using a pointer but I'm storing a uint_t's worth of data and it'd be nicer to not need the malloc/free'ing.

**Comment by Nikratio** [comment]
Checking the code, my initial answer is correct. `fuse_file_info` is passed to the kernel by e.g. `fuse_reply_create`. A write request from the kernel comes with the corresponding `fh` value (see `do_write` in `fuse_lowlevel.c`). So any request whose corresponding `fuse_rely_*` function does not take a `fuse_file_info` argument cannot modify the `fh` member.

**Comment by trapexit** [comment]
Any idea why the kernel would be interested in `fh` or was it just out of convenience?

**Comment by Nikratio** [comment]
The kernel needs it because otherwise it can't pass it back to write, read etc.

**Comment by trapexit** [comment]
But `fh` is a userland object only AFAIU. Something libfuse or the like would care about. Not the kernel. The only reason I can see handing it to the kernel if it's not meaningful is because keeping track of it in libfuse was {too much work,too costly,etc.}.

Doesn't matter (besides not working the way I'd prefer). Just trying to understand the reasoning for the kernel to care about such things.

**Comment by Nikratio** [comment]
How would userland know what `fh` to use for which `write` request unless the kernel told you about it?

**Comment by Nikratio** [comment]
(let's continue this discussion on the fuse-devel mailing list please)
