### ISSUE TITLE
Useful tool/new example

### ISSUE THREAD

**Issue by mistotebe** [libfuse/libfuse#301]
I've been using [this filesystem](https://github.com/mistotebe/examples/tree/master/fuse) derived from null.c for a while and was wondering whether it might be a tool to include back in the examples directory.

It is mainly useful as a `tail` like replacement when dealing with an application that insists on logging extreme amounts of data to a file but you only really need the last few megabytes just before something interesting happens. Unlike `tail` it keeps it nice and semi-persistent and unlike `logrotate` doesn't hit the storage (which might be slow or just doesn't like having gigabytes written to it) nor does it need the application to support transitioning over to a new file (on SIGHUP or otherwise).

If you think it would be worth including, let me know if there is any cleanup needed to make that happen.

**Comment by Nikratio** [comment]
Thanks for the offer! I don't think this would be well placed as a libfuse example, because most of the code deals with how to implement the desired ring-buffer functionality - but the examples are meant to focus on how to use libfuse.
