### ISSUE TITLE
meson testing

### ISSUE THREAD

**Issue by ahmed-masud** [libfuse/libfuse#303]
https://github.com/libfuse/libfuse/blob/e469e1f8d19408e83d30aa1cfab06dd133304ad8/test/wrong_command.c#L8

Perhaps change the `return 1;` to `return 77;` to help with `ninja test` for situation when libfuse is a subproject.

**Comment by Nikratio** [comment]
What would be the effect? Could you submit a pull request?

**Comment by ahmed-masud** [comment]
just did, have a look
