### ISSUE TITLE
Pass request context to all handlers

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#31]
I don't see any reason why we need a special function to access the request context, it should simply be passed to all handlers. This avoids any trickery with thread-local variables.

I suspect the function was introduced in order to not break the API. With FUSE 3, this is no longer a concern.

**Comment by trapexit** [comment]
May I suggest adding in additional information as well? My main interest is the inode number (obviously in the high level API) but it's probably best to include all available. unique identifier and opcode.

**Comment by Nikratio** [comment]
I'm not sure what I was thinking when opening this issue. The `fuse_req_context` function simply returns `req->ctx`, so there is no special trickery required. Furthermore, none of the handlers receive the context object directly (so there is no inconsistency either). So this seems to be a non-issue entirely.

**Comment by trapexit** [comment]
You mean `fuse_get_context`? I'd argue from a cleanliness perspective the context should be passed into any functions where it may be necessary but it's not a huge deal so long as the relevant information is available which as I mentioned above there is some info that would be useful in the high level api which isn't available AFAIK.
