### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by Annu4git** [libfuse/libfuse#311]
Hi,
I just installed Fuse, and tried testing it, with this command : python -m pytest test/
And I am getting below error : 

============================================================ test session starts ============================================================
platform linux2 -- Python 2.7.15rc1, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python
cachedir: test/.cache
rootdir: /home/anurag/Anurag/Subjects/OS/GoogleDrive/fuse-3.2.6/build/test, inifile: pytest.ini
collecting 0 items / 1 errors                                                                                                               
========================================================== short test summary info ==========================================================
ERROR test/test_ctests.py
================================================================== ERRORS ===================================================================
______________________________________________________ ERROR collecting test_ctests.py ______________________________________________________
test/test_ctests.py:19: in <module>
    pytestmark = fuse_test_marker()
test/util.py:116: in fuse_test_marker
    universal_newlines=True) as which:
E   AttributeError: __exit__
========================================================== 1 error in 0.09 seconds ==========================================================

**Comment by Nikratio** [comment]
Thanks for the report! You need to run `python3 -m pytest`, not `python -m pytest`.
