### ISSUE TITLE
error when run pdg-config is not found meson to build libfuse on ubuntu 18.04.1

### ISSUE THREAD

**Issue by bingbing8** [libfuse/libfuse#312]
Here is what I did:
0. host an Ubuntu 18.04.1 from https://www.ubuntu.com/download/desktop
1. install meson by "sudo apt-get install meson"
2. install by "sudo apt-get install ninja-build"
3. install gcc by "sudo apt-get install build-essential"
4. download latest libfuse by "wget https://github.com/libfuse/libfuse/releases/download/fuse-3.2.6/fuse-3.2.6.tar.xz"
5. Extract it by "tar -xf fuse-3.2.6.tar.xz"
6. cd  fuse-3.2.6
7. meson ..

got 2 errors:
Checing whether type "Struct stat" has member "st_atimespc": NO
...
Message: compiler warns about unused result even when casting to void
...
Found pkg-confg: NP

**Comment by Nikratio** [comment]
Thanks for the report! Could you clarify what the problem is? The messages that you get are informational, not errors.

**Comment by bingbing8** [comment]
the last line is:
util/,eson.build:27:2: ERROR: Pkg-config not found.

Is it an error?

**Comment by Nikratio** [comment]
That is indeed an error. You can fix it by... installing pkg-config :-)

**Comment by bingbing8** [comment]
Can you mention it in the step to build? 
also does this "Checing whether type "Struct stat" has member "st_atimespc": NO" matter?
