### ISSUE TITLE
memory leak in fuse_session_loop_mt() on shutdown.

### ISSUE THREAD

**Issue by ashleypittman** [libfuse/libfuse#313]
_Originally posted by @ashleypittman in https://github.com/libfuse/libfuse/commit/161983e2416bc6e26bbbe89664fff62c48c70858#commitcomment-31008120_

We are seeing valgrind (memcheck) report memory leaks with this change, however master with this change reverted is clean.

Normal execution is fine, however on occasions fuse_session_exit() isn't waking the threads so we send a signal to the thread calling fuse_session_loop_mt() which then calls pthread_cancel() on the worker threads, and the buff is leaked.

**Comment by Nikratio** [comment]
Thanks for the report! Will try to revert or fix in the next release.

**Comment by ashleypittman** [comment]
A plain revert applied without conflict and fixed the issue for me.
