### ISSUE TITLE
Callback after mount point mounted

### ISSUE THREAD

**Issue by wm8120** [libfuse/libfuse#315]
In a current project, I launch fuse daemon in a thread of main process and specify the foreground mode (i.e. "-f") . The target mount point can be successfully mounted. The issue is I hope fuse could trigger a callback (or other synchronization methods) after the mount point has been mounted. The callback could be customized, such as setting one flag. When main thread detecting this flag, it knows the mount successes and it can do further actions. Is there such mechanism in libfuse? Thanks.

**Comment by Nikratio** [comment]
Sounds like you are looking for init(), http://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html#ab6fa0b9edb5b002cd1502c969c887329
