### ISSUE TITLE
ACL does not support by libfuse?

### ISSUE THREAD

**Issue by mehran1371** [libfuse/libfuse#317]
With special salutes and thanks for your incredible package
I'm trying to mount a directory by using `pyfuse` in Python (both 2 and 3 version) but the problem is I think `libfuse` actually does not support acl at all, am I right?
I have tested the mounted directory with this command: `setfacl -m "u:root:wrx" mountpoint`
Then I got this error message: `"setfacl: mountpoint/: Operation not supported"`

Libraries version:
OS: Ubuntu Server 16.04
Kernel: Linux_4.15
Libfuse: libfuse-3.2.6

Any suggestions?

**Comment by mehran1371** [comment]
@vplugaru 
@Nikratio

**Comment by jpandre** [comment]
> setfacl -m "u:root:wrx mountpoint"

Bad syntax, should be :
setfacl -m "u:root:wrx" mountpoint

AFAIK the Posix ACLs are supported by libfuse... provided the mounted file system (and language bindings) supports storing the extended attributes. 
Also remember that "mountpoint" means a different thing after a file system is mounted.

**Comment by mehran1371** [comment]
thanks for your response, @jpandre 
but no problem in syntax, command updated to `setfacl -m "u:root:wrx" mountpoint`

**Comment by Nikratio** [comment]
Closing, since this is now being discussed on the mailing list.
