### ISSUE TITLE
Concurrency of single file

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#318]
Kernel version:4.4
libfuse:3.2.6

- I use libfuse to create a simple file system that contains a file with permissions to read and write. When I use custom method validation, it is single-threaded. What is the reason for this?

- The mount command is as follows：
#mount
http://oos-fj2.ctyunapi.cn/roay100g/ on /root/roay/fileDir type fuse.s3backer (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=1048576)
#pwd
/root/roay/fileDir
#ll
total 65536
-rw------- 1 root root 1073741824 Nov  9 18:07 file
-r--r--r-- 1 root root       1709 Nov  9 18:27 stats

**Comment by Nikratio** [comment]
I don't fully understand with "When I use custom method validation, it is single-threaded." - but based on your second message I assume you solved the problem. Feel free to reopen if I misunderstood (but in that case please give specific steps to reproduce the problem with one of the example filesystems).

**Comment by Roay** [comment]
I haven't solved the problem yet.
