### ISSUE TITLE
example/passthrough_ll misses NULL mountpoint check and crashes

### ISSUE THREAD

**Issue by tkhai** [libfuse/libfuse#319]
$~/libfuse$ build/example/passthrough_ll
Segmentation fault

$gdb  build/example/passthrough_ll
...
Program received signal SIGSEGV, Segmentation fault.
__rawmemchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:61
61	../sysdeps/x86_64/multiarch/memchr-avx2.S: No such file or directory.
(gdb) bt
#0  __rawmemchr_avx2 () at ../sysdeps/x86_64/multiarch/memchr-avx2.S:61
#1  0x00007ffff7def342 in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffdca0, ptr=ptr@entry=0x0, size=size@entry=0, 
    pstart=pstart@entry=0x0) at strops.c:41
#2  0x00007ffff7ddd82d in __GI___isoc99_vsscanf (string=0x0, format=0x7ffff7fb37c3 "/dev/fd/%u%n", args=args@entry=0x7fffffffddd0)
    at isoc99_vsscanf.c:41
#3  0x00007ffff7ddd794 in __isoc99_sscanf (s=s@entry=0x0, format=format@entry=0x7ffff7fb37c3 "/dev/fd/%u%n") at isoc99_sscanf.c:31
#4  0x00007ffff7faf800 in fuse_mnt_parse_fuse_fd (mountpoint=mountpoint@entry=0x0) at ../lib/mount_util.c:361
#5  0x00007ffff7fa65f5 in fuse_session_mount (se=0x55555555d460, mountpoint=0x0) at ../lib/fuse_lowlevel.c:2901
#6  0x000055555555671b in main (argc=<optimized out>, argv=0x7fffffffe168) at ../example/passthrough_ll.c:1240

HEAD commit is 3e2fcf3a630e575bc420df254525834504dc01b7

**Comment by Nikratio** [comment]
Thanks for the report!
