### ISSUE TITLE
Concurrency of single file

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#320]
#318 
I haven't solved the problem yet.
The reproducing steps are as follows:
- Create a file system through libfuse 3.2.6,  sleep for 4 seconds in the write method of “struct fuse_operations”. The file system is mounted in the /root/test/fileDir directory.
- Write a file with size of 1G.
[root@test ~]# ll -h /root/test/fileDir/
-rw------- 1 root root 1.0G Nov 10 09:35 file
- Create two threads and run at the same time.
First:  dd if=/dev/zero of=/root/test/fileDir/file  bs=4k seek=100  count=10
The second: dd if=/dev/zero of=/root/test/fileDir/file  bs=4k seek=220  count=10
- The results: after a written request is completed, the next request will begin.
# Why can't it be executed concurrently?

**Comment by Roay** [comment]
I tracked the libfuse source code and found that threads were blocked.
Only one thread could get IO requests from /dev/fuse.

- fuse_loop_mt.c>>>fuse_do_work()>>>res = fuse_session_receive_buf_int(mt->se, &w->fbuf, w->ch);

- fuse_lowlevel.c>>>fuse_session_receive_buf_int()>>>res = read(ch ? ch->fd : se->fd, buf->mem, se->bufsize);
**Can't multiple threads get IO requests concurrently?**

**Comment by Nikratio** [comment]
Do you have writeback caching enabled? If not, then the kernel will automatically serialize write requests for the same inode. 

The call to `receive_buf_int` can be executed by many threads in parallel. You can easily test that by having a second thread write to a different file.

(In the future, please simply re-open the original issue if you believe it hasn't been solved instead of creating a new one. Thanks!)

**Comment by Nikratio** [comment]
You'd clock on the "re-open and comment" button. But to be honest, I don't see this going anywhere. I don't believe there is an actual problem, and I have real trouble following your messages. I do not have the impression that you truly read my previous reply.

**Comment by Roay** [comment]
When I enabled writeback caching, I used a DD command test for a file. The results are as follows：

- dd if=/dev/zero of=/root/test/fileDir/file oflag=direct bs=1M count=1
the result: A total of 8 requests are executed at the same time, each request size of 128K.
- dd if=/dev/zero of=/root/test/fileDir/file oflag=direct bs=4k count=4
the result: Four requests are executed sequentially, and each request size is 4K instead of 16K.

### Can fuse only split bigger writes(eg. 1M) into small writes(eg. 128k), but can't merge small writes(eg. 4k) into bigger writes(eg. 128k)?
My English is not good, please understand.☺☺☺

**Comment by Nikratio** [comment]
It can if you enable writeback caching and do not use direct_io. However, there is a hard limit on the maximum size (currently 128kb I believe).

**Comment by Roay** [comment]
You mean DD doesn't use direct_io?

**Comment by Nikratio** [comment]
I mean you should not tell dd to use direct io, omit the `oflags=direct`

**Comment by Roay** [comment]
I use "dd if=/dev/zero of=/root/test/fileDir/file  bs=4k count=3", there is no merger request.
the result:
open flags: 0x8201 /file 
   open[0] flags: 0x8201 /file 
   unique: 137, success, outsize: 32
unique: 138, opcode: WRITE (16), nodeid: 2, insize: 4176, pid: 11977
**write[0] 4096 bytes to 0 flags**: 0x8001
   write[0] 4096 bytes to 0
   unique: 138, success, outsize: 24
unique: 139, opcode: WRITE (16), nodeid: 2, insize: 4176, pid: 11977
**write[0] 4096 bytes to 4096** flags: 0x8001
   write[0] 4096 bytes to 4096
   unique: 139, success, outsize: 24
unique: 140, opcode: WRITE (16), nodeid: 2, insize: 4176, pid: 11977
**write[0] 4096 bytes to 8192** flags: 0x8001
   write[0] 4096 bytes to 8192
   unique: 140, success, outsize: 24
unique: 141, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0
   unique: 141, success, outsize: 16

**Comment by Roay** [comment]
#define FUSE_USE_VERSION 31

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <assert.h>
#include <unistd.h>
#include <fuse3/fuse.h>
#include <fuse3/fuse_common.h>

static struct options {
    const char                  *filename;
    const char                  *contents;
    uid_t                       uid;
    gid_t                       gid;
    u_int                       block_size;
    off_t                       num_blocks;
    int                         file_mode;
} options;

static void *hello_init(struct fuse_conn_info *conn,
            struct fuse_config *cfg)
{
    struct fuse_args fuseArg;
    struct fuse_conn_info_opts *opts;

    memset(&fuseArg, 0, sizeof(fuseArg));
    fuse_opt_insert_arg(&fuseArg, 0, "-ono_async_dio");
    fuse_opt_insert_arg(&fuseArg, 1, "-omax_write=4096");
    fuse_opt_insert_arg(&fuseArg, 2, "-owriteback_cache");
    fuse_opt_insert_arg(&fuseArg, 3, "-osplice_move");
    opts = fuse_parse_conn_info_opts(&fuseArg);

    if ((conn = calloc(1, sizeof(struct fuse_conn_info))) == NULL)
        return NULL;
    fuse_apply_conn_info_opts(opts, conn);

    cfg->kernel_cache = 1;
    return NULL;
}

static int hello_getattr(const char *path, struct stat *stbuf,
             struct fuse_file_info *fi)
{
    memset(stbuf, 0, sizeof(*stbuf));
    if (strcmp(path, "/") == 0) {
        stbuf->st_mode = S_IFDIR | 0755;
        stbuf->st_nlink = 2;
        stbuf->st_ino = 1;
        stbuf->st_uid = getuid();
        stbuf->st_gid = getuid();
        stbuf->st_atime = time(NULL);
        stbuf->st_mtime = time(NULL);
        stbuf->st_ctime = time(NULL);
        return 0;
    }
    if (*path == '/' && strcmp(path + 1, options.filename) == 0) {
        stbuf->st_mode = S_IFREG | options.file_mode;
        stbuf->st_nlink = 1;
        stbuf->st_ino = 2;
        stbuf->st_uid = getuid();
        stbuf->st_gid = getuid();
        stbuf->st_size = options.num_blocks * options.block_size;
        stbuf->st_blksize = options.block_size;
        stbuf->st_blocks = options.num_blocks;
        return 0;
    }

    return -ENOENT;
}

static int hello_readdir(const char *path, void *buf, fuse_fill_dir_t filler,
             off_t offset, struct fuse_file_info *fi,
             enum fuse_readdir_flags flags)
{
    if (strcmp(path, "/") != 0)
        return -ENOENT;
    if (filler(buf, ".", NULL, 0, 0) != 0)
        return -ENOMEM;
    if (filler(buf, "..", NULL, 0, 0) != 0)
        return -ENOMEM;
    if (filler(buf, options.filename, NULL, 0, 0) != 0)
        return -ENOMEM;
    return 0;
}

static int hello_open(const char *path, struct fuse_file_info *fi)
{
    if (*path == '/' && strcmp(path + 1, options.filename) == 0) {
        fi->fh = 0;
        fi->direct_io = 0;
        return 0;
    }
    return -ENOENT;
}

static int hello_read(const char *path, char *buf, size_t size, off_t offset,
              struct fuse_file_info *fi)
{
    size_t len;
    (void) fi;

    if((strcmp(path+1, options.filename) != 0))
        return -ENOENT;

    len = strlen(options.contents);

    printf("hello_read begin offset=0x%jx size=0x%jx len=%lu\n", (uintmax_t)offset, (uintmax_t)size, len);

    if (offset < len) {
        if (offset + size > len)
            size = len - offset;
        memcpy(buf, options.contents + offset, size);
    } else
        size = 0;
    printf("hello_read end offset=0x%jx size=0x%jx\n", (uintmax_t)offset, (uintmax_t)size);
    return size;
}
static int hello_write(const char *path, const char *buf, size_t size,
    off_t offset, struct fuse_file_info *fi)
{
    printf("hello_write begin offset=0x%jx size=0x%jx\n", (uintmax_t)offset, (uintmax_t)size);
    if (size == 0)
        return 0;
    sleep(5);
    printf("hello_write end offset=0x%jx size=0x%jx\n",(uintmax_t)offset, (uintmax_t)size);
    return size;
}

static int
hello_statfs(const char *path, struct statvfs *st)
{
    st->f_bsize = options.block_size;
    st->f_frsize = options.block_size;
    st->f_blocks = options.num_blocks;
    st->f_bfree = 0;
    st->f_bavail = 0;
    st->f_files = 3;
    st->f_ffree = 0;
    st->f_favail = 0;
    return 0;
}

static struct fuse_operations hello_oper = {
    .init       = hello_init,
    .getattr    = hello_getattr,
    .readdir    = hello_readdir,
    .open        = hello_open,
    .read        = hello_read,
    .write      = hello_write,
    .statfs     = hello_statfs,
};


int main(int argc, char *argv[])
{
    options.filename = strdup("hello");
    options.contents = strdup("Hello World!\n");
    options.block_size = 8192;
    options.file_mode = 0600;
    options.gid = getuid();
    options.uid = getuid();
    options.num_blocks = 131072;

    return fuse_main(argc, argv, &hello_oper, NULL);
}

**Comment by Roay** [comment]
My code is as follows:

#define FUSE_USE_VERSION 31

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <assert.h>
#include <unistd.h>
#include <fuse3/fuse.h>
#include <fuse3/fuse_common.h>

static struct options {
    const char                  *filename;
    const char                  *contents;
    uid_t                       uid;
    gid_t                       gid;
    u_int                       block_size;
    off_t                       num_blocks;
    int                         file_mode;
} options;

static void *hello_init(struct fuse_conn_info *conn,
            struct fuse_config *cfg)
{
    struct fuse_args fuseArg;
    struct fuse_conn_info_opts *opts;

    memset(&fuseArg, 0, sizeof(fuseArg));
    fuse_opt_insert_arg(&fuseArg, 0, "-ono_async_dio");
    fuse_opt_insert_arg(&fuseArg, 1, "-omax_write=4096");
    fuse_opt_insert_arg(&fuseArg, 2, "-owriteback_cache");
    fuse_opt_insert_arg(&fuseArg, 3, "-osplice_move");
    opts = fuse_parse_conn_info_opts(&fuseArg);

    if ((conn = calloc(1, sizeof(struct fuse_conn_info))) == NULL)
        return NULL;
    fuse_apply_conn_info_opts(opts, conn);

    cfg->kernel_cache = 1;
    return NULL;
}

static int hello_getattr(const char *path, struct stat *stbuf,
             struct fuse_file_info *fi)
{
    memset(stbuf, 0, sizeof(*stbuf));
    if (strcmp(path, "/") == 0) {
        stbuf->st_mode = S_IFDIR | 0755;
        stbuf->st_nlink = 2;
        stbuf->st_ino = 1;
        stbuf->st_uid = getuid();
        stbuf->st_gid = getuid();
        stbuf->st_atime = time(NULL);
        stbuf->st_mtime = time(NULL);
        stbuf->st_ctime = time(NULL);
        return 0;
    }
    if (*path == '/' && strcmp(path + 1, options.filename) == 0) {
        stbuf->st_mode = S_IFREG | options.file_mode;
        stbuf->st_nlink = 1;
        stbuf->st_ino = 2;
        stbuf->st_uid = getuid();
        stbuf->st_gid = getuid();
        stbuf->st_size = options.num_blocks * options.block_size;
        stbuf->st_blksize = options.block_size;
        stbuf->st_blocks = options.num_blocks;
        return 0;
    }

    return -ENOENT;
}

static int hello_readdir(const char *path, void *buf, fuse_fill_dir_t filler,
             off_t offset, struct fuse_file_info *fi,
             enum fuse_readdir_flags flags)
{
    if (strcmp(path, "/") != 0)
        return -ENOENT;
    if (filler(buf, ".", NULL, 0, 0) != 0)
        return -ENOMEM;
    if (filler(buf, "..", NULL, 0, 0) != 0)
        return -ENOMEM;
    if (filler(buf, options.filename, NULL, 0, 0) != 0)
        return -ENOMEM;
    return 0;
}

static int hello_open(const char *path, struct fuse_file_info *fi)
{
    if (*path == '/' && strcmp(path + 1, options.filename) == 0) {
        fi->fh = 0;
        fi->direct_io = 0;
        return 0;
    }
    return -ENOENT;
}

static int hello_read(const char *path, char *buf, size_t size, off_t offset,
              struct fuse_file_info *fi)
{
    size_t len;
    (void) fi;

    if((strcmp(path+1, options.filename) != 0))
        return -ENOENT;

    len = strlen(options.contents);

    printf("hello_read begin offset=0x%jx size=0x%jx len=%lu\n", (uintmax_t)offset, (uintmax_t)size, len);

    if (offset < len) {
        if (offset + size > len)
            size = len - offset;
        memcpy(buf, options.contents + offset, size);
    } else
        size = 0;
    printf("hello_read end offset=0x%jx size=0x%jx\n", (uintmax_t)offset, (uintmax_t)size);
    return size;
}
static int hello_write(const char *path, const char *buf, size_t size,
    off_t offset, struct fuse_file_info *fi)
{
    printf("hello_write begin offset=0x%jx size=0x%jx\n", (uintmax_t)offset, (uintmax_t)size);
    if (size == 0)
        return 0;
    sleep(5);
    printf("hello_write end offset=0x%jx size=0x%jx\n",(uintmax_t)offset, (uintmax_t)size);
    return size;
}

static int
hello_statfs(const char *path, struct statvfs *st)
{
    st->f_bsize = options.block_size;
    st->f_frsize = options.block_size;
    st->f_blocks = options.num_blocks;
    st->f_bfree = 0;
    st->f_bavail = 0;
    st->f_files = 3;
    st->f_ffree = 0;
    st->f_favail = 0;
    return 0;
}

static struct fuse_operations hello_oper = {
    .init       = hello_init,
    .getattr    = hello_getattr,
    .readdir    = hello_readdir,
    .open        = hello_open,
    .read        = hello_read,
    .write      = hello_write,
    .statfs     = hello_statfs,
};


int main(int argc, char *argv[])
{
    options.filename = strdup("hello");
    options.contents = strdup("Hello World!\n");
    options.block_size = 8192;
    options.file_mode = 0600;
    options.gid = getuid();
    options.uid = getuid();
    options.num_blocks = 131072;

    return fuse_main(argc, argv, &hello_oper, NULL);
}

**Comment by Nikratio** [comment]
What about "you need to enable writeback caching" is unclear? I really don't know how else to express it.
