### ISSUE TITLE
dereferencing typecasted pointer inside cusexmp_ioctl ignored

### ISSUE THREAD

**Issue by akshitkanda5** [libfuse/libfuse#329]
Hi,
I am trying to pass in an address of a struct to an ioctl call in cusexmp_ioctl.
I get the correct value of the address inside the call. However, when I try to typecast and dereference the pointer to one of the members of the struct, and print it with something like
struct mystruct data= *((struct mystruct*)(arg));
(printf"no of bytes read are %d\n", data.nBytes);  // nBytes being the member of the struct
The whole statement is ignored and not printed, no segfault/anamalous behavior occurs. Printing just the value of the pointer allows the statement to be printed. Apparently, dereferencing the pointer causes all the subsequent prints to fail.
This is really baffling to me.
Kindly help

**Comment by Nikratio** [comment]
The address refers to memory in the process that issued the ioctl. The filesystem process has its own address space. Resolving the pointer in a different address space gives non-sensical results.

**Comment by akshitkanda5** [comment]
Thanks for the quick response.
Does a copy_to/from_user works for getting the data pointed to by the
pointer?

Regards,
Akshit
