### ISSUE TITLE
Missing OPENAFS magic number in whitelist

### ISSUE THREAD

**Issue by aarnolds** [libfuse/libfuse#336]
Dear fuse developers,

in newer fuse releases a whitelist was introduced to check magic numbers of filesystems. The magic number of openafs file systems 0x5346414f is not recognized yet unfortunately. Would it be possible to add this in the 2.9 and 3.3 branches?

Thanks a lot, kind regards and happy holidays

Ado Arnolds

```
diff -ur fuse-2.9.8.orig/util/fusermount.c fuse-2.9.8/util/fusermount.c
--- fuse-2.9.8.orig/util/fusermount.c   2018-07-24 09:00:41.000000000 +0200
+++ fuse-2.9.8/util/fusermount.c        2018-12-18 14:48:26.086199870 +0100
@@ -1028,6 +1028,7 @@
         * the ecryptfs mount helper
         * (https://bazaar.launchpad.net/~ecryptfs/ecryptfs/trunk/view/head:/src/utils/mount.ecryptfs_private.c#L225). */
        typeof(fs_buf.f_type) f_type_whitelist[] = {
+               0x5346414f /* OPENAFS_SUPER_MAGIC */,
                0x61756673 /* AUFS_SUPER_MAGIC */,
                0x9123683E /* BTRFS_SUPER_MAGIC */,
                0x00C36400 /* CEPH_SUPER_MAGIC */,
```

**Comment by Nikratio** [comment]
I believe this has already been fixed: https://github.com/libfuse/libfuse/blob/master/util/fusermount.c#L1013

**Comment by aarnolds** [comment]
Dear Nikratio,

unfortunately it's not fixed by the release you mentioned (and not in 3.4.1). The magic number 0x5346414f for the openafs file system is still not in f_type_whitelist. Would be great to have it there.

Thanks and have a happy and healthy new year.

Ado Arnolds

**Comment by Nikratio** [comment]
Sorry, the diff in your original message did not render correctly.

**Comment by aarnolds** [comment]
Thanks a lot & have a nice weekend!
