### ISSUE TITLE
Clarify constraints for calling fuse_lowlevel_notify_*

### ISSUE THREAD

**Issue by Vogtinator** [libfuse/libfuse#341]
fuse_lowlevel_notify_inval_entry says:

```
 * To avoid a deadlock this function must not be called while
 * executing a related filesytem operation or while holding a lock
 * that could be needed to execute such an operation. As of kernel
 * 4.18, a "related operation" is a lookup(), symlink(), mknod(),
 * mkdir(), unlink(), rename(), link() or create() request for the
 * parent, and a setattr(), unlink(), rmdir(), rename(), setxattr(),
 * removexattr(), readdir() or readdirplus() request for the inode
 * itself.
```

At which point is a filesystem operation considered to be executing?
AFAIU it happens once the kernel placed a request into the /dev/fuse buffer, but if that is the case, it's impossible to call this reliably as it's possible that the kernel sends such a request/starts an operation while this funcion is being called.

**Comment by Nikratio** [comment]
Thanks for the report! I hope the above fix answers your question. In short, it is not about things happening at the same time but within the same code path. Please feel free to ask on the mailing list for further clarification (https://lists.sourceforge.net/lists/listinfo/fuse-devel).
