### ISSUE TITLE
How to handle lowlevel setattr failing partially?

### ISSUE THREAD

**Issue by Vogtinator** [libfuse/libfuse#342]
If writeback caching is enabled, the kernel sends a single setattr request with `FUSE_SET_ATTR_MTIME | FUSE_SET_ATTR_MTIME_NOW | FUSE_SET_ATTR_ATIME | FUSE_SET_ATTR_ATIME_NOW | FUSE_SET_ATTR_CTIME | FUSE_SET_ATTR_SIZE` for truncation.

If one of those operations fails, e.g. mtime changing fails after truncating the file, `fuse_reply_err` is called, which does not update the file's st_size in the kernel cache.

I think libfuse's own fuse_lib_setattr hits the same issue.

Is the filesystem supposed to do this operation atomically, i.e. if changing the size fails, revert the time changes?

In my filesystem implementation I'm doing all of the operations async (and in no specific order) and to deal with this I'm doing effectively

```
fuse_reply_err(req, EIO);
// Some part of the operation might've succeeded though, inform the kernel about that
fuse_lowlevel_notify_inval_entry(...);
```

which I don't think is the correct/best way to handle it and might even lead to a deadlock (https://github.com/libfuse/libfuse/issues/341)

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

As for your question: yes, I think the best solution is to make the operation either fail completely or succeed completely.

**Comment by Vogtinator** [comment]
> I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Ok, so should I also mention this on fuse-devel?

> I think libfuse's own fuse_lib_setattr hits the same issue.

**Comment by Vogtinator** [comment]
> As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Sure, I just subscribed and will try to start a thread there.

Note that I ended up here because basically every resource redirects to here on GitHub and Sourceforce appears to be entirely unused ("The FUSE project has moved to https://github.com/libfuse/").

Could this be made more visible?

**Comment by Rondom** [comment]
I think, one could abuse issue templates for this. The template for questions/discussion should simply state not to file an issue but use the list for discussion instead. The one for features could state @Nikratio's stance on "features that nobody plans to work on" as well.

https://help.github.com/articles/creating-issue-templates-for-your-repository/

@Nikratio What do you think?

**Comment by Nikratio** [comment]
Yeah, using an issue template would be an option. But this doesn't happen too often, so I don't mind copy & pasting the occasional boilerplate response.

**Comment by Rondom** [comment]
Good, if I was you, I certainly would be. :-)

Thanks for your work on libfuse. It is appreciated.
