### ISSUE TITLE
Strange link issue - had to add to fuse_versionscript

### ISSUE THREAD

**Issue by Smit-tay** [libfuse/libfuse#348]
For some reason I was getting this build error message when building test_write_cache

//FUSE/libfuse/lib/mount.c|491|undefined reference to `fuse_mnt_resolve_path'|

for the following functions:

fuse_mnt_resolve_path;
fuse_mnt_add_mount;
fuse_mnt_check_fuseblk;
fuse_mnt_umount;

I noticed these functions were missing from fuse_version_script - and, having tried everything else I could think of, I added them to the FUSE_3.0 global block.  This appears to solve the issue, but, I don't understand why I would have to do that.

Any help greatly appreciated.

**Comment by Nikratio** [comment]
Thanks for the report! These functions are not used by test_write_cache.c, and the build works fine both for me, on Travis, and various distribution buildds. So I am hesitant to change this to make it work on an unknown system for unknown reasons. Hope you understand!
