### ISSUE TITLE
util/meson.build:19:2: ERROR:  Dependency "udev" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by heppytt** [libfuse/libfuse#350]
util/meson.build:19:2: ERROR:  Dependency "udev" not found, tried pkgconfig and cmake

![image](https://user-images.githubusercontent.com/17058423/51966186-c2a0cd00-24a6-11e9-801d-b60c20eeebb8.png)

**Comment by Smit-tay** [comment]
You should have a file: /usr/share/pkgconfig/udev.pc

In *most* Ubuntu versions this is provided via package "udev" (at least as far as Ii can tell)

systemd based systems (modern RedHat based) provide this via systemd.
