### ISSUE TITLE
FreeBSD 12.0 - Setattr being called when a file is opened read only

### ISSUE THREAD

**Issue by animosity22** [libfuse/libfuse#358]
I am using rclone and using the default fuse on FreeBSD 12.0. When I try to mediainfo or play a file, for some reason it's trying to set the size of the file instead of opening it just read only.

```
2019/02/08 12:30:12 DEBUG : Radarr_Movies/Unsane (2018)/Unsane (2018).mkv: Setattr: a=Setattr [ID=0x3b Node=0x4 Uid=0 Gid=0 Pid=1535] size=25938409160 handle=INVALID-0x0
```

There is a post here as well that goes through it a bit more and the testing:

https://forum.rclone.org/t/freebsd-question/8662/14

I'm using a test VM with FreebSD 12.0 current and just installing fuse / fusefs-libs to compile and test the issue.

**Comment by animosity22** [comment]
The full truss log is here.

[mediatruss.log](https://github.com/libfuse/libfuse/files/2857061/mediatruss.log)

**Comment by Nikratio** [comment]
Do you have writeback caching enabled?

**Comment by animosity22** [comment]
Is there a specific flag that would enable it? The only fuse option I've enabled is sync_read and left everything else at defaults. If there is a flag to pass to turn that off, I can definitely test it.

**Comment by Nikratio** [comment]
http://libfuse.github.io/doxygen/fuse__common_8h.html#a4839fce31097f4b4da7a1f01169228fa

**Comment by animosity22** [comment]
That doesn't help me unfortunately. I'm using the stock packages with FreeBSD 12 and installing fuse via the pkg install fuse commands.

I don't see how to check anything based on that link.

**Comment by Nikratio** [comment]
You'd have to look into the rclone source code (that is the filesystem that is using libfuse, right?). If you're not familiar with rclone, I'd suggest reporting this issue against rclone rather than libfuse - the problem might well be there and without more information there is little that we can do on the libfuse side.

**Comment by trapexit** [comment]
rclone is written in Go and AFAIK uses bazil.org/fuse. Not libfuse.

**Comment by animosity22** [comment]
I've got it compiled using the local fuse library on FreeBSD and not the rclone one as @ncw wanted to rule out it was a rclone issue and suggested it looked like more of a fuse issue since we aren't using the rclone fuse.

**Comment by animosity22** [comment]
his comments:

![image](https://user-images.githubusercontent.com/5088712/52669777-00f5ad80-2ee5-11e9-8637-74efe5d1e65f.png)

**Comment by Nikratio** [comment]
What he refers to is the FreeBSD FUSE kernel module, not libfuse :-). libfuse is not creating any requests, it just forwards what it receives from the kernel.

**Comment by animosity22** [comment]
Much appreciated as I wasn't sure if this was the right spot or not.

Thanks!
