### ISSUE TITLE
cuse: device not found, try modprobe cuse first

### ISSUE THREAD

**Issue by akshitkanda5** [libfuse/libfuse#364]
I am trying to create a device node using cuse on a 32 bit system but getting the above mentioned error. However, it works perfectly fine on 64 bit systems.
Upon investigation, I see that there isn't a /dev/cuse pre-installed on the 32 bit system.
Do I need to update the fuse package for that?
Or is it something else?

**Comment by Nikratio** [comment]
Thanks for the report! On modern systems, the libfuse package isn't responsible for creating the device nodes. This should be done by udev or the kernel (there is some legacy code for creating /dev/fuse, but I see no reason to do something similar for /dev/cuse).
