### ISSUE TITLE
Enables writeback cache but performance not improved

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#366]
Enables writeback cache but the performance is not improved.

linux kernel: 4.4
libfuse: 3.3.0

Reproduce:
`./passthrough_ll -o writeback /mnt/`

Is this a problem with the FUSE Linux kernel module，If so, how to solve it?

**Comment by trapexit** [comment]
You need to provide more information. What tests did you use? AFAIK if the writes are large enough they won't be cached so you wouldn't see an improvement. It'd need to be smaller (like a single page).

**Comment by Roay** [comment]
Testing with FIO：

> fio -filename=bigFile -direct=1 -iodepth 1 -thread -rw=write -ioengine=libaio -bs=4k -size=25G -numjobs=1 -runtime=180 -time_based -group_reporting -name=test

**Comment by Nikratio** [comment]
Try using `dd` instead, I'm not sure what `fio` does exactly (and I'm particularly suspicious of the effects of `ioengine=libaio`).

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
