### ISSUE TITLE
Make fuse_main() more powerful

### ISSUE THREAD

**Issue by vxgmichel** [libfuse/libfuse#382]
I ran into some signal issues while running separate fuse instances in different threads. That's because the binding I'm using, [fusepy](https://github.com/fusepy/fusepy), relies mainly on the `fuse_main_real` function to run a fuse instance. The problem is that the `fuse_main` function calls the `fuse_set_signal_handlers` function which is not meant to be used in a multi-threaded environment.

More precisely, the symptoms are:
-  Only the first instance is stopped on a `SIGTERM`, `SIGINT` or `SIGHUP` signal.
   -> This is not really a big deal since setting a custom handler prevents libfuse from setting its own (python already does that for `SIGINT` actually, so only `SIGTERM` and `SIGHUP` require a special treatment)
- The following message gets printed to `stderr`:
   `fuse: fuse_remove_signal_handlers: unknown session`
   It will be printed at the cleanup of every instance, except for the newest. 
   -> This is a minor issue but still annoying.

These symptoms can easily be reproduced with [this python gist](https://gist.github.com/vxgmichel/fdaa49066937d56687ad174185fc4411). Now I understand that `fuse_main` is merely a helper on top of a larger API, but I suspect it would be quite some work to add and maintain access to lower-level functions in a binding like fusepy. So some solutions on the libfuse side might be:
- Add an extra option to disable signal handlers (like `foreground` and `singlethread`)
- Do not set the signal handlers outside of the main thread (which makes sense but also break backward compatibility in some sense)

Or maybe I missed a simpler solution or workaround :)

**Comment by Nikratio** [comment]
Thanks for the report! I don't think that not using fuse_main_real() is a big hurdle - it is actually intended only for very simple filesystems like the examples that ship with libfuse. Making it more powerful would send the wrong signal, so I'd rather not make changes like that. That said, if there are things we can improve to make *not* using it less painful, I'd be happy to consider them.

Makes sense?

**Comment by vxgmichel** [comment]
> I don't think that not using fuse_main_real() is a big hurdle - it is actually intended only for very simple filesystems like the examples that ship with libfuse. Making it more powerful would send the wrong signal, so I'd rather not make changes like that.

Haha that was the answer I feared :) Anyway I wanted to let you know that apart from those signal issues, `fuse_main` works fine in a multi-instance multi-threaded environment, so maybe it's something to consider in the future.

> That said, if there are things we can improve to make not using it less painful, I'd be happy to consider them.

I'm not sure there's much libfuse can do about this. A proper approach would be to ask the fusepy maintainers to expose and maintain the following items:

    struct fuse
    struct fuse_args
    struct fuse_loop_config
    fuse_new
    fuse_mount
    fuse_daemonize
    fuse_loop 
    fuse_loop_mt 
    fuse_unmount
    fuse_destroy

It would also mean re-implementing some option management logic (at the moment fusepy blindly propagates any provided options to `fuse_main`). So that is quite a bit of work for very little gain.

I think I'll simpy use the workaround described earlier (setting custom signal handlers). I did not find a way to workaround the stderr message though.

**Comment by Nikratio** [comment]
Alright, thanks for letting me know.
