### ISSUE TITLE
Dropping privileges

### ISSUE THREAD

**Issue by wland32** [libfuse/libfuse#385]
fusermount is installed setuid root, however unlike many other suid applications it does not seem to drop its permissions permanently.
Therefore my question is, why is is not dropping permissions for good or why is this not possible in case of fusermount.

**Comment by Nikratio** [comment]
Thanks for the report! fusermount does something even better: as soon as it no longer needs the permissions, it exits completely :-). It's only point is to carry out an action that requires root privileges, afterwards there is nothing left to do.
