### ISSUE TITLE
unlock_path  coredump

### ISSUE THREAD

**Issue by YorkTsai2012** [libfuse/libfuse#386]
Hi   @Nikratio   

Recently our project hits a fuse coredump, related to 
https://sourceforge.net/p/fuse/mailman/message/30256786/ 

the second time

![image](https://user-images.githubusercontent.com/2317749/54423586-f3ce1780-474b-11e9-8a93-eae48320a4d0.png)

the first time

![image](https://user-images.githubusercontent.com/2317749/54423876-a00ffe00-474c-11e9-80a0-bd31e8364462.png)

the unlock_path() is in  libfuse/lib/fuse.c

the fuse version we use is 2.9.2

Does the higher version fuse have fixed this problem, or maybe it is still hide?

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid I don't know if this has been fixed in newer versions. I'd suggest you install a new version and test it. If it still happens with the most recent version, we can take a closer look.
