### ISSUE TITLE
fuse still manages to fail mounts due to _netdev

### ISSUE THREAD

**Issue by gilbahat** [libfuse/libfuse#390]
Hi,

Using ubuntu xenial (latest as of time of writing) and fuse 2.9.4, I still manage to get this error, even though looking at the code it's supposed to be ignored.

$ sudo mount -a
fuse: unknown option `_netdev'
fuse: unknown option `_netdev'
fuse: unknown option `_netdev'
fuse: unknown option `_netdev'

my fstab:
//snipped
bucket-name-redacted 	/some/path 	s3fs  auto,_netdev,allow_other,ro,uid=1000,gid=1000,iam_role,endpoint=eu-west-1 1 1

$ ls -l /sbin/mount.s3fs
lrwxrwxrwx 1 root root 13 Apr  2 10:11 /sbin/mount.s3fs -> /usr/bin/s3fs

$ dpkg -l | grep fuse
ii  fuse                             2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace
ii  libfuse2:amd64                   2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace (library)

$ dpkg -l | grep s3fs
ii  s3fs                             1.82-1~ubuntu16.04.1~alindt                amd64        FUSE-based file system backed by Amazon S3

this is annoying because the system fails to mount the volumes on startup when I remove this option (possibly some race condition) but sudo mount -a works. I figured _netdev could fix this but then I ran into this error...

**Comment by Nikratio** [comment]
Thanks for the report! S3FS probably does its own option parsing (rather than the one in fuse_main, which skips over netdev) and then passes this option to libfuse.  So this needs to be fixed in S3FS.
