### ISSUE TITLE
Add support for FALLOC_FL_ZERO_RANGE

### ISSUE THREAD

**Issue by bahusvel** [libfuse/libfuse#395]
Currently specifying this mode to fallocate will fail with EOPNOTSUPP from kernel space https://elixir.bootlin.com/linux/v5.0.6/source/fs/fuse/file.c#L2971. Or perhaps there is a reason why this mode is deliberately not supported?

**Comment by Nikratio** [comment]
Thanks for the report!

As far as I can tell, this is a missing feature of the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.

**Comment by rwmjones** [comment]
I posted a kernel patch which should fix this, please test and review it: https://marc.info/?l=linux-fsdevel&m=162081340116485&w=2

**Comment by nh2** [comment]
> I posted a kernel patch

For the record, this was merged:

* https://github.com/torvalds/linux/commit/6b1bdb56b17c25f640261f3b18030cb0a21d7878
* https://github.com/torvalds/linux/commit/59bda8ecee2ffc6a602b7bf2b9e43ca669cdbdcd
