### ISSUE TITLE
Off by one cache padding in fuse_file_info

### ISSUE THREAD

**Issue by bahusvel** [libfuse/libfuse#396]
Padding ```unsigned int padding : 27;``` is one bit too much for the 6 one bit fields above it. Probably not a big deal, but I'm guessing this is not intended, and makes struct fuse_file_info occupy 8 bytes more than it should.

**Comment by Nikratio** [comment]
Thanks for the report! This was indeed not intended - but now that we have it we can't change it for backwards compatibility reasons.
