### ISSUE TITLE
paths are sliced when arriving to FUSE operations 

### ISSUE THREAD

**Issue by shay-sundaysky** [libfuse/libfuse#397]
I have a C based backend application that can only work with local filesystem paths.
In order for my application to work with assets located on the internet, I'm converting urls from this:
https://somethingontheinternet.com/assets/Computer_33200.mp4
to this
/mnt/https/aHR0cHM6Ly9zb21ldGhpbmdvbnRoZWludGVybmV0LmNvbS9hc3NldHMvQ29tcHV0ZXJfMzMyMDAubXA0.mp4
(some base64 encoding manipulation)
this way, my application is "reading" local fs files but my fuse hooks (implemented with fuse-bindings node.js wrapper) are kicking in and converting the local path to the remote path and fetching the item from the internet.
Sometimes i'll run into long urls, for example :-):
https://somethingontheinternet.com/very/very/very/long/path/until/someday/finally/reaching/the/gaddamn/assets/goesonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandonandon/Computer_33200.mp4
the local fs will look like this:
/mnt/https/aHR0cHM6Ly9zb21ldGhpbmdvbnRoZWludGVybmV0LmNvbS92ZXJ5L3ZlcnkvdmVyeS9sb25nL3BhdGgvdW50aWwvc29tZWRheS9maW5hbGx5L3JlYWNoaW5nL3RoZS9nYWRkYW1uL2Fzc2V0cy9nb2Vzb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW/5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbi9Db21wdXRlcl8zMzIwMC5tcDQ.mp4
(a 363 long path)
When this path goes into my hook, it's sliced from after 255 characters:
/mnt/https/aHR0cHM6Ly9zb21ldGhpbmdvbnRoZWludGVybmV0LmNvbS92ZXJ5L3ZlcnkvdmVyeS9sb25nL3BhdGgvdW50aWwvc29tZWRheS9maW5hbGx5L3JlYWNoaW5nL3RoZS9nYWRkYW1uL2Fzc2V0cy9nb2Vzb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFuZG9uYW5kb25hbmRvbmFu
According to my understanding, I have a 4096 chars max path limit in linux, so how come i don;'t have the same limit in my mounted FS? Is there specific mount configuration I need to use to increase path limit?

**Comment by Nikratio** [comment]
Thanks for the report! I'm not aware of any specific configuration needs, and libfuse doesn't impose any limits here. Either this is a problem in the Linux kernel, or it is a problem in the node.js wrapper.
