### ISSUE TITLE
Unable to Mount - Value too large for defined data type

### ISSUE THREAD

**Issue by problemss** [libfuse/libfuse#399]
I am using rclone to mount a fuse file system on my ODROID-HC2 (32 bit armv71 processor running 32-bit Debian [OMV 4]) on a HDD formatted as XFS. I am running it as root right now.

When I run it, I have a failure at the FUSE mount point.

`2019/04/24 21:58:14 mount helper error: fusermount: failed to access mountpoint /srv/dev-disk-by-label-WDred/GD: Value too large for defined data type`

I am asking for help on the rclone forum, but since it appears to be a FUSE issue. I figured I would ask here as well.

**Comment by Nikratio** [comment]
Thanks for the report! Is this with libfuse 2.x or 3.x? In the former case,  the solution is probably to upgrade to libfuse3 (unfortunately the fix cannot be backported because that would break backwards compatibility).

**Comment by problemss** [comment]
@Nikratio I am not sure, but if I get the version of fusermount it is as follows:
`fusermount version: 2.9.7`

**Comment by Nikratio** [comment]
Yeah, that means you may have to ask the rclone developers to update to libfuse 3.x. There's a chance that it might be something else, but without knowing more about rclone I can't really tell.

**Comment by problemss** [comment]
I also tried fuse-zip and received the same error.

I am going to ask a potentially dumb question, I apologize, but when you say libfuse is that the same as fusermount? So fusermount being 2.9.7 is the same as libfuse 2.x? Or is libfuse a package inside rclone or fuse-zip to call fusermount and other apis?

**Comment by problemss** [comment]
So I think I just answered by own question. I see I have the latest Fuse package (2.9.4) and it looks like they have libfuse2 in that package. Is there an easy way to use the new libfuse3 package to see if it helps?

**Comment by problemss** [comment]
It looks like the issue is that the programs are compiled without large file support. They will need to be recompiled with -D FILE_OFFSET_BITS=64. Do you know if that is just libfuse or if that will need to be fuse and rclone? I assume it is just fuse, but not sure.

Looks like it is mentioned at the bottom of this file.
[https://github.com/libfuse/libfuse/blob/master/include/fuse_common.h](https://github.com/libfuse/libfuse/blob/master/include/fuse_common.h)

**Comment by jpandre** [comment]
> It looks like the issue is that the programs are compiled without large file support.
> They will need to be recompiled with -D FILE_OFFSET_BITS=64. 
Hmm. Unlikely, as you would not be able compile an application using libfuse with _FILE_OFFSET_BITS different from 64. This is checked in fuse_common.h (at compile time). Also note the underscore prefix in _FILE_OFFSET_BITS.

**Comment by Rondom** [comment]
rclone is written in Golang I think, so I think the compile-time-check in the libfuse-header-file might not work.
https://github.com/libfuse/libfuse/blob/5fc562c90d7925963467babbb73ae5b4f9fd13f8/include/fuse_common.h#L799-L810

**Comment by Nikratio** [comment]
In that case you're looking at the wrong project, rclone probably uses Gofuse: https://github.com/hanwen/go-fuse
