### ISSUE TITLE
Memory Leak with libfuse 2.9.4/5

### ISSUE THREAD

**Issue by kateagbaw** [libfuse/libfuse#40]
Using Valgrind with libfuse 2.9.4/5 produces the memory leaks below:

==29170== 64 bytes in 1 blocks are still reachable in loss record 433 of 663
==29170==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==29170==    by 0x513CFFA: fuse_chan_new_common (fuse_session.c:151)
==29170==    by 0x51368B0: fuse_kern_chan_new (fuse_kern_chan.c:97)
==29170==    by 0x513E7B8: fuse_mount_common (helper.c:238)
==29170==    by 0x513EAD6: fuse_setup_common (helper.c:284)
==29170==    by 0x513EBF6: fuse_main_common (helper.c:349)
==29170==    by 0x403C86: bfs_main_mount (bfs_main.c:625)
==29170==    by 0x4040E6: main (bfs_main.c:255)

==29170== 72 bytes in 1 blocks are still reachable in loss record 440 of 663
==29170==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==29170==    by 0x513D0D2: fuse_session_new (fuse_session.c:36)
==29170==    by 0x5137A21: fuse_lowlevel_new_common (fuse_lowlevel.c:2750)
==29170==    by 0x5130904: fuse_new_common (fuse.c:4679)
==29170==    by 0x513EB00: fuse_setup_common (helper.c:290)
==29170==    by 0x513EBF6: fuse_main_common (helper.c:349)
==29170==    by 0x403C86: bfs_main_mount (bfs_main.c:625)
==29170==    by 0x4040E6: main (bfs_main.c:255)

==29170== 384 bytes in 1 blocks are still reachable in loss record 554 of 663
==29170==    at 0x4A057BB: calloc (vg_replace_malloc.c:593)
==29170==    by 0x512FA78: fuse_fs_new (fuse.c:4544)
==29170==    by 0x513075C: fuse_new_common (fuse.c:4618)
==29170==    by 0x513EB00: fuse_setup_common (helper.c:290)
==29170==    by 0x513EBF6: fuse_main_common (helper.c:349)
==29170==    by 0x403C86: bfs_main_mount (bfs_main.c:625)
==29170==    by 0x4040E6: main (bfs_main.c:255)

==29170== 65,536 bytes in 1 blocks are still reachable in loss record 656 of  663
==29170==    at 0x4A057BB: calloc (vg_replace_malloc.c:593)
==29170==    by 0x512B73A: node_table_init (fuse.c:4559)
==29170==    by 0x5130955: fuse_new_common (fuse.c:4698)
==29170==    by 0x513EB00: fuse_setup_common (helper.c:290)
==29170==    by 0x513EBF6: fuse_main_common (helper.c:349)
==29170==    by 0x403C86: bfs_main_mount (bfs_main.c:625)
==29170==    by 0x4040E6: main (bfs_main.c:255)

If a fix has already been submitted, please do point me to the fix. Thank you.
Catherine

**Comment by Nikratio** [comment]
With what file system are you getting these errors? Can you reproduce it with one of the examples?

**Comment by kateagbaw** [comment]
We have been able to reproduce these errors using CentOS 7 and RHEL 6.5 x86_64 GNU/Linux
on a file system that is still in development.

Catherine

**Comment by Nikratio** [comment]
Please try to reproduce this with one of the examples, or try to create a minimal example based on your in-development fs. If you can't provide code that triggers the problem, it is very hard to fix it (i.e, I won't bother).

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, with the current state of affairs it's unlikely that anyone is going to be able 
to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Comment by trapexit** [comment]
Where would such reports be kept if not in the issue tracker?

**Comment by Nikratio** [comment]
Nowhere, at the moment. If you're interested in this, feel free to maintain a list somewhere (maybe the wiki?).

**Comment by trapexit** [comment]
Isn't the point of the issue tracker to keep track of the outstanding issues? Keeping only currently worked on issues in the tracker is a very odd way of using it.

**Comment by Nikratio** [comment]
I agree, with "outstanding" in the sense of "someone looking to do some work on libfuse might reasonably pick this issue". It's not necessary for someone to currently work on them.
