### ISSUE TITLE
Write requests less than 4K trigger read requests （enable writeback）

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#400]
`enable writeback`
When the write request is less than 4K (paging size), libfuse receives a read request (4k).

**What** is the meaning of reading a request?

**Can** this function be turned off?

**Comment by Nikratio** [comment]
Writeback means that the kernel caches write requests. This is done in units of pages (in your case kb). You always need to have one full page of data, so if you write less than that, the kernel needs to find out the missing data. The only way to turn this off is to disable writeback caching.
