### ISSUE TITLE
simplify passthrough_ll at the expense of race safety

### ISSUE THREAD

**Issue by asomers** [libfuse/libfuse#407]
passthrough_ll makes clever use of Linux's `AT_EMPTY_PATH` flag to provide safety against races between the client and the underlying file system.  For example, if a file in the underlying file system gets renamed, passthrough_ll will usually be able to track the file across the rename operation.  However, this approach causes several problems:

1) It isn't portable, because `AT_EMPTY_PATH` is Linux-specific.
2) It's more confusing than simply tracking files' file names.  As an example program, simplicity is a design goal.
3) It is incompatible with named pipes, because the `openat` in `lo_do_lookup` will block on a named pipe.
3b) **Edit**: It's incompatible with device files too, for the same reason.  `lo_do_lookup` will try to open the device file.
3c) **Edit 2**: That same `open` during `lo_do_lookup` also causes problems for sockets and dead symlinks.
4) It doesn't eliminate all race conditions, leading to a false sense of security.  For example, every place that currently uses procfs is vulnerable to a rename race.
5) The goal of robustness in the face of changes to the underlying file system precludes the use of the attribute and entry caches.  Those caches can both improve performance and serve as useful examples.

I propose eliminating the use of both `AT_EMPTY_PATH` and procfs.  Instead, `struct lo_inode` will simply save the pathname of each file.  The result will be an example file system that is simpler, more portable, and compatible with fifos.  It will also be possible to enable the attribute and entry caches with a runtime option.  However, the program will no longer be remotely robust in the face of unexpected changes to the underlying file system.  IMHO that's fine for an example program.

**Comment by Nikratio** [comment]
Sounds good to me. I was actually thinking about adding a second "example" that focuses on performance and correctness rather than simplicity (since a lot of people are interested in that). Simplifying the existing example would fit nicely into that plan.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
