### ISSUE TITLE
fuse_lib_create doesn't work with sockets

### ISSUE THREAD

**Issue by asomers** [libfuse/libfuse#408]
The high level API precludes the use of sockets by assuming that OP_CREATE is only used with regular files.  In fact, that opcode is used for both regular files and sockets.  AFAICT this was an oversight in revision d9079a75b14b73e7953adf4958709b1e5ab3804c .  The following patch fixes the problem.  Tested against libfuse 2.9.9 with fusefs-ext2 0.0.10 on FreeBSD 13.0-CURRENT.  I haven't tested the patch with libfuse master, because I don't have a file system that works with sockets and uses libfuse-3.

```
--- lib/fuse.c.orig	2019-05-04 15:37:10 UTC
+++ lib/fuse.c
@@ -3190,7 +3190,9 @@ static void fuse_lib_create(fuse_req_t req, fuse_ino_t
 			err = lookup_path(f, parent, name, path, &e, fi);
 			if (err)
 				fuse_fs_release(f->fs, path, fi);
-			else if (!S_ISREG(e.attr.st_mode)) {
+			else if (!S_ISREG(e.attr.st_mode) &&
+				 !S_ISSOCK(e.attr.st_mode))
+			{
 				err = -EIO;
 				fuse_fs_release(f->fs, path, fi);
 				forget_node(f, e.ino, 1);
```

**Comment by Nikratio** [comment]
Thanks! Would you be able to submit a pull request?

**Comment by asomers** [comment]
Would you accept a PR even though I don't have a way to test this patch on the master branch?

**Comment by Nikratio** [comment]
Yes

**Comment by asomers** [comment]
Actually, this issue is obsolete.  After I opened it, I changed FreeBSD's fuse driver to use `OP_MKNOD` so that it will work with existing FUSE file systems.
https://svnweb.freebsd.org/base?view=revision&revision=347395
