### ISSUE TITLE
Auto unmount stale FUSE mount before mounting at start-up

### ISSUE THREAD

**Issue by cmcqueen** [libfuse/libfuse#41]
I see libfuse has an `-o auto_unmount` option. That's great. But what about the case where, at start-up, the mount point is still mounted stale? It might be good to have an option to auto unmount the stale mount, before remounting, rather than failing with a "bad mount point <mount>: Transport endpoint is not connected" error.

I looked up the old mailing list messages about the auto-unmount idea several years ago. Someone pointed out that some might want the stale mount to persist so programs accessing it (such as `rsync`) get an error rather than just an empty directory. That sounds fair enough. Si in that case, `-o auto_unmount` wouldn't be used, but then it would be nice to clean up the stale mount next time the program is run.

Is that a reasonable feature idea, or is there a better way to handle that scenario?

**Comment by Nikratio** [comment]
Well, "that scenario" ought to be a rare exception, right? It only happens if the file system crashed. So in which situation would you use this "silently work around program crashes" option? And why can't you just call `fusermount -u` before mounting the file system?

**Comment by cmcqueen** [comment]
That's a good philosophical question. I come from an embedded systems background (e.g. automotive, fire safety), where it's highly desirable to continue working, even in the face of unusual failure modes.

(With this philosophy, a significant portion of design effort and code can end up being to handle all the failure modes. But that effort pays off in reputation for reliability.)

I could call `fusermount -u` before mounting the file system. It seems favourable to add it to libfuse itself, but maybe you're right, maybe this belongs in my code.

**Comment by Nikratio** [comment]
After contemplating this for a while, I don't think it makes sense to add this feature. If you use `-o auto_unmount`, the mountpoint should never ever be stale. If you've found a way to get a stale mountpoint when using `-o auto_unmount`, then please re-open this issue. That would be a bug that definitely needs to be fixed.
