### ISSUE TITLE
Question about fuse low level API and valgrind

### ISSUE THREAD

**Issue by falk-werner** [libfuse/libfuse#410]
**Background**

Recently, I tried low level API of libfuse. In order to verify my knowledge, I did some unit tests. I had two threads in my test application:
- one to execute the filesystem loop and 
- another to execute normal filesystem operations, such as `stat`

Everything worked fine, until I started using valgrind.

**Problem**

When using valgrind to execute tests, I got a deadlock as soon as `stat` is called. The process went to sleep and both threads are blocked.

**Investigation**

I really believe, that I am doing something wrong. Therefore, I created a minimal sample application to demonstrate the issue:  
https://github.com/falk-werner/libfuse-valgrind-deadlock

The example contains the test code, some stack traces and a Makefile to create docker images showing the issue with several versions of libfuse.

I also read https://github.com/libfuse/libfuse/blob/master/doc/kernel.txt, since the case I observed may be one of the already known deadlock scenarios. Unfortunately, I was not able to determine if this is the case.

But since there are some already closed issues here, that mention the use of valgrind to investigage filesystem issues, I beliebe my issue comes from wrong usage of the library.

**Question**

Can you tell me, what I am doing wrong, please?

**Comment by Nikratio** [comment]
Most likely Valgrind is not expecting that a syscall like read() calls back into the program, and therefore does not release a lock before. Best practice is to put the filesystem and the test program into separate processes, not threads.

**Comment by Nikratio** [comment]
For further questions, could you use the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

**Comment by falk-werner** [comment]
Thank you for your quick reply. I will use the mailing list next time, sorry for misusing the issue tracker.
I will start using separate processes to test the filesystem, just as recommended. 

I will also add the issue to Valgrinds issue tracker  _(although I don't believe the issue will be fixed in near future, since it may be considered as some kind of corner case for Valgrind, but it may prevent some other guy from cumbersome debugging sessions)_.
