### ISSUE TITLE
passthrough_hp problems without use of --nocache

### ISSUE THREAD

**Issue by Smit-tay** [libfuse/libfuse#416]
I am experiencing a failure for the test:
test/test_examples.py::test_passthrough_hp[True]

For same reason, when caching is enabled, the pytest function tst_passthrough(src_dir, mnt_dir) fails.  BUT, oddly, only when run under pytest.  IOW, I can run the passthrough_hp daemon without specifying --nocache, then create a file in src, and it is visible in mnt.   Yet running within pytest this fails at line 677  <assert name in os.listdir(mnt_dir)>

I have interrupted the test before the call to os.listdir() and verified that the file does not appear in mnt, while being present in src.  So, this is not a strange issue with os.listdir(), but rather somehow passthrough_hp's behaviour is affected by the fact it is launched via pytest.

I'm happy to investigate this further, but, I am struggling to understand where to look.  

Any hints - please ??

**Comment by Nikratio** [comment]
Are you running kernel >= 4.20?

When trying to reproduce the problem by hand, does it make a difference if you call 'ls' on mnt *before* creating the file?

**Comment by Smit-tay** [comment]
$ uname -a
Linux My-laptop 5.0.13-300.fc30.x86_64 #1 SMP Mon May 6 00:39:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

In attempting to test your question I did this:
$ /home/me/dev/libfuse-GOLD/build/test/../example/passthrough_hp /tmp/src /tmp/mnt --debug

Then in a separate console did this:
$ ls /tmp/mnt
<no result>
$ touch /tmp/src/file1
$ ls /tmp/mnt
file1
$ touch /tmp/src/file2
$ ls /tmp/mnt
file1  file2

Then I shut down passthrough_hp, leaving the files in /tmp/src
Then restarted passthrough_hp

$ ls /tmp/mnt
file1  file2
$ touch /tmp/src/file3
$ ls /tmp/mnt
file1  file2  file3

So, it appears that even with caching, when run outside of pytest, this works as expected.

The failure mode for some reason is only when running under pytest



So, as far as I can tell, the behavior appears to not depend upon listing the mount directory before creating a file

**Comment by Nikratio** [comment]
Hmm, that's odd. But setting `fi->cache_readdir = 0` in `passthrough_hp.cc` does fix the problem, right?

**Comment by Smit-tay** [comment]
That is correct.
Setting fi->cache_readdir = 0 in passthrough_hp.cc allows the test to execute successfully via pytest.

**Comment by Nikratio** [comment]
Ok.. how about timing then? Probably the sucessive reads happen much faster with pytest than when run by hand. Can you reproduce it with a shell script?

**Comment by Smit-tay** [comment]
Indeed, with a shell script, I get the same (incorrect) behavior.

Also, after running the script, adding new files to src (manually) never appear to result in new files in mnt.

It seems like the cache is not being invalidated.

**Comment by Nikratio** [comment]
Yes, there is no way for the cache to be invalidated, since the source directory is changed without the fs being aware of it. You could do something with inotify, but one of the core assumptions of passthrough_fh is that all modifications come through the filesystem. So this is more of a bug in the testcase. Thanks for looking into this, will try to come up with a fix!

**Comment by Smit-tay** [comment]
I'm confused.

If this is failing for everybody (not just me) why was it pushed to master ?

**Comment by Nikratio** [comment]
Readdir caching was only added in kernel 4.20. Most people (including the CI) probably still run older kernels.

**Comment by Smit-tay** [comment]
After a little more experimenting, I have discovered that it is when operated on automatically that the cache becomes (and then remains) invalid.

For example, if you manually populate src with files, then list mnt, they will appear.  Until you run a process which does multiple operations, like a BASH script here:

#!/usr/bin/env bash
# Requires file name as parameter
ls /tmp/mnt
touch /tmp/src/"$1"
ls /tmp/mnt

From that point on the only what *was* in the cached directory list will be presented by the FS when listing mnt.  Even when adding files manually after running the script, the listing remains as previously cached.

I find this extremely strange - can you explain how this is happening.  I'd really like to understand the internals better.

As shown here:
# Before FS is running
$ rm -rf /tmp/src/*
$ ls /tmp/src
$ ls /tmp/mnt
$ touch /tmp/src/file1
$ touch /tmp/src/file2

#  As expected, /tmp/mnt is empty, FS is not yet running
$ ls /tmp/mnt


$ #Start FS
$ ls /tmp/mnt
file1  file2

#Manually add files
$ touch /tmp/src/file3
$ ls /tmp/mnt
file1  file2  file3
$ touch /tmp/src/file4

# Manually adding files allows FS to list them in mnt
$ ls /tmp/mnt
file1  file2  file3  file4

# Now run a script to add 1 more file
$ bash test.sh file5
file1  file2  file3  file4
file1  file2  file3  file4

# FAIL !
# Try manually listing mnt
$ ls /tmp/mnt
file1  file2  file3  file4

# file was created in src, but does not show up in mnt
$ ls /tmp/src
file1  file2  file3  file4  file5

#Try manually adding file
$ touch /tmp/src/file6
$ ls /tmp/mnt
file1  file2  file3  file4

# Cache remains invalid. ?!?!?!?!?

**Comment by Nikratio** [comment]
My guess is that this is more related to timing than manual/automatic. It certainly is not related to #401, that only affects non-Linux systems.

What if you add some `sleep 5` calls in-between the commands in `test.sh`?

**Comment by Smit-tay** [comment]
Adding sleep 5 between commands has no effect on the outcome, the result of listing mnt is still incorrect.

**Comment by Nikratio** [comment]
Not sure what to explain... libfuse maintains a cache of directory contents. If you modify the directory contents without libfuse noticing (by modifying the source directory directly, instead of going through the mountpoint), libfuse will report the old, invalid contents until the cache is flushed for other reasons (timeout, memory pressure, etc.).

If you use `--nocache`, the directory cache is disabled and libfuse always reads the contents from the source directory.
