### ISSUE TITLE
RHEL 6 ninja error - missing securebits.h

### ISSUE THREAD

**Issue by scottjarman** [libfuse/libfuse#417]
Hi

In RHEL 6.5  ( Kernel 2.6.32 )  there is no securebits.h but the Ninja build requires it:

    ../util/mount.fuse.c:25:30: error: linux/securebits.h: No such file or directory

Is there anyway to bypass this or is it a critical requirement ?

Thanks

Scott

**Comment by Smit-tay** [comment]
On RedHat based systems securebits.h is provided by package kernel-headers

Consider that a prerequisite for lib-fuse development.

**Comment by paullintilhac** [comment]
I am running into this same issue when trying to install libfuse. I can see the `securebits.h` file in multiple locations on my system, so I guess ninja just isn't seeing it. Any idea on what environment variable needs to be set to include that location?

**Comment by bsbernd** [comment]
You need `linux/securebits.h`, typically /usr/include/linux/securebits.h`

**Comment by bsbernd** [comment]
And it is not ninja asking for the flag, but your compiler.

**Comment by Smit-tay** [comment]
This shouldn't happen - as, no doubt, you know. 

It would be helpful to know what OS flavor/version you are trying to compile for.
