### ISSUE TITLE
Cannot mount on ufsd filesystem

### ISSUE THREAD

**Issue by tenzap** [libfuse/libfuse#418]
Hello,

When trying to mount an ISO file to a mounting point on a NTFS partition mounted with UFSD driver (the paragon NTFS/HFS implementation) I have the following error message :

`fusermount: mounting over filesystem type 0x736675005346544e is forbidden`

For info, this is the output of df -T (2nd column is the type)
`/dev/sda16       ufsd       226G    175G   52G  78% /mnt/***`

output of stat fs .
`    ID: 0        Namelen: 255     Type: UNKNOWN (0x736675005346544e)`

Could you allow mounting of ISO on that filesystem ?

**Comment by Nikratio** [comment]
Thanks for the report! I'm happy to add support if someone submits pull request - here's a similar example: https://github.com/libfuse/libfuse/pull/392

**Comment by tenzap** [comment]
Here is a patch towards 2.9.9

[ufsd_support-2.9.9-.patch.gz](https://github.com/libfuse/libfuse/files/3260114/ufsd_support-2.9.9-.patch.gz)

**Comment by Nikratio** [comment]
Could you submit a pull request instead? Thanks!

**Comment by tenzap** [comment]
That's beyond my skills, sorry.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Comment by Nable80** [comment]
FYI: this value yields a warning on some 32-bit systems:
```
../fuse-3.11.0/util/fusermount.c: In function 'check_perm':
../fuse-3.11.0/util/fusermount.c:1025:17: warning: overflow in conversion from 'long long int' to 'int' changes value from '8315462406243767374' to '1397118030' [-Woverflow]
 1025 |                 0x736675005346544e /* UFSD */,
      |                 ^~~~~~~~~~~~~~~~~~
```

Maybe it's better to always use ``u64``/``uint64_t``/``unsigned long long`` instead of ``typeof(fs_buf.f_type)``. I wonder which ``f_type`` is reported by the UFS driver on 32-bit systems.
