### ISSUE TITLE
Fuse3 doesn't accept direct_io mount option

### ISSUE THREAD

**Issue by sunwire** [libfuse/libfuse#419]
Support for direct_io has been removed with this commit
https://github.com/libfuse/libfuse/commit/8ee553dac0297cfd75cbdd2d9cfdce37e22ef4ee#diff-ea5d64ddacb25ba3b5f93f299b159d94
Now if I mount e.g. /proc/net from a remote machine (with fuse-sshfs) and try to read any file from this mount point, the reading always returns 0 bytes instead of the actual content.

To enable direct_io I have to add this code
FUSE_LIB_OPT("direct_io",	      direct_io, 1),
to the fuse.c file bellow line
static const struct fuse_opt fuse_lib_opts[] = {

Is it possible to restore this option for the end user?

**Comment by Nikratio** [comment]
Thanks for the report! While libfuse no longer accept this as a command line option, filesystems like SSHFS can still selectively enable this in whatever way they want. So I'd suggest to request this as a feature in SSHFS instead (there were good reasons for not accepting this in libfuse anymore).

**Comment by DUOLabs333** [comment]
I have the same problem -- how would I add functionality back on the program side.

**Comment by sunwire** [comment]
@DUOLabs333 This functionality has been added to sshfs https://github.com/libfuse/sshfs/pull/173

**Comment by aakefbs** [comment]
One can do it as in sshfs, set fi->direct_io in fuse_operations::{open,create} methods or set in fuse_operations::init fuse_config::direct_io

Personally I don't see why some options like these have been removed, as their are kernel-fuse options and file system implementation independent.
