### ISSUE TITLE
Ambiguous conditional expression

### ISSUE THREAD

**Issue by e03213ac** [libfuse/libfuse#42]
While compiling with `gcc-5.3.0` I noticed the following warning:

    ulockmgr_server.c: In function ‘receive_message’:
    ulockmgr_server.c:95:24: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
       if (!cmsg->cmsg_type == SCM_RIGHTS) {
                            ^
The warning seems legit. It should be replaced with:

       if (cmsg->cmsg_type != SCM_RIGHTS) {

**Comment by Nikratio** [comment]
thanks for the report!
