### ISSUE TITLE
The reading performance of V2.9.4 is higher than V3.1.1, is it reasonable?

### ISSUE THREAD

**Issue by Roay** [libfuse/libfuse#422]
As the title, I tested the sequential read performance through `FIO` and found that the performance of v2.9.4 is higher than v3.1.1. Is it reasonable?
```
Fio command:
fio -filename=/mnt/test-fuse/file -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=4k -size=50G -numjobs=4 -runtime=500 -time_based -group_reporting -name=test
**note**：File is a virtual large file based on fuse
```
 Why does the performance of the high version decrease?

**Comment by Nikratio** [comment]
Thanks for the report. This isn't expected. If someone can find out which specific change is responsible for this, that would be great. First step would be to make sure that this is indeed a change in libfuse, rather than the filesystem / filesystems you have tested with.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
