### ISSUE TITLE
fusermount: extra arguments after the mountpoint

### ISSUE THREAD

**Issue by passwordleak** [libfuse/libfuse#423]
fusermount version: 2.9.2
I am trying to mount a raw image, but it fails, despite the fact that there are no extra arguments after the mountpoint. 
```
fusermount /test.dd /mnt/test
fusermount: extra arguments after the mountpoint
```

**Comment by Nikratio** [comment]
Thanks for the report! I think you misunderstood something about fusermount though, this is not intended for end-users to mount anything directly. You will need to find a filesystem that is designed for the raw image in question, or use `mount -o loop`.
