### ISSUE TITLE
Can I mount hgfs over 7 by root ?

### ISSUE THREAD

**Issue by i-beetle** [libfuse/libfuse#426]
PLEASE READ BEFORE REPORTING AN ISSUE

libfuse does not have any active, regular contributors or developers.  The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. When reporting bugs, please understand that unless you are including a pull request or are reporting a critical issue, you will probably not get a response.

To prevent the issue tracker from being flooded with issues that no-one is intending to work on, and to give more visibilty to critical issues that users should be aware of and that most urgently need attention, I will also close most bug reports once they've been inactive for a while.

Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. Unfortunately, libfuse is a purely volunteer driven project, and at the moment there simply aren't any volunteers.

**Comment by i-beetle** [comment]
I am using VMwareFusion 10 on the MacOS 10.14 now.
The guest OS is CentOS7 for Samba server.
I try mount many(over 40 mount points) VMware's ShareFolders to the CentOS7 by '/etc/fstab' for Samba User's Home directory !!
I consider that I back up the Samba's Home Directory on CentOS7 to MacOS 's TimeMachine.

/etc/fstab is ...
~- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
:
.host:/aaa /mnt/macos/aaa fuse.vmhgfs-fuse noauto,allow_other,default_permissions,uid=1001,gid=519 0 0
:
.host:/zzz/mnt/macos/zzz fuse.vmhgfs-fuse noauto,allow_other,default_permissions,uid=1026,gid=519 0 0
:
~- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

And after Startup...

~- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
mount /mnt/aaa
mount /mnt/bbb
:
mount /mnt/zzz
~- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

But I could't mount over 7 mount points !!!
I got the ERROR 'Error -107 cannot open connection!' above 8 mount point !!

I wish that I will can mount hgfs over 8 mount points by root !!!

It is FUSE's Limitation ?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
