### ISSUE TITLE
fuse doesn't work in mount an sshfs filesystem when there is a comma in the password

### ISSUE THREAD

**Issue by iltis42** [libfuse/libfuse#428]
As an example (user and password altered for security reasons), the following mount is not possible as of a comma within the password:
 sshfs sftp.hidrive.strato.com:/users/user1 /mnt/user1 -o ssh_command='sshpass -e ssh -l user1 -p "?QTft0pIAG,f"',rw,allow_other

fuse: unknown option `f"'
Fuse takes all after the comma as a new option. I could not find any workaround to escape comma in order to workaroun the problem. Apparently the options list gets passed with 'resovled' escapes, or the escape won't be resolved within password.
Problem is easy to reproduce.
No issue with a modified password without comma, hence the passwords are created by another organisation which cannot avoid to get there a comma in as its autogenerated.

**Comment by Nikratio** [comment]
Thanks for reporting this issue! You are right, commas in the password are currently not supported. I don't think it is worth adding support for this - the rarity of the use-case doesn't justify the necessary complexity in the code. (In most cases, using pubkey authentication instead of writing the password into fstab is a better solution). So I'll close this as WONTFIX.

**Comment by vojta001** [comment]
It might not be a good justification either, but I would like to note that you cannot therefore use multiple jump hosts for sshfs as they are separated by a comma as `sshfs -o ssh_command='ssh -J firstuser@firsthost,seconduser@secondhost' …`

**Comment by mvanros** [comment]
> It might not be a good justification either, but I would like to note that you cannot therefore use multiple jump hosts for sshfs as they are separated by a comma as `sshfs -o ssh_command='ssh -J firstuser@firsthost,seconduser@secondhost' …`

This is a problem I am currently facing, as it seems currently impossible to mount via sshfs through 2 jumps (ie, localhost  -> jump A -> jump B -> remotehost) at the moment with this issue.
