### ISSUE TITLE
LTFS refusing to mount unless opt_parse section remmed out(LTO tape backup)

### ISSUE THREAD

**Issue by JazzMaster** [libfuse/libfuse#429]
A core critical "new age" tape backup method appears to be borked- not due to vendor support- but rather a FUSE/libfuse limitation or code change. Some may very well ask why the sources refuse to compile- or do so and BAIL- when they are not supposed to.

LTFS makes tape backups- and access much easier. However- it requires libFUSE to work correctly.

command-line options are parsed correctly (I would assume) if given to the LTFS binary. However- said binary will not build unless libfuse opt_parsing sections are remmed out.
I dont think this is the underlying problem. I believe it may the calling convention with (Quantum, HP, IBM) supported vendored drives' source code.

Since you just stated that there is NO active devs- the burden falls on you- and shouldnt fall on the end (TAPE) user. Those using these units in enterprise environments may wish to take heed.

Anyways: 

here is the QUANTUM patch.

patch QT sources for ltfs(needed-opt_parse error is not a OS limtation)
(not libQt- quantum abbreviates)

/* ret = fuse_opt_parse(args, device, ltotape_opts, null_parser);
if (ret < 0) {
ltfsmsg(LTFS_ERR, "20037E", ret);
return ret;
}
*/

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid I can't see any description of a libfuse issue here, you seem to be describing a problem with a different project. I'll close this report for now - feel free to reopen if you've found a specific bug in fuse_opt_parse().
