### ISSUE TITLE
Building errors with meson in CentOS7

### ISSUE THREAD

**Issue by 2994186010** [libfuse/libfuse#439]
When I use meson and ninja to build fuse-3.5.0, I encounter errors.
When I run the command "meson.py fuse-3.5.0", the repsonse message is as following,
The Meson build system
Version: 0.51.999
Source dir: /root/fuse/fuse-3.5.0
Build dir: /root/fuse
Build type: native build
Project name: libfuse3
Project version: 3.5.0
C compiler for the build machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)")
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "fork" : YES 
Checking for function "fstatat" : YES 
Checking for function "openat" : YES 
Checking for function "readlinkat" : YES 
Checking for function "pipe2" : YES 
Checking for function "splice" : YES 
Checking for function "vmsplice" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "fdatasync" : YES 
Checking for function "utimensat" : YES 
**Checking for function "copy_file_range" : NO** 
Checking for function "setxattr" : YES 
Checking for function "iconv" : YES 
Checking whether type "struct stat" has member "st_atim" : YES 
**Checking whether type "struct stat" has member "st_atimespec" : NO** 
Configuring config.h using configuration
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
Message: Compiler warns about unused result even when casting to void
Run-time dependency threads found: YES 
**Library iconv found: NO**
Library dl found: YES
Library rt found: YES
Found pkg-config: /usr/bin/pkg-config (0.27.1)
Run-time dependency udev found: YES 219
Program install_helper.sh found: YES (/root/fuse/fuse-3.5.0/util/install_helper.sh)
Build targets in project: 25
Found ninja-1.9.0 at /usr/bin/ninja

**Comment by Nikratio** [comment]
Could you clarify what you mean with "I encounter errors."? The output that you quoted only contains two warnings, and these are harmless.
