### ISSUE TITLE
Syntax error in passthrough_ll.c: #elif with no expression

### ISSUE THREAD

**Issue by 2994186010** [libfuse/libfuse#440]
According to the commands in the **Installation** of libfuse, I have run the commands as following,
```
$ mkdir build; cd build
$ meson ..
$ ninja
```
When I run the command "ninja" according to the REMDME.md, I encountered an error "../example/passthrough_ll.c:939:27: error: #elif with no expression".
After running the command "ninja", the output is as following:
```
[49/65] Compiling C object 'example/example@@passthrough_ll@exe/passthrough_ll.c.o'.
FAILED: example/example@@passthrough_ll@exe/passthrough_ll.c.o 
cc -Iexample/example@@passthrough_ll@exe -Iexample -I../example -Iinclude -I../include -Ilib -I../lib -I. -I../ -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -D_REENTRANT -DHAVE_CONFIG_H -Wall -Wextra -Wno-sign-compare -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -Wno-unused-result -pthread  -MD -MQ 'example/example@@passthrough_ll@exe/passthrough_ll.c.o' -MF 'example/example@@passthrough_ll@exe/passthrough_ll.c.o.d' -o 'example/example@@passthrough_ll@exe/passthrough_ll.c.o' -c ../example/passthrough_ll.c
../example/passthrough_ll.c: In function ‘lo_do_readdir’:
../example/passthrough_ll.c:701:6: warning: missing initializer for field ‘st_nlink’ of ‘struct stat’ [-Wmissing-field-initializers]
      .attr.st_mode = d->entry->d_type << 12,
      ^
In file included from /usr/include/fcntl.h:77:0,
                 from ../include/fuse_lowlevel.h:28,
                 from ../example/passthrough_ll.c:42:
/usr/include/bits/stat.h:61:15: note: ‘st_nlink’ declared here
     __nlink_t st_nlink;  /* Link count.  */
               ^
../example/passthrough_ll.c:702:5: warning: missing initializer for field ‘st_uid’ of ‘struct stat’ [-Wmissing-field-initializers]
     };
     ^
In file included from /usr/include/fcntl.h:77:0,
                 from ../include/fuse_lowlevel.h:28,
                 from ../example/passthrough_ll.c:42:
/usr/include/bits/stat.h:64:13: note: ‘st_uid’ declared here
     __uid_t st_uid;  /* User ID of the file's owner. */
             ^
../example/passthrough_ll.c: In function ‘lo_fallocate’:
../example/passthrough_ll.c:939:27: error: #elif with no expression
 #elif HAVE_POSIX_FALLOCATE
                           ^
[51/65] Compiling C object 'example/example@@null@exe/null.c.o'.
ninja: build stopped: subcommand failed.
```

**Comment by Nikratio** [comment]
Thanks for the report. I'm not sure what to do here - it works fine on my system, for the CI, and the various distributions that ship precompiled binaries. I think there's something odd about the system that you are using..

**Comment by AgrawalAmey** [comment]
Faced the error on Centos 7.

**Comment by EthanBannister** [comment]
@AgrawalAmey Same here, running CentOS 7

**Comment by chengmyy** [comment]
Same problem，is there a solution?

**Comment by Nikratio** [comment]
Thanks everyone for the reports! At this point, it is pretty clear that there is a problem somewhere.

However, libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

Any takers?
