### ISSUE TITLE
fuse: memory allocation failed with kernel 2.6.32

### ISSUE THREAD

**Issue by MastaG** [libfuse/libfuse#443]
Hi there,

I need to get libfuse3 and sshfs running on an older platform.
It runs linux 2.6.32 and uses uClibc 0.9.32.1.

Now I've created a toolchain using crosstool-ng to build a cross-compiler matching this kernel and c-library.

I've build sshfs (git snapshot), libfuse 3.6.2 (and all of their dependencies such as glib-2.0 etc)
Now when I transfer the libraries and binaries to my platform I get the following:

strace /tmp/t/bin/sshfs -o ssh_command="/tmp/t/bin/ssh" -o StrictHostKeyChecking=no -o IdentityFile=/tmp/sshfs/key -o ServerAliveInterval=15 -o Ciphers=arcfour -o reconnect -o Compression=no -p 2222 root@localhost:/data /tmp/data

execve("/tmp/t/bin/sshfs", ["/tmp/t/bin/sshfs", "-o", "ssh_command=/tmp/t/bin/ssh", "-o", "StrictHostKeyChecking=no", "-o", "IdentityFile=/tmp/sshfs/key", "-o", "ServerAliveInterval=15", "-o", "Ciphers=arcfour", "-o", "reconnect", "-o", "Compression=no", "-p", ...], [/* 14 vars */]) = 0
brk(0)                                  = 0x570000
brk(0x570c7c)                           = 0x570c7c
set_thread_area(0x577460)               = 0
set_tid_address(0x570068)               = 11261
SYS_4309()                              = 0
futex(0x7f862818, 0x189 /* FUTEX_??? */, 1, NULL, 0) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGRT_0, {0x8, ~[HUP INT QUIT ILL TRAP IOT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM USR1 USR2 CHLD PWR WINCH URG IO STOP TSTP CONT TTIN TTOU VTALRM PROF XCPU XFSZ RT_0 RT_1 RT_2 RT_3 RT_4 RT_5 RT_6 RT_7 RT_8 RT_9 RT_10 RT_11 RT_12 RT_13 RT_14 RT_15 RT_16 RT_17 RT_18 RT_19 RT_20 RT_21 RT_22 RT_23 RT_24 RT_25 RT_26 RT_27 RT_28 RT_29 RT_30 RT_31 RT_32 RT_33 RT_34 RT_35 RT_36 RT_37 RT_40 RT_41 RT_42 RT_43 RT_44 RT_45 RT_46 RT_47 RT_48 RT_49 RT_50 RT_51 RT_53 RT_54 RT_56 RT_57 RT_58 RT_59 RT_60 RT_61 RT_62 RT_63 RT_64 RT_65 RT_66 RT_70 RT_73 RT_74 RT_78 RT_80 RT_81 RT_85 RT_86], SA_SIGINFO|SA_NOCLDWAIT|0x424970}, NULL, 16) = 0
rt_sigaction(SIGRT_1, {0x10000008, ~[HUP INT QUIT ILL TRAP IOT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM USR1 USR2 CHLD PWR WINCH URG IO STOP TSTP CONT TTIN TTOU VTALRM PROF XCPU XFSZ RT_0 RT_1 RT_2 RT_3 RT_4 RT_5 RT_6 RT_7 RT_8 RT_9 RT_10 RT_11 RT_12 RT_13 RT_14 RT_15 RT_16 RT_17 RT_18 RT_19 RT_20 RT_21 RT_22 RT_23 RT_24 RT_25 RT_26 RT_27 RT_28 RT_29 RT_30 RT_31 RT_32 RT_33 RT_34 RT_35 RT_36 RT_37 RT_40 RT_41 RT_42 RT_43 RT_44 RT_45 RT_46 RT_47 RT_48 RT_49 RT_50 RT_51 RT_53 RT_54 RT_56 RT_57 RT_58 RT_59 RT_60 RT_61 RT_62 RT_63 RT_64 RT_65 RT_66 RT_70 RT_73 RT_74 RT_78 RT_80 RT_81 RT_85 RT_86], SA_NOCLDWAIT|0x424830}, NULL, 16) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_0 RT_1], NULL, 16) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=1024*1024, rlim_max=RLIM_INFINITY}) = 0
open("/dev/urandom", O_RDONLY)          = 3
read(3, "g0\347\36"..., 4)              = 4
close(3)                                = 0
ioctl(0, TIOCNXCL, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCNXCL, {B38400 opost isig icanon echo ...}) = 0
brk(0x571c7c)                           = 0x571c7c
brk(0x572000)                           = 0x572000
gettimeofday({1565771361, 714218}, NULL) = 0
brk(0x573000)                           = 0x573000
brk(0x575000)                           = 0x575000
brk(0x576000)                           = 0x576000
readlink("/tmp", 0x7f861680, 4095)      = -1 EINVAL (Invalid argument)
readlink("/tmp/data", 0x7f861680, 4095) = -1 EINVAL (Invalid argument)
time(NULL)                              = 1565771361
getuid()                                = 0
brk(0x57e000)                           = 0x57e000
brk(0x586000)                           = 0x586000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|0x20, -1, 0) = -1 EBADF (Bad file descriptor)
write(2, "fuse: memory allocation failed\n"..., 31fuse: memory allocation failed
) = 31
exit_group(1)                           = ?

Is the kernel simply too old for libfuse 3.6.2  or could it be something else I missed?

**Comment by Nikratio** [comment]
I don't know for sure, but it wouldn't surprise me if 2.6.32 was simply too old. The other possible reason us uClibc. I'd try to run with either a newer kernel or glibc, if only for testing.

**Comment by Nikratio** [comment]
I don't think this is a bug in libfuse though, so I'm closing this issue. Please feel free to continue the discussion on the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel),
