### ISSUE TITLE
Proposal: Rename standard system types to equivalent FUSE types

### ISSUE THREAD

**Issue by billziss-gh** [libfuse/libfuse#453]
With this issue I am proposing that standard system types in libfuse should be renamed to equivalent FUSE types.

The motivation stems from my attempt to port libfuse to non-Unixy platforms and specifically Windows. Windows either lacks a lot of these types or worse has antiquated/conflicting versions of them, which makes it hard to sensibly port `fuse_operations`, etc.

My solution to this problem is to change types such as `struct stat` to `struct fuse_stat` everywhere. Then for platforms such as Linux and FreeBSD, one can simply:

```C
#define fuse_stat stat
```

Whereas on Windows one can define a sensible `struct fuse_stat`:

```C
struct fuse_stat
{
    // ...
};
```

With a solution like this existing file systems would not be affected in any way, whereas a Windows port of libfuse (including the low level interface) would become far more likely.

I will submit a PR related to this proposal next.

**Comment by billziss-gh** [comment]
As per my originally stated motivation I have an experimental port of libfuse to Windows in this [fork/branch](https://github.com/billziss-gh/libfuse/tree/winport).

This port is currently **work-in-progress**. The biggest obstacle in completing the port is that the necessary Windows kernel driver ([WinFuse](https://github.com/billziss-gh/winfuse)) that speaks the lowlevel FUSE protocol is not fully baked yet.

**Comment by Nikratio** [comment]
Hmm. I am not convinced. Let's revisit the issue once the Windows kernel driver is working.

**Comment by billziss-gh** [comment]
Understood and agreed. I will ping you again when this is more mature.

**Comment by billziss-gh** [comment]
@Nikratio since you closed both the related PR and this issue, should I assume that you are not interested to see the proposed changes incorporated in libfuse?

I understand that changing so many fundamental FUSE types is perhaps unpalatable, but it is the cleanest way that I can think of to provide a portable interface across UNIX and Windows. I am happy to entertain alternatives.

The [Windows port](https://github.com/billziss-gh/libfuse/tree/winport) of libfuse is essentially complete (barring bugfixes/improvements that I am doing as the WinFuse kernel driver is further developed). It was my intent to eventually submit for inclusion to this project. My hope was to avoid having to fork this project to support Windows and ending up with the same split that happened with Linux and macOS libfuse.

**Comment by Nikratio** [comment]
@billziss-gh  I have not yet made up my mind if it makes sense to make these changes. I thought our conclusion was to revisit this issue when this is more mature. Closing the issue and PR wasn't meant to signal anything beyond that.

If the Windows port is now working, could you submit a PR for the whole port so that I can get an impression how intrusive the changes are?

**Comment by billziss-gh** [comment]
> @billziss-gh I have not yet made up my mind if it makes sense to make these changes. I thought our conclusion was to revisit this issue when this is more mature. Closing the issue and PR wasn't meant to signal anything beyond that.

Thanks for clarifying and apologies for my misunderstanding.

> If the Windows port is now working, could you submit a PR for the whole port so that I can get an impression how intrusive the changes are?

I am happy to do this. But it should be understood that the port is not fully tested and that there may be significant changes to it as the Windows kernel driver matures.

**Comment by Nikratio** [comment]
> I am happy to do this. But it should be understood that the port is not fully tested and that there may be significant changes to it as the Windows kernel driver matures.

In that case, I'd prefer to defer looking at this until the driver is more mature and has some active users and supported filesystems.

**Comment by billziss-gh** [comment]
@Nikratio understood and that was my original intent.

In any case if you want to have an advance peek of the necessary changes this GitHub comparison may be instructive.

https://github.com/billziss-gh/libfuse/compare/master...billziss-gh:winport

- The major new change is the introduction of a `lib/windows` directory that contains a minimal POSIX compatibility and an implementation of `fuse_kern_mount` in `lib/windows/winfuse.c`.
- There are also some changes in `lib` for functionality that makes little sense or that is hard to achieve on Windows. Such changes are `#ifdef`'ed.
- The meson build scripts have been changed to accommodate Windows builds using the MSVC compiler.
- The `fuse_types.h` file and related changes have been incorporated.

**Comment by RayyanAnsari** [comment]
did these changes ever get merged?

**Comment by billziss-gh** [comment]
@RayyanAnsari unfortunately no.

I personally would like to see some unification of the Linux and Windows FUSE API's so as to make writing cross-platform file systems in C easier.
