### ISSUE TITLE
Large-File Corruption with sshfs

### ISSUE THREAD

**Issue by haraldrudell** [libfuse/libfuse#458]
Copying a file-set from macOS to Linux using sshfs and cp -an…

sshfs file corruption is a known problem for the last 10 years, however lots hardware deficiencies has clouded the issue of type Ethernet off-loading and dma issues

1. 40 GiB is a large-enough file-set to exhibit the problem
2. 7221070 bytes is large enough file to cause file corruption. It is possible that some maximum file size is the root cause, however, smaller or fewer files always works
3. scp -pr… works.Note: scp is more reliable in displaying issues whereas sshfs typically only exhibit issues by corrupting files for you
4. large files like video or blu-ray images provokes the issue

File verification macOS:
```D=~foxyboy/190827-s8+ && (F=~/"$(hostname -s)-${D//\//-}.txt" && echo >&2 "Writing: $F" && cd "$D" && find . -type f -print0 | LC_COLLATE=C sort --zero-terminated | xargs -0 md5 -r | sed 's/ /  /' >"$F")```

File verification Linux:
```D=/mnt/rwstore/tostorage/2/190827-s8+ && (F=~/"$(hostname -s)-${D//\//-}.txt" && echo >&2 "Writing: $F" && cd "$D" && find . -type f -print0 | LC_COLLATE=C sort --zero-terminated | xargs -0 md5sum >"$F")```

Then diff the text files

macOS sshfs: brew sshfs/2.10_1
Linux ssh: Ubuntu 19.04 openssh-server 1:7.9p1-10

This is also a problem Linux-to-Linux

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid this isn't the SSHFS bugtracker, I think you are looking for https://github.com/libfuse/sshfs/issues.
