### ISSUE TITLE
Difference between FUSE_USE_VERSION?

### ISSUE THREAD

**Issue by netheril96** [libfuse/libfuse#46]
Any documentation about the difference between different FUSE_USE_VERSION? Like what surprising behavior I will have if I bump up this define in my program?

**Comment by Nikratio** [comment]
Thanks for your interest in FUSE! Could you please send your question to FUSE mailing list
(https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
