### ISSUE TITLE
How can I choose between libfuse2 and libfuse3 at runtime?

### ISSUE THREAD

**Issue by kiril-kirov** [libfuse/libfuse#460]
I thought about checking if `fusermount3` is installed and based on that - use `dlopen` and `dlsym`.

Unfortunately, this won't work out of the box - `fuse_main_real` has a `fuse_operations*` parameter, which is a different type for both versions of `libfuse`, meaning - I can't easily construct the parameters for calling the `dlsym`-ed symbol for `fuse_main_real`.

What is the canonical way to support both versions in a single binary?

**Comment by kiril-kirov** [comment]
I thought about wrapping only `fuse_main_real` in two different shared libraries, making their API independent from the FUSE version - like `int fuse_main_wrapper(MyClassWithCallback*);`. But this is also not enough.

`MyClassWithCallback` also needs the `fuse.h` header in order to use some types, e.g. `fuse_dirfil_t` 
 (not present in `fuse_common.h`; also - types in `fuse_common.h` for v2 and v3 are different ?).

So, my current working idea is - write 2 shared libs, which will create a global object from type `MyClassWithCallback`  and then, at run-time, `dlopen` one of these libs, based on `fusermount3`. This will make the API for the two libs similar to `int fuse_main_wrapper(MyClassWithCallbacksDependencies*...);`.

Still not sure if this will work, just writing my thoughts at the moment. Sounds kinda hacky. A cleaner approach?

**Comment by trapexit** [comment]
That's not a pattern that AFAIK is supported. The expectation is / was 
that you'd use one of them and the libraries are install in parallel.

**Comment by kiril-kirov** [comment]
Well, we do support `libfuse2` now and we'd like to move towards `libfuse3` - there are plenty of features and improvements that we want from the later.

On the other hand, very few Linux distros support `fuse3`, so we can't just drop fuse2. Hence my question.

Having said that, I guess other people will also need the same sooner or later. Any advices?

**Comment by trapexit** [comment]
While it wasn't popular with some I ended up vendoring / embedding libfuse. Simplified things for my users and myself.

**Comment by kiril-kirov** [comment]
Sorry, I'm not sure if I get your point.

I can't just link statically with both of them and choose which one to use, as this will violate the one-definition rule. So, I think I can't avoid `dlopen` and family. Or I'm missing something big here?

Also, for example, even Ubuntu 18.04LTS doesn't have `fuse3`, I can't pack/embed the kernel module in our installer.

I'd also like to avoid patching the `fuse`

**Comment by trapexit** [comment]
> Also, for example, even Ubuntu 18.04LTS doesn't have fuse3, I can't pack/embed the kernel module in our installer.

There is no kernel component. Not sure what you're referring to. libfuse2 and libfuse3 are entirely userland differences and backwards compatible with different kernel module releases.

> I'd also like to avoid patching the fuse implementation for plenty of reasons.

Then you'll have to deal with the distro's support. This is what I'm getting at. I embedded libfuse2 and have taken ownership over its maintenance because most distros move far too slowly and getting the user involved in updating is a PITA. That's true with features and bugfixes (wheezy had a version of libfuse2 that would regularly segv.) I chose 2 because at the time it was easier than moving to 3 *and* doing the embedding work. It was pretty trivial to add more current FUSE features and have had some of them before the main branch.

There isn't much in terms of a middle ground. I've argued with distro packagers a few times about this and no one has provided a better solution. I don't believe mount.fuse3 / fusermount3 have changed much from v2. Perhaps its possible to use libfuse3 with v2 tooling to simplify embedding for older platforms.

**Comment by trapexit** [comment]
Or the tools could be modified so they could be installed as custom for a specific project.

**Comment by Nikratio** [comment]
I don't think it makes sense to support libfuse2 and libfuse3 in the same binary. For example, on 32-bit systems libfuse2's fuse_ino_t is 32 bit, while libfuse3's is 64 bit.  Of course, in principle everything is possible, but I doubt that it's worth the effort.

Why don't you ship two binaries (one for libfuse2 and one for libfuse3) together with a small wrapper that picks with version to use?

That said, I'd like to reserve use of the issue tracker to track issues and not use it for discussion. So let's continue the discussion on the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel).

**Comment by kiril-kirov** [comment]
Ah, I see where my misunderstanding comes from. I thought `libfuse3` is incompatible not only with `libfuse2`, but also with the kernel module for `libfuse2`. I mean - I thought there are two different kernel modules for both user-space libs - hence my questions.

OK, let's continue with the mailing lists/

**Comment by probonopd** [comment]
> I don't think it makes sense to support libfuse2 and libfuse3 in the same binary. For example, on 32-bit systems libfuse2's fuse_ino_t is 32 bit, while libfuse3's is 64 bit. Of course, in principle everything is possible, but I doubt that it's worth the effort.

We need exactly this for AppImage.

AppImages need to work without the user installing anything, besides what comes with most Linux distributions by default. Unfortunately, some distributions now have started to ship only libfuse3, while there are still-supported distributions that are shipping libfuse2. Hence we need a way to support both from the same AppImage.

How?
