### ISSUE TITLE
Minimum build enviroment

### ISSUE THREAD

**Issue by matheuskknd** [libfuse/libfuse#461]
Hello, good night. I'm a Computer Science student and I'm creating a program which must have the capability to read files from and SMB/CIFS share as they were on the local file system to work. In Windows machine it's as simple as type the path to read (\\server\share\file), but on linux (Ubuntu, at least) it's not.

I've read several things and the best solution I have is to use this software (https://github.com/OpenVisionE2/smbnetfs), that also needs FUSE installed to be built. So I could mount the SMB/CIFS share without root privileges, I gess.

The first problem I found is to build fuse-3.7.0 release. Meson is giving me the following erros:

The Meson build system
Version: 0.45.1
Source dir: /home/ophio/Downloads/fuse-3.7.0
Build dir: /home/ophio/Downloads/fuse-3.7.0/build
Build type: native build
Project name: libfuse3
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native C++ compiler: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking for function "fork": YES
Checking for function "fstatat": YES
Checking for function "openat": YES
Checking for function "readlinkat": YES
Checking for function "pipe2": YES
Checking for function "splice": YES
Checking for function "vmsplice": YES
Checking for function "posix_fallocate": YES
Checking for function "fdatasync": YES
Checking for function "utimensat": YES
Checking for function "copy_file_range": YES
Checking for function "fallocate": YES
Checking for function "setxattr": YES
Checking for function "iconv": YES
Checking whether type "struct stat" has member "st_atim": YES
Checking whether type "struct stat" has member "st_atimespec": NO
Configuring config.h using configuration
Message: Compiler warns about unused result even when casting to void
Dependency threads found: YES
Library iconv found: NO
Library dl found: YES
Library rt found: YES
Found Pkg-config: NO

util/meson.build:19:2: ERROR: Pkg-config not found.

A full log can be found at /home/ophio/Downloads/fuse-3.7.0/build/meson-logs/meson-log.txt

It's a fresh Ubuntu 18.04 installation, in which I run the following script to update and install some things:

```bash
#/usr/bin/env bash

sudo apt-get install 'gcc' 'gcc-5' 'gcc-6' 'gcc-7' 'gcc-8' -y
sudo apt-get install 'g++' 'g++-5' 'g++-6' 'g++-7' 'g++-8' -y
sudo apt-get install 'python3.7' -y
sudo apt-get install 'ruby-full' -y
sudo apt-get install 'dist-upgrade' -y

sudo apt-get install 'git'
sudo apt-get install 'meson'

# It may take several time, but is required to cross-platform buildings
sudo apt-get install 'binutils-*'
```

My questions are: is this the right place to ask about this specific library? And if it is, what should I have installed to accomplish the building? I made this installation because meson newer versions are not supported for Ubuntu 16.04, so if it's not the best distro to build it, what is?

The meson log file:
[meson-log.txt](https://github.com/libfuse/libfuse/files/3674098/meson-log.txt)

**Comment by anderspitman** [comment]
> util/meson.build:19:2: ERROR: Pkg-config not found.

There may be other problems but at the very least you need to install pkg-config:

`sudo apt-get install pkg-config`

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
