### ISSUE TITLE
Potential issue with fuse_versionscript

### ISSUE THREAD

**Issue by billziss-gh** [libfuse/libfuse#467]
This is something I have noticed during my work on a Windows port for libfuse. The  [`fuse_versionscript`](https://github.com/libfuse/libfuse/blob/fuse-3.8.0/lib/fuse_versionscript#L168) appears to have a small mistake:

```
FUSE_3.4 {
	global:
		fuse_fs_copy_file_range;
		fuse_reply_copy_file_range;
} FUSE_3.3;

FUSE_3.7 {
	global:
		fuse_set_log_func;
		fuse_log;
} FUSE_3.3;
```

Notice that the `FUSE_3.7` section references the `FUSE_3.3` section and not the `FUSE_3.4` section. Is this intentional or an oversight?

**Comment by Nikratio** [comment]
It is probably an oversight, though I am not 100% sure. Sadly, I haven't been able to find reasonably complete documentation for it so most of it is cargo-culted.

**Comment by billziss-gh** [comment]
I am looking at libfuse again and can easily address this with a PR. Drop me a quick note if you want me to.

**Comment by Nikratio** [comment]
Sure, a PR would be great!
