### ISSUE TITLE
Why fuse_loop can not support timeout?

### ISSUE THREAD

**Issue by lilijreey** [libfuse/libfuse#469]
The current implement of libfuse loop can not break, this limit the user how to user it. by now need run loop in an independent thread, why support timeout loop like poll that user can call loop in any thread.

**Comment by Nikratio** [comment]
Mainly because no one has implemented it. Would you be interested in contributing such a feature?

**Comment by lilijreey** [comment]
> Mainly because no one has implemented it. Would you be interested in contributing such a feature?

Ok， I am working on this feature， but on 2.8.2 not the newest version。 contribute code after several days。 ：）

**Comment by Nikratio** [comment]
Hmm. I'm sorry, but I would not want to add a feature to fuse 2.x that is not available in 3.x. fuse 2.x is in maintenance mode.
