### ISSUE TITLE
Feature Request: Canonical example of "Proxy Overlay Filesystem"

### ISSUE THREAD

**Issue by gwpl** [libfuse/libfuse#47]
Hi!

Could you recommend best example (preferably for C/C++ or Go), of Overlay Filesystem, that would be close as possible to just "proxying" underlaying filesystem?
Otherwise, consider adding such as one another example in examples directory?

In such, each call made to it would go through it and reach underlying filesystem unchanged and response came back.
(Such example could log operations, or do some measurements).
Such example would be great to follow to make own instrumentations (like benchmarking or things like: http://unix.stackexchange.com/q/283149/9689 fast ).

Thanks in advance and best regards,
Grzegorz Wierzowiecki

**Comment by Nikratio** [comment]
Thanks for your interest in FUSE! Could you please send your question to FUSE mailing list
(https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
