### ISSUE TITLE
fuse cp read-only file shows "Permission denied"

### ISSUE THREAD

**Issue by hexiecs** [libfuse/libfuse#470]
Fuse version: 3.1.0

When I `cp` a file from Linux whose permission mode is `0400(-r--------)` to the fuse  directory which is mounted to a remote file system, I see following error message:
```
cp: error writing './test.txt': Permission denied
cp: failed to extend './test.txt': Permission denied

```
the command is `cp /tmp/test.txt .`
In my log file, I saw following processes which the `cp` command called:
1. Create a file in current directory whose name and permission are the same as the source file.
2. Then it tries to write the file using the content of the source file. Because the file is read-only to the owner, so the write process is `permission denied`
3. Then it tries to delete to file. Again, because the file is read-only to the owner, so the writing process is `permission denied`

So I guess the reason behind this is that when fuse creates the file, it copies the permission of the source file, which causes the following write process to fail. One solution I can think of is maybe fuse should create the file using mode 0700, and chmod the file to the source file's permission mode after it finishes the copy process.

**Comment by Nikratio** [comment]
Thanks for the report! There is no such thing as "the fuse filesystem". fuse is a library. If you have problems with a filesystem that uses fuse, you'll need to report it with that filesystem.
