### ISSUE TITLE
regular crashes

### ISSUE THREAD

**Issue by GerhardSchellhorn** [libfuse/libfuse#471]
I'm running a fuse mount under kubuntu 18.04 (with current updates, so libfuse is version 2.9.7) from a server which also has the same OS. For ca. the last half year I experience 
crashes that happen irregularly every several hours to several days. The mount entry in fstab is

sshfs#schell@<servername>:/daten/kiv /home/kiv fuse defaults,debug,sshfs_debug,noauto,user,exec,allow_other 0 10

without "debug" and "sshfs_debug" (that I added to debug the problem). I'm running
scalaide (Eclipse with scala-plugin) with a scala project that is under the mount path /home/kiv. This regular refreshes files, so when running with the debug options I see lots of entries like

LOOKUP /v9/projects/lib/basic/specs/stream/doc/replay-some-result.txt
getattr /v9/projects/lib/basic/specs/stream/doc/replay-some-result.txt

that access files in /home/kiv.
At the crash I get

double free or corruption (out)
Aborted (core dumped)

The attached coredump has then been created in /var/crash. I'm no expert in C, but a colleague let
me start gdb on the attached coredump, and told me that 

it shows that libfuse crashes in fuse_fs_readdir.

If you need additional data about the environment please let me know.

[coredump.zip](https://github.com/libfuse/libfuse/files/3840793/coredump.zip)

**Comment by GerhardSchellhorn** [comment]
Oops. github does not like using less/greater symbols: the entry in /etc/fstab 
of course has the servername between @ and :

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by Nikratio** [comment]
I also see that you are using a very old version of SSHFS. There is a good chance that your problem can be fixed by upgrading to something newer.

**Comment by GerhardSchellhorn** [comment]
I'm afraid my knowledge of debugging C is not good enough to contribute. The version I'm using is the one that comes with ubuntu 18.04.3. I just checked: the newest ubuntu 19.10 has version 2.9.9 for libfuse instead of 2.9.7. Do you think this makes a difference? 

I have tried to compile the current master (not sure if replacing my version with the 
compiled result will break dependencies (?)), but did not get very far. Calling "../meson"
complains about  iconv missing, although libc6-dev is installed and there is a file /usr/include/iconv.h
It seems the meson-log-file says my iconv is incompatible:

/tmp/tmpjyhmn0cd/testfile.c:12:17: error: ‘struct stat’ has no member named ‘st_atimespec’; did you mean ‘st_atim’?
             foo.st_atimespec;
                 ^~~~~~~~~~~~
                 st_atim

Checking whether type "struct stat" has member "st_atimespec": NO

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
