### ISSUE TITLE
pkg-config to set -D_FILE_OFFSET_BITS=64 when required

### ISSUE THREAD

**Issue by onlyjob** [libfuse/libfuse#475]
To avoid FTBFS on 32-bit architectures it would be great to add `-D_FILE_OFFSET_BITS=64` to 
generated `fuse3.pc` when required.

See the following [comment](https://github.com/moosefs/moosefs/issues/311#issuecomment-555507938) for details:

> Type off_t on 32-bit Linux is by default 32-bit and you have to add -D_FILE_OFFSET_BITS=64 to change off_t to 64-bit. Since this define is essential for fuse3 it should be added to pkgconfig file distributed with package libfuse3-dev.

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by onlyjob** [comment]
I may have neither skills nor time to help with this very issue but I strongly object to such improper issues handling. Arguably what is suggested here should be done hence it is an (actionable) item on TODO list and it does not matter how soon anyone can work on this.
Until the issue is resolved it _must_ remain open. I suggest you to learn about best practice of issue management. Closing legitimate issues without action is _wrong_. Number of opened issues is not your problem but prioritisation may be and proper tagging/hinting can be helpful to classify and prioritise issues.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Comment by onlyjob** [comment]
Let's pretend this issue was never reported, shall we?

What a disgraceful handling of bugs!

You keep such issue opened and you never know who might submit a pull request one day.
Some projects mark such issues as "good first issue" because fix is probably not that difficult.

Database of known issues is useful to choose a problem to work on and to share information about outstanding problems.

Issue management will much improve if you learn how to prioritise instead of closing reports without doing anything. Denial helps nobody.
