### ISSUE TITLE
tst_rmdir in test_passthrough_hp fails when --nocache isn't specified

### ISSUE THREAD

**Issue by algrebe** [libfuse/libfuse#477]
I am encountering a failed test. It seems to occur in the test_passthrough_hp function

```
(venv) algrebe@node-0:~/downloads/libfuse/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

# I'm using the 5.3.2 linux kernel (no modifications), built from source.
(venv) algrebe@node-0:~/downloads/libfuse/build$ uname -r
5.3.2

(venv) algrebe@node-0:~/downloads/libfuse/build$ python -m pytest test/test_examples.py::test_passthrough_hp
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.8.0, pytest-5.3.0, py-1.8.0, pluggy-0.13.1 -- /users/algrebe/downloads/miniconda3/envs/venv/bin/python
cachedir: .pytest_cache
rootdir: /users/algrebe/downloads/libfuse/build/test, inifile: pytest.ini
collected 2 items

test/test_examples.py::test_passthrough_hp[False] PASSED                                                                                                                                             [ 50%]
test/test_examples.py::test_passthrough_hp[True] FAILED                                                                                                                                              [100%]

================================================================================================= FAILURES =================================================================================================
________________________________________________________________________________________ test_passthrough_hp[True] _________________________________________________________________________________________
Traceback (most recent call last):
  File "/users/algrebe/downloads/libfuse/build/test/test_examples.py", line 204, in test_passthrough_hp
    tst_rmdir(src_dir, mnt_dir)
  File "/users/algrebe/downloads/libfuse/build/test/test_examples.py", line 422, in tst_rmdir
    assert name in os.listdir(mnt_dir)
AssertionError: assert 'testfile_31' in ['testfile_27', 'testfile_25', 'testfile_30', 'testfile_28', 'testfile_26', 'testfile_29']
 +  where ['testfile_27', 'testfile_25', 'testfile_30', 'testfile_28', 'testfile_26', 'testfile_29'] = <built-in function listdir>('/tmp/tmpftk8924d/mnt')
 +    where <built-in function listdir> = os.listdir
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
============================================================================================= warnings summary =============================================================================================
/users/algrebe/downloads/miniconda3/envs/venv/lib/python3.8/site-packages/_pytest/mark/structures.py:318
  /users/algrebe/downloads/miniconda3/envs/venv/lib/python3.8/site-packages/_pytest/mark/structures.py:318: PytestUnknownMarkWarning: Unknown pytest.mark.uses_fuse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    warnings.warn(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================= short test summary info ==========================================================================================
FAILED test/test_examples.py::test_passthrough_hp[True] - AssertionError: assert 'testfile_31' in ['testfile_27', 'testfile_25', 'testfile_30', 'testfile_28', 'testfile_26', 'testfile_29']
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================== 1 failed, 1 passed, 1 warning in 1.81s ==================================================================================
(venv) algrebe@node-0:~/downloads/libfuse/build$

```

`tst_rmdir` succeeds for

```
passthrough_hp /tmp/tmprtpqz7tt/src /tmp/tmprtpqz7tt/mnt --nocache
```

but not for

```
passthrough_hp /tmp/tmpr5vz9sy1/src /tmp/tmpr5vz9sy1/mnt
```

Looking at `passthrough_hp.cc`, [the comment says](https://github.com/libfuse/libfuse/blob/ada08d50a647adb37c77f2106e7adc0db6ab93d5/example/passthrough_hp.cc#L25) we shouldn't be modifying the src directory and expect changes in the mnt directory immediately. However, the `tst_rmdir` function does exactly that - It makes a directory from the src and lists the directory from the mnt immediately after. The cache returns the older value and the assert fails.

This isn't just limited to `tst_rmdir` though. I modified the cache timeout from 86400 ( a day) to 5 seconds and slept for 10 seconds in the function. It then failed in `tst_unlink`. 

Changing [the parameters](https://github.com/libfuse/libfuse/blob/master/test/test_examples.py#L174) to just `False` also works, but I'm assuming we want to test the cached mode too.

I'd like to start working on a fix for this but would like some guidance.

Would making modifications (file creation / deletion) through the mnt rather than src be a viable solution? However, we would need this only for the cached mode when testing `test_passthrough_hp`.

**Comment by jpandre** [comment]
The passthrough test is correct, if has shown the directory cache management to be buggy.

**Comment by algrebe** [comment]
Without `nocache`, the `passthrough_hp` will cache directory contents and will only update them if files are created or removed through `mnt` or a day has passed.
So when creating a file through `src` and listing files through `mnt`, we get the old listing and the test fails.

I felt that this buggy behavior was clearly documented as "if you don't specify nocache, don't modify through src, only use mnt". The test violates that assumption.

If we do want correct cache management, we will have to listen to changes in cached directories/files (inotify / dnotify) and update them appropriately. Would that be an acceptable change? Or is there an easier way to ensure correctness and get the test to pass?

**Comment by algrebe** [comment]
This is related to #416

**Comment by Nikratio** [comment]
Thanks for the report and comments!

The report is correct. `tst_rm()` is not expected to work with `passthrough_hp` if caching is enabled. The easiest fix would be to skip the test (as done for `tst_passthrough()`). 

I think the reason that `mkdir` is called in the source directory is to separate errors in mkdir from errors in rmdir. I think it's worth to keep that behavior where possible. A good fix would be make the source directory parameter optional and call mkdir from the source directory *if specified*. `test_passthrough_hp` could then pass only a mount directory if caching is enabled. 


Adding inotify/dnotify support to `passthrough_hp.c` would be an interesting project and welcome contribution, but I think is unrelated to the issue at hand.

**Comment by algrebe** [comment]
> A good fix would be make the source directory parameter optional and call mkdir from the source directory if specified. test_passthrough_hp could then pass only a mount directory if caching is enabled.

I'll submit a pull request sometime this month with these changes!

**Comment by algrebe** [comment]
@Nikratio #493 fixes the problem. However, since `src_dir` is optional, the `tst_unlink` and `tst_rmdir` have `src_dir` as the second argument (as opposed to being the first in the other `tst_*` functions).
