### ISSUE TITLE
Ability to override path resolving

### ISSUE THREAD

**Issue by Overv** [libfuse/libfuse#481]
I'm currently implementing a file system and noticed that FUSE makes a lot of calls to fully resolve a path as a result of an `openat` call.

For example, `openat("/lib64/ld-linux-x86-64.so.2")` on my system results in the following calls to my file system:

```
getattr("/lib64",)
readlink("/lib64",)
getattr("/usr/lib",)
getattr("/usr/lib/ld-linux-x86-64.so.2",)
readlink("/usr/lib/ld-linux-x86-64.so.2",)
getattr("/usr/lib/ld-2.30.so",)
open("/usr/lib/ld-2.30.so")
```

Given that I'm implementing a network file system and all of these calls are made synchronously, this results in increased latency. Is there a way to tell FUSE to let me do the resolving of paths in a single call? Or a way to tell FUSE to pass raw paths directly to callbacks like `open`?

**Comment by trapexit** [comment]
No. That can't be done. It has to know what the details of each node in 
the tree. A file exists relative to a directory which is a node in that 
tree. You can't find the file till you find the directory.
