### ISSUE TITLE
Problems working with ninja

### ISSUE THREAD

**Issue by rrpereira** [libfuse/libfuse#487]
Hello, 
I am trying to follow the steps you listed in [README.md](https://github.com/libfuse/libfuse) but when I enter "meson ..", after some checking and configuration I get a message saying: 

"ERROR: Could not detect Ninja v1.5 or newer"

Is there some not displayed basic steps that I am missing or a concrete place where to put the ninja folder? Any help would be much appreciated. 

Thanks!

**Comment by Rondom** [comment]
Usually, installing ninja from your package manager should be fine.
If, for some reason, that is not an option, make sure that ninja is in your PATH, i.e. you can run ninja --version without any errors.
