### ISSUE TITLE
Install script ignores prefix variable when installing fuse3 init script

### ISSUE THREAD

**Issue by bobrofon** [libfuse/libfuse#489]
# How to reproduce
```
git clone https://github.com/libfuse/libfuse.git
meson --prefix="${PWD}/prefix" -Duseroot=false -Dudevrulesdir="${PWD}/prefix/lib/udev/rules.d" libfuse build
ninja -C build install
```
```
Installing /home/ubuntu/libfuse/doc/mount.fuse3.8 to /home/ubuntu/prefix/share/man/man8
Installing /home/ubuntu/build/meson-private/fuse3.pc to /home/ubuntu/prefix/lib/x86_64-linux-gnu/pkgconfig
Running custom install script '/home/ubuntu/libfuse/util/install_helper.sh /home/ubuntu/prefix/etc /home/ubuntu/prefix/bin /home/ubuntu/prefix/lib/udev/rules.d false'
install: cannot create regular file '/etc/init.d/fuse3': Permission denied
Failed to run install script '/home/ubuntu/libfuse/util/install_helper.sh /home/ubuntu/prefix/etc /home/ubuntu/prefix/bin /home/ubuntu/prefix/lib/udev/rules.d false'
FAILED: meson-install 
```
# Problem
install_helper.sh is trying to install `util/init_script` into `/etc/init.d/fuse3` even if prefix is specified. It is possible to solve problem by adding DESTDIR environment variable but the installation of `init.d/fuse3` becomes inconsitent with the installation of other configuration files. All other configuration files are installing into sysconfdir directory and according to [GNU coding standarts](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) I assume that `init.d/fuse3` is also should do this.

**Comment by Nikratio** [comment]
I disagree with the GNU standards here. An init script in /usr/local is pointless. The init script is deliberately installed into /etc if libfuse installed into /usr/local.

**Comment by bobrofon** [comment]
> An init script in /usr/local is pointless.

It is not absolutely true. I am working with embedded linux system which doesn't have /etc on purpose and runs init scripts in /vendor/etc/init.d. And even if init script is pointless in some installations there is no option not to install it.

You can disagree with the GNU standards, but enforcing to install scripts into /etc/ without any other options is not a perfect decision if you are not a maintainer of target operating system.

As a workaround I can offer to add a meson option to redefine init scripts location(by analog with udevrulesdir).

**Comment by Nikratio** [comment]
Closing this. As I said above, I do not consider this a bug. In the few cases where a different location makes sense, the script can be manually moved.
