### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by mlevy5722** [libfuse/libfuse#521]
the install doe snot pas the ninja,
I keep getting same exact error.

My system:
Centos 7
and I tried with the last 3 stable versions:
fuse-3.9.0.tar.xz
fuse-3.9.1.tar.xz
fuse-3.9.2.tar.xz

still same exact error message.

here is the trace below.

Any help/hint/pointers would be great.

Thank you.

===========================================================
[root@mdev03 build]#
[root@mdev03 build]# ninja
[1/2] Compiling C++ object 'example/example@@passthrough_hp@exe/passthrough_hp.cc.o'.
FAILED: example/example@@passthrough_hp@exe/passthrough_hp.cc.o
c++ -Iexample/example@@passthrough_hp@exe -Iexample -I../example -Iinclude -I../include -Ilib -I../lib -I. -I../ -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O2 -g -D_REENTRANT -DHAVE_CONFIG_H -D_GNU_SOURCE -Wall -Wextra -Wno-sign-compare -std=c++11 -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -pthread  -MD -MQ 'example/example@@passthrough_hp@exe/passthrough_hp.cc.o' -MF 'example/example@@passthrough_hp@exe/passthrough_hp.cc.o.d' -o 'example/example@@passthrough_hp@exe/passthrough_hp.cc.o' -c ../example/passthrough_hp.cc
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::mutex’ [-Wmissing-field-initializers]
 static Fs fs{};
              ^
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::inodes’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::root’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::debug’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::source’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::blocksize’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::src_dev’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::nosplice’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:156:14: warning: missing initializer for member ‘Fs::nocache’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc: In function ‘int do_lookup(fuse_ino_t, const char*, fuse_entry_param*)’:
../example/passthrough_hp.cc:362:27: error: invalid initialization of non-const reference of type ‘Inode&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     Inode& inode {*inode_p};
                           ^
../example/passthrough_hp.cc: In function ‘void sfs_lookup(fuse_req_t, fuse_ino_t, const char*)’:
../example/passthrough_hp.cc:395:25: warning: missing initializer for member ‘fuse_entry_param::ino’ [-Wmissing-field-initializers]
     fuse_entry_param e {};
                         ^
../example/passthrough_hp.cc:395:25: warning: missing initializer for member ‘fuse_entry_param::generation’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:395:25: warning: missing initializer for member ‘fuse_entry_param::attr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:395:25: warning: missing initializer for member ‘fuse_entry_param::attr_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:395:25: warning: missing initializer for member ‘fuse_entry_param::entry_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc: In function ‘void sfs_link(fuse_req_t, fuse_ino_t, fuse_ino_t, const char*)’:
../example/passthrough_hp.cc:482:25: warning: missing initializer for member ‘fuse_entry_param::ino’ [-Wmissing-field-initializers]
     fuse_entry_param e {};
                         ^
../example/passthrough_hp.cc:482:25: warning: missing initializer for member ‘fuse_entry_param::generation’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:482:25: warning: missing initializer for member ‘fuse_entry_param::attr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:482:25: warning: missing initializer for member ‘fuse_entry_param::attr_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:482:25: warning: missing initializer for member ‘fuse_entry_param::entry_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc: In function ‘void do_readdir(fuse_req_t, fuse_ino_t, size_t, off_t, fuse_file_info*, int)’:
../example/passthrough_hp.cc:703:28: warning: missing initializer for member ‘fuse_entry_param::ino’ [-Wmissing-field-initializers]
         fuse_entry_param e{};
                            ^
../example/passthrough_hp.cc:703:28: warning: missing initializer for member ‘fuse_entry_param::generation’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:703:28: warning: missing initializer for member ‘fuse_entry_param::attr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:703:28: warning: missing initializer for member ‘fuse_entry_param::attr_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:703:28: warning: missing initializer for member ‘fuse_entry_param::entry_timeout’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc: In function ‘void sfs_write_buf(fuse_req_t, fuse_ino_t, fuse_bufvec*, off_t, fuse_file_info*)’:
../example/passthrough_hp.cc:922:44: error: cannot convert ‘std::initializer_list<long unsigned int>’ to ‘size_t {aka long unsigned int}’ for argument ‘2’ to ‘void do_write_buf(fuse_req_t, size_t, off_t, fuse_bufvec*, fuse_file_info*)’
     do_write_buf(req, size, off, in_buf, fi);
                                            ^
../example/passthrough_hp.cc: In function ‘void maximize_fd_limit()’:
../example/passthrough_hp.cc:1197:24: warning: missing initializer for member ‘rlimit::rlim_cur’ [-Wmissing-field-initializers]
     struct rlimit lim {};
                        ^
../example/passthrough_hp.cc:1197:24: warning: missing initializer for member ‘rlimit::rlim_max’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc: In function ‘int main(int, char**)’:
../example/passthrough_hp.cc:1224:26: error: ‘class std::initializer_list<cxxopts::ParseResult>’ has no member named ‘count’
     fs.timeout = options.count("nocache") ? 0 : 86400.0;
                          ^
../example/passthrough_hp.cc:1243:18: error: ‘class std::initializer_list<cxxopts::ParseResult>’ has no member named ‘count’
         (options.count("debug-fuse") && fuse_opt_add_arg(&args, "-odebug")))
                  ^
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::init’ [-Wmissing-field-initializers]
     fuse_lowlevel_ops sfs_oper {};
                                 ^
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::destroy’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::lookup’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::forget’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::getattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::setattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::readlink’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::mknod’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::mkdir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::unlink’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::rmdir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::symlink’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::rename’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::link’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::open’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::read’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::write’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::flush’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::release’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::fsync’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::opendir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::readdir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::releasedir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::fsyncdir’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::statfs’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::setxattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::getxattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::listxattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::removexattr’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::access’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::create’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::getlk’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::setlk’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::bmap’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::ioctl’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::poll’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::write_buf’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::retrieve_reply’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::forget_multi’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::flock’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::fallocate’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::readdirplus’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::copy_file_range’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1246:33: warning: missing initializer for member ‘fuse_lowlevel_ops::lseek’ [-Wmissing-field-initializers]
../example/passthrough_hp.cc:1264:17: error: ‘class std::initializer_list<cxxopts::ParseResult>’ has no member named ‘count’
     if (options.count("single"))
                 ^
ninja: build stopped: subcommand failed.
[root@mdev03 build]#

===========================================================

In my opinion the first 2 lines of he error messages must be real critical, but I really do not understand them:
=======================================
[1/2] Compiling C++ object 'example/example@@passthrough_hp@exe/passthrough_hp.cc.o'.
FAILED: example/example@@passthrough_hp@exe/passthrough_hp.cc.o
......
==========================================

Thank you.

**Comment by koba-e964** [comment]
This quick-fix worked (at least for me): https://github.com/koba-e964/libfuse/tree/fix-initializer-list

**Comment by Nikratio** [comment]
Alternatively, upgrading your C++ compiler should help.

**Comment by partizanes** [comment]
You can use this point for Centos 7

yum install centos-release-scl
scl enable devtoolset-7 bash

Check:
gcc --version

And try rebuild.

**Comment by waynecn** [comment]
![ninja-builderrors](https://user-images.githubusercontent.com/5299551/180971674-b60a6451-54ab-4134-ad2a-cf34dc3cc62e.png)
same error when building libfuse release package, libfuse version: 3.11.0
