### ISSUE TITLE
Release path convention "broken"

### ISSUE THREAD

**Issue by tomharvey** [libfuse/libfuse#53]
There's not been much of a convention in past releases, but it looks like you've switched from using underscores to periods in the version identifier. 2_9_5 has become 2.9.6

https://github.com/libfuse/libfuse/releases/download/fuse-2.9.6/fuse-2.9.6.tar.gz
https://github.com/libfuse/libfuse/releases/download/fuse_2_9_5/fuse-2.9.5.tar.gz
https://github.com/libfuse/libfuse/releases/download/fuse_2_9_4/fuse-2.3.0.tar.gz

Can you settle on one way or the other? It's making it hard to automate the install, specifically through the chef receive at https://github.com/twilson63/s3fs-recipe

**Comment by Nikratio** [comment]
Dots will be the convention in the foreseeable future
