### ISSUE TITLE
Remote filesystem trick?

### ISSUE THREAD

**Issue by amoffat** [libfuse/libfuse#531]
Hi, what's the trick to making a filesystem identify as "remote"/non-local? I am asking because some file managers seem to aggressively index local filesystems. The issue I am having is that my fuse filesystem is dynamically generated, and has near-infinite nesting of subdirectories and files...so the file manager threads use up an enormous amount of CPU trying to browse to the bottom of the tree as quickly as possible. I am hoping that if I can tell fuse to report my filesystem as a non-local filesystem, some file managers will stop being so aggressive.

I've looked at sshfs and I don't see anything special they are doing. There seem to be various reports around a `_netdev` option existing at some point in fuse's history. Can anyone point me in the right direction? Thanks.

**Comment by trapexit** [comment]
https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=lib/mountlist.c;h=ca1be63f21ec44f5bee8b1e5400ba391005c5934;hb=HEAD#l229

That's how gnulib, used by df and many other tools, determines if a mount is remote. If you include a colon in the fsname it should generally get picked up as remote.

**Comment by amoffat** [comment]
Thanks @trapexit. I must be seeing another issue then, since my fsname does have a ":" in it:

```
$ df -T
...
supertag:myfiles                    fuse.manifold  104857600         0  104857600   0% /mnt/myfiles
```

Then it seems like neither Thunar nor Nautilus/Gnome Files are respecting remote filesystems then by not spidering them. I haven't confirmed if they also do this with sshfs, so that may have been a bad assumption on my part (assuming that they didn't do this with sshfs).

I've tried fiddling with the "subtype" so that it reports as a known network filesystem, so in my example, having the second column report "fuse.nfs" for example, but no luck wrt the spidering there either.

Seems like the problem might not be resolved via fuse reporting the filesystem as remote (since I already seem to be doing that), so closing this issue.

**Comment by trapexit** [comment]
Probably best to look into the filemanager code or talk with their teams and see if they're doing their own thing or using gnulib.

**Comment by amoffat** [comment]
Yeah. At least in the case of Thunar, it doesn't look like there is a way to short-circuit the spidering: https://github.com/xfce-mirror/thunar/blob/f81711e88e2a861d6f61b68b0dd4f58a497d0418/thunar/thunar-io-scan-directory.c. Seems to spider anything labelled a directory, nearly unconditionally.

**Comment by trapexit** [comment]
Sounds like a feature request...
