### ISSUE TITLE
When running meson ..  "ERROR: Pkg-config binary for machine MachineChoice.HOST not found. Giving up. "

### ISSUE THREAD

**Issue by Chord-Chen-30** [libfuse/libfuse#534]
When I run _$ meson .._ I got this. What does this mean and how should I solve this?
Let me know if I need to provide more information. 

> root@**** /***/fuse-3.9.2/build
# meson ..
The Meson build system
Version: 0.54.3
Source dir: /p300/fuse/fuse-3.9.2
Build dir: /p300/fuse/fuse-3.9.2/build
Build type: native build
Project name: libfuse3
Project version: 3.9.2
C compiler for the host machine: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609")
C linker for the host machine: cc ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "fork" : YES 
Checking for function "fstatat" : YES 
Checking for function "openat" : YES 
Checking for function "readlinkat" : YES 
Checking for function "pipe2" : YES 
Checking for function "splice" : YES 
Checking for function "vmsplice" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "fdatasync" : YES 
Checking for function "utimensat" : YES 
Checking for function "copy_file_range" : NO 
Checking for function "fallocate" : YES 
Checking for function "setxattr" : YES 
Checking for function "iconv" : YES 
Checking whether type "struct stat" has member "st_atim" : YES 
Checking whether type "struct stat" has member "st_atimespec" : NO 
Configuring config.h using configuration
../meson.build:68: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:68: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
../meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:72: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
../meson.build:72: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++11".
Message: Compiler warns about unused result even when casting to void
Run-time dependency threads found: YES
Library iconv found: NO
Library dl found: YES
Library rt found: YES
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Found CMake: /usr/bin/cmake (3.5.1)
Run-time dependency udev found: NO (tried cmake)

../util/meson.build:19:2: **ERROR: Pkg-config binary for machine MachineChoice.HOST not found. Giving up.**

A full log can be found at /p300/fuse/fuse-3.9.2/build/meson-logs/meson-log.txt

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by eddiegrinman** [comment]
I have the same issue. This seems like a basic installation problem for libfuse/sshfs. I'd appreciate any help on this matter.

**Comment by adrinjalali** [comment]
I had the same issue. But in archlinux, and `pacman -Sy pkgconf` solved the issue.

**Comment by congtri** [comment]
do you know how to solve it om mac?

**Comment by arabgb** [comment]
c x hn bvnhhn vbcn bvjuyj bcvfxnnhnhnjx z
 
 
 
 
 
 
 
 
 
 
 

             v x  vc GKM NVBK.  
X

**Comment by TheManchineel** [comment]
```sh
brew install pkg-config
```

works on Mac
