### ISSUE TITLE
#include <config.h> (examples/hello.c)

### ISSUE THREAD

**Issue by SmartArray** [libfuse/libfuse#54]
On line 38 in file [https://github.com/libfuse/libfuse/blob/master/example/hello.c](url)

For what reason has "config.h" been included?
When I remove that file, it compiles just fine.

The file can not be found on any of my systems?

**Comment by Nikratio** [comment]
It's generated in `include` when you run `./configure`. Including it is good practice, even if at the moment none of the #defines are used.

**Comment by SmartArray** [comment]
Thank you very much!

2016-06-14 19:04 GMT+02:00 Nikolaus Rath <notifications@github.com>:

> It's generated in include when you run ./configure. Including it is good
> practice, even if at the moment none of the #defines are used.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libfuse/libfuse/issues/54#issuecomment-225948051>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA5CwNC-VIDvzK36oObqlHymadY83neJks5qLt8YgaJpZM4I1Nad>
> .
>



-- 


        Julian Jäger
        Werner-Heisenberg-Weg 121 - Stw. 0129
        85579 München
        Deutschland

        Website: http://www.smartarray.org/
        Mail: jaeger@smartarray.org
