### ISSUE TITLE
Introduce an API version guard symbol preventing linking a library to an incompatible header

### ISSUE THREAD

**Issue by KOLANICH** [libfuse/libfuse#542]
Accidential linking to libfusev2 when using v3 headers can cause very srange errors. Unfortunately C has no name mangling.

The proposed solution is to
1. create a define with api version number
2. create an exported function doing nothing incorporating that number in its name
3. do something to ensure it is linking
4. increment version number on each change in functions prototypes.

So, there should be a link error when versions and headers have different api.

**Comment by Nikratio** [comment]
libfuse2 and libfuse3 have different sonames, so it should not be possible to accidentally use the wrong major version. This is most likely a usage error. 

If you still have the command history that resulted in incorrect linking, I'd suggest to send them to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel) and ask for advice there.

**Comment by KOLANICH** [comment]
In fact I had runtime errors. I took some project from GH and tried to compile it, but in headers it used paths <fuse/...> and linked against fuse 3. The result was weird memory errors. Finally  I have managed to sort that out. But I have spent some time debugging the issue.
