### ISSUE TITLE
Error while loading shared libraries: libfuse3.so.3 ... No such file or directory.

### ISSUE THREAD

**Issue by JohnnyC1234** [libfuse/libfuse#543]
When I compiled the hello.c program, and then executed it I got the error that the libfuse3.so file couldnt be found.

I see that the libfuse is installed under:
Installing lib/libfuse3.so.3.9.3 to /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.9.3

So I had to copy it to;
sudo cp /usr/local/lib/x86_64-linux-gnu/* /lib/x86_64-linux-gnu/
sudo cp -r /usr/local/lib/x86_64-linux-gnu/pkgconfig/ /lib/x86_64-linux-gnu/

Is it possible for the file libfuse3.so to be created in the /lib/x86_64-linux-gnu/
directory, during the installation.

**Comment by Nikratio** [comment]
Yes, you can configure the install locations with `meson configure`.
