### ISSUE TITLE
Kernel page cache corruption

### ISSUE THREAD

**Issue by Bockeman** [libfuse/libfuse#544]
I am using libfuse to recover data from HDDs that have been extracted from a hardware RAID-5 box where the hardware RAID controller has died. The controller is obsolete and cannot be replaced.  I can confirm that all 5 3TB HDDs are good, as far as I can tell, because a parity check for any location across the 5 devices returns a positive result and a checksum across the entire drive, taking about 8 hours per drive, gives consistent results when repeated.

I have written a fuse program, taken mostly from available examples, and added a parity check which is a luxury that my data set affords.  I mounted the 5 HDDs and did a further loop mount onto the partition holding the data.  When I do a simple sequential read, I get no parity errors.  However, when do something more complex, such as an "ls" or a "du", I can see that several blocks are being read simultaneously and I get random parity errors.

I amended my fuse program to repeat the read from any block with a parity error.  Most accesses with an initial parity error, return a parity correct result on the second attempt, though a few blocks require 6 or 7 attempts.  However, given the volume of data (~11TB) that I am attempting to recover, the possibility of a false parity pass (i.e. 5 random bytes which have a parity match) is high.  Indeed, when I do a "du" on the whole partition, I get  system errors.

The documentation for fuse_config::direct_io indicates that setting this configuration disables the use of page cache (file content cache) in the kernel for this filesystem.  I set this bit and now I get no parity errors and no system errors.

From this I conclude that something under the hood, such as the page cache, is not correctly allocating unique pointers to the allocated memory blocks, or something similar.  It looks like a kernel page cache corruption.

Do you see this a fuse issue or actually a issue with the kernel?

**Comment by Nikratio** [comment]
Thanks for the report! That'd be a kernel issue, libfuse doesn't look at the `direct_io` option at all, it just passes it through to the kernel.
