### ISSUE TITLE
Support for CUE/BIN files

### ISSUE THREAD

**Issue by rderooy** [libfuse/libfuse#546]
Feature request for being able to mount data tracks of CUE/BIN files.

The idea is that you can double click a CUE file, it would parse it and find the BIN file(s) and mount the data tracks. A CUE/BIN set can also contain audio tracks either as part of the BIN file or as separate WAVE/MP3/OGG/whatever audio files, and while it would be nice if those could also be supported as a "virtual cd", that is not the primary focus of this feature request.

One side note, GOG seems to have a habit of "hiding" their ISO and CUE/BIN files for retro games. There will typically be a .gog file which can be either an ISO or BIN file, and CUE will be named .inst
But that is really not that important, as you can easily rename them.

Alternatives:
- https://cdemu.sourceforge.io/
- https://sourceforge.net/projects/fuseiso/

You can also convert a CUE/BIN to ISO (which converts it to a single-track image), but I would rather not have to do that.

**Comment by Nikratio** [comment]
Thanks for the idea! This sounds like a great idea for a filesystem that could be based on libfuse. libfuse itself - however - is not intended to provide any specific filesystem. It's just a library to build filesystems.
