### ISSUE TITLE
fuse: failed to allocate request when mount without -s (after 14th parallel i/o operation)

### ISSUE THREAD

**Issue by lapsio** [libfuse/libfuse#552]
Hi I'm currently developing heavilty parallel FUSE filesystem and I noticed that I'm getting ridiculous amounts of "fuse: failed to allocate request" errors. Those errors are thrown by FUSE itself, before it even reaches my implementation of filesystem.

Errors don't occur when filesystem is mount with `-s` flag however they still **do** occur when I make my filesystem realistically singlethreaded by putting all fuse operations inside giant critical sections.

I believe it's due to fact that FUSE enqueues too many i/o operations in parallel and crashes due to being unable to allocate even more. When I intentionally put deadlock in all i/o operations FUSE log looks like this:

        lapsio@linux-qzuq ~/D/P/P/build-mess-Desktop-Debug> less fuse.log
        FUSE library version: 2.9.4
        nullpath_ok: 0
        nopath: 0
        utime_omit_ok: 0
        unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
        INIT: 7.24
        flags=0x0003f7fb
        max_readahead=0x00080000
           INIT: 7.19
           flags=0x00000011
           max_readahead=0x00080000
           max_write=0x00020000
           max_background=0
           congestion_threshold=0
           unique: 1, success, outsize: 40
        unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15121
        getattr /
        unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 4516
        opendir flags: 0x18800 /
        unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 15123
        LOOKUP /.xdg-volume-info
        getattr /.xdg-volume-info
           unique: 2, success, outsize: 120
        unique: 5, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 15121
        opendir flags: 0x18800 /
        unique: 6, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15332
        getattr /
        unique: 7, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15333
        getattr /
        unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15335
        opendir flags: 0x18800 /
        FUSE library version: 2.9.4
        nullpath_ok: 0
        nopath: 0
        utime_omit_ok: 0
        unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
        INIT: 7.24
        flags=0x0003f7fb
        max_readahead=0x00080000
           INIT: 7.19
           flags=0x00000011
           max_readahead=0x00080000
           max_write=0x00020000
           max_background=0
           congestion_threshold=0
           unique: 1, success, outsize: 40
        unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15121
        getattr /
        unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 4516
        opendir flags: 0x18800 /
        unique: 4, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 15123
        LOOKUP /.xdg-volume-info
        getattr /.xdg-volume-info
           unique: 2, success, outsize: 120
        unique: 5, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 15121
        opendir flags: 0x18800 /
        unique: 6, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15332
        getattr /
        unique: 7, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15333
        getattr /
        unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15335
        getattr /
        unique: 9, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15339
        getattr /
        unique: 10, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15342
        getattr /
        unique: 11, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15345
        getattr /
        unique: 12, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15348
        getattr /
        unique: 13, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15349
        fuse: failed to allocate worker structure
        unique: 14, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15350
        getattr /
        fuse: failed to allocate request
           unique: 14, error: -12 (Cannot allocate memory), outsize: 16
        fuse: failed to allocate worker structure
        unique: 15, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15353
        fuse: failed to allocate request
           unique: 15, error: -12 (Cannot allocate memory), outsize: 16
        fuse: failed to allocate worker structure
        unique: 16, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15346
        fuse: failed to allocate request
           unique: 16, error: -12 (Cannot allocate memory), outsize: 16
        fuse: failed to allocate worker structure
        unique: 17, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 15355
        fuse: failed to allocate request
           unique: 17, error: -12 (Cannot allocate memory), outsize: 16

Which seems to confirm my theory about exceeding queue size and crashing. Some applications (like KDE Dolphin) operate in heavily parallel manner and easily call more than 14 i/o operations at once - resulting in i/o errors shown to user.

I would rather expect FUSE to hang on mutex in such situation rather than just crash with i/o error. Is there any way to control this behavior? Due to ultra high latency of filesystem in certain cases, using it in single threaded mode is not acceptable for multi-user scenarios.

**Comment by trapexit** [comment]
If you look at the code that error comes from a failed call to calloc. 
Do you have overcommit memory disabled?

**Comment by lapsio** [comment]
I think I have auto:

    lapsio@linux-a7l6 ~> cat /proc/sys/vm/overcommit_memory 
    0

**Comment by trapexit** [comment]
Unless something odd is going on... you're running out of memory. Isn't 
really something libfuse can manage.

**Comment by lapsio** [comment]
There is in fact something unusual because this machine has 32 GB of RAM and this fs is using like 64mb tops . But also this machine has really old version of FUSE (2.9.4). It's throwing this error after 10th thread is allocated. iirc old FUSE versions had hard limit of 10 simultaneous threads and probably handling of more threads was a bit wonky at the time. Here's result of my test script in sh:

```sh
sh-4.2$ while true ; do
> ls mnt &
> sleep .1
> done
[1] 8771
[2] 8774
[3] 8777
[4] 8780
[5] 8783
[6] 8786
[7] 8789
[8] 8792
[9] 8795
ls: cannot access mnt: Cannot allocate memory
[9]+  Done(2)                 ls mnt
[9] 8797
ls: cannot access mnt: Cannot allocate memory
[9]+  Done(2)                 ls mnt
```

I did the same thing on my laptop with FUSE 2.9.7 and it works just fine (threads above 10th are just enqueued and waiting until earlier ones will finish. Which is exactly behavior I expected. As result I didn't experience any issues with my filesystem when it's running on machine with more recent libfuse.

I guess I consider it closed in such case.
