### ISSUE TITLE
passthrough_hp does not close any file handles

### ISSUE THREAD

**Issue by jasongibson** [libfuse/libfuse#555]
After compiling this example and running it on Ubuntu 18.04 4.4.0-171-generic, I noticed (by way of my session getting locked up) that it never frees any file handles that it opens.  Doing things like 'ls mountpoint' opens a couple files, then 'ls mountpoint/dir' opens some more, etc.  This is visible by looking at /proc/$pid/fd.  Eventually it'll run into the ulimit for open files as it is used more.

Barring changing its caching behavior, a comment in the source describing how it currently works would be nice.

This is as of commit 0105e061b97a97d9836128aea5bcdfc9593c9b82.

Thank you.

(I realize this will be auto-closed without a patch, but maybe it'll be useful for onlookers.)

**Comment by Nikratio** [comment]
Are you sure about that? I suspect it may simply not free them as early/quickly as you expect. Fds should be closed as soon as the corresponding dentry is removed from the kernel cache, and the kernel does not release them unless there is memory pressure.

Try `cat 1 > /proc/sys/vm/drop_caches` to force a cache flush, that should also see the fds closed.

**Comment by jasongibson** [comment]
Thanks for the info.  If it does eventually do it on its own, it can take a long time (such that it'd be easy to characterize how I originally did).  Setting drop_caches to 2 does free up the fds.
