### ISSUE TITLE
io_uring support

### ISSUE THREAD

**Issue by pwang7** [libfuse/libfuse#562]
Is it possible that libfuse can support io_uring? So that FUSE can support Linux native async IO.

**Comment by Nikratio** [comment]
Thanks for bringing this up!

As far as I can tell, this is a question about the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response or discussion, let alone in them being addressed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood your question.

**Comment by akvadrako** [comment]
I'm not sure what the original asker meant, but do you think libfuse would get a benefit from using io_uring like https://github.com/uroni/fuseuring does?

**Comment by xin3liang** [comment]
FYI, a new feature in Linux 6.14
https://docs.kernel.org/next/filesystems/fuse-io-uring.html

**Comment by bsbernd** [comment]
The current libfuse maintainer is the author of that ;)  

https://github.com/bsbernd/libfuse/tree/uring

I hope that I find time today to make a clean PR out of that branch.
