### ISSUE TITLE
build fails with un-helpful error message

### ISSUE THREAD

**Issue by bkerin** [libfuse/libfuse#566]
I followed the instructions in README.md but it says:

$ meson ..
The Meson build system
Version: 0.21.0
Source dir: /home/bkerin/tmp/fuse-3.10.0
Build dir: /home/bkerin/tmp/fuse-3.10.0/build
Build type: native build

Meson encountered an error in file meson.build, line 8, column 42:
lexer

Sounds like a parse failure on meson.build itself but I can't tell for sure

**Comment by Nikratio** [comment]
You're using a very old meson verson - so old that it can't even parse the minimum required version (0.42). Please update to a less antiquated meson :-).
