### ISSUE TITLE
Pass fuse_file_info in chown, chmod, utimensat, etc

### ISSUE THREAD

**Issue by jabolopes** [libfuse/libfuse#58]
Hi,

I would like to get the file handle that was set in open when fchown, fchmod, and futimens are called.
This is necessary to distinguish between syscalls, such as, chown and fchown, which make a difference
when the underlying implementantion is inode-based and not path-based.

Is it possible to create new FUSE handlers fchown, fchmod, futimens, that receive the fuse_file_info
structure, which contains the file handle created in open?

Thanks,
Jose

**Comment by Nikratio** [comment]
Possible? yes. Possible without breaking backwards compatibility? Probably awkward. A good idea? Probably not :-). If your file system is inode based, then you should be using the low-level API (see `fuse_lowlevel.h`). But let's continue the discussion on the fuse mailing list, since this isn't a bug.

**Comment by Nikratio** [comment]
As discussed on the mailing list, this may actually be a good fit for FUSE3 to complement the existing truncate/ftruncate, getattr/fgetattr handlers. Pull requests are welcome!

**Comment by Nikratio** [comment]
If you'd like to see this added in FUSE 3, please submit a pull request in the next 2 weeks or so.

**Comment by jabolopes** [comment]
Hi,

I am working on a patch. Can you help me with some info?

I need to add this comment as the docstring of the fchmod. What is the
version of the Linux kernel?

* If this method is not implemented or under Linux kernel
* versions earlier than X.X.X, the chmod() method will be
* called instead.

What is the license for the repository? Can you provide a URL to the
license file?

Thanks,
Jose

On Mon, Oct 3, 2016 at 6:23 PM Nikolaus Rath <notifications@github.com>
wrote:

If you'd like to see this added in FUSE 3, please submit a pull request in
the next 2 weeks or so.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libfuse/libfuse/issues/58#issuecomment-251153199>, or mute
the thread

**Comment by jabolopes** [comment]
Hi,

I found the URL to the license file. I only need to know the kernel version.

Thanks,
Jose

**Comment by Nikratio** [comment]
Uhm. I thought this required only changes in the high-level API? In this case it's independent of the kernel version.

**Comment by Nikratio** [comment]
After thinking about this for a while, I think a better solution is to add a `struct fuse_file_info` parameter to chown, chmod etc (as the issue title suggests) instead of adding separate fchown, fchmod functions. My rationale is that probably the majority of file systems would implement a helper function that is called by both request handlers to do  the actual work anyway. In that case there is no point in having separate handlers.

So unless someone has a convincing argument against this, I will add the additional argument to the existing functions, and actually drop `ftruncate` and `fgetattr`.

**Comment by jabolopes** [comment]
Sounds good to me. Just to clarify what you are proposing, a client can
determine if the syscall was e.g. chmod or fchmod by checking if the
pointer to the fuse file info struct is null or not, right?

**Comment by Nikratio** [comment]
I am not sure about that one, you'd need to check the fuse kernel source to be sure. It is possible that if one processes calls chmod(), the FUSE file system still receives a fuse_file_info that is non-NULL if the same file is currently open in a different process.

But that applies no matter if you have two separate handler functions or not.

**Comment by jabolopes** [comment]
There is a reference to ftruncate in a docstring in fuse.h that should be
removed. Line 90.

On Mon, Oct 17, 2016 at 4:55 AM Nikolaus Rath <notifications@github.com>
wrote:

Closed #58 <https://github.com/libfuse/libfuse/issues/58> via 73b6ff4
<https://github.com/libfuse/libfuse/commit/73b6ff4b75cf1228ea61262c293fcb2fda5dfeea>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libfuse/libfuse/issues/58#event-825346030>, or mute the
thread

**Comment by jabolopes** [comment]
The next step would be to also add the fuse_file_info to getxattr,
setxattr, listxattr, and removexattr, since they also have file descriptor
variants in the system calls.

What do you think?

On Mon, Oct 17, 2016 at 1:39 PM Jose Lopes <jabolopes@gmail.com> wrote:

There is a reference to ftruncate in a docstring in fuse.h that should be
removed. Line 90.

On Mon, Oct 17, 2016 at 4:55 AM Nikolaus Rath <notifications@github.com>
wrote:

Closed #58 <https://github.com/libfuse/libfuse/issues/58> via 73b6ff4
<https://github.com/libfuse/libfuse/commit/73b6ff4b75cf1228ea61262c293fcb2fda5dfeea>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libfuse/libfuse/issues/58#event-825346030>, or mute the
thread

**Comment by Nikratio** [comment]
Probably makes sense. Any others (in addition to xattr*)?

**Comment by jabolopes** [comment]
I cross checked all the fuse operations against the man pages to see which
syscalls had
file descriptor variants and I think the xattr related are the only ones
left. However, it would
be nice if someone could double check to make sure I didn't miss any
syscall.

**Comment by Nikratio** [comment]
Were you able to test if the changes actually work? I just did a cursory check, and it looks to me as if the `fi` argument to `getattr` is always NULL, even if the file is open...

**Comment by Nikratio** [comment]
Adding a fuse_file_info argument to the xattr handlers would require a kernel patch. At the moment, the kernel does not provide this information.

**Comment by Nikratio** [comment]
Regarding `getattr`: when testing with `example/passthrough_fh`, it seems that

```
>>> f = open('testfile', 'r+')
>>> os.fstat(f.fileno())
```
results in a getattr call with `fi == NULL`. However,
```
>>> os.ftruncate(f.fileno(), 50)
```
results in *truncate* with *fi* defined, followed by *getattr* with *fi* defined. Weird.

**Comment by jabolopes** [comment]
Hi,

I was investigating this issue. I tested fstat, fchmod, and ftruncate similarly to how you did.

fstat: fuse_file_info is NULL because in fuse_lowlevel.c line 612 the "if"

  if (arg->getattr_flags & FUSE_GETATTR_FH) {

is always false, because arg->getattr_flags is 0. So the kernel is not passing the file handle.

fchmod: fuse_file_info is NULL because in fuse_lowlevel.c line 637 the "if"

  if (arg->valid & FATTR_FH) {

is also false because "valid" is 1 which masks out FATTR_FH.

ftruncate: fuse_file_info is not NULL because "valid" is some number (like 584) that masks in FATTR_FH, so the code enters the if and sets the file handle.

I think the problem is on the kernel side. 
It might even be related to https://github.com/libfuse/libfuse/issues/62
What do you think?

**Comment by Nikratio** [comment]
Yes, this looks like a kernel issue.

**Comment by Nikratio** [comment]
I'm closing this because we already have #62, and on the libfuse side all the pieces are now present.
