### ISSUE TITLE
auto_unmount doesn't work without allow_other

### ISSUE THREAD

**Issue by mahkoh** [libfuse/libfuse#586]
In https://github.com/libfuse/libfuse/blob/77d662459a0fcdf358d515477d33795837e859d5/util/fusermount.c#L1219 `open` is executed as root which does not have access to the mount point if allow_other was not used and the real user id is not 0. Since allow_other usually cannot be specified by unprivileged users, auto_unmount has no effect for unprivileged users.

@kevin-vigor Should we maybe drop privileges before calling `open`?

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue!

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

This is just to calibrate expectations. I am grateful that you took the time and effort to report this! I'll leave this issue open to document the problem and who knows, maybe someone will pick it up after all :-).

**Comment by matthiasgoergens** [comment]
@mahkoh @Nikratio I gave addressing this issue a try in https://github.com/libfuse/libfuse/pull/754.  Please have a look.  Thanks!

**Comment by Feverfew** [comment]
@matthiasgoergens I tried fixing this [some time ago](https://invent.kde.org/system/kio-fuse/-/issues/180) by dropping privileges too, but with the key difference being that I didn't do this in a forked child process. Do you know why that forking is necessary here?

**Comment by matthiasgoergens** [comment]
I forked, because the kind of privilege dropping that is required to get past a missing allow_other is not reversible.

The reversible privilege dropping that fusermount already does isn't enough.
