### ISSUE TITLE
Can libfuse be built in windows?

### ISSUE THREAD

**Issue by yiylin** [libfuse/libfuse#6]

**Comment by Nikratio** [comment]
No.

**Comment by Maxhy** [comment]
For Windows, we (Dokan/Dokany folks) are making a library that makes our Windows user-mode file system library compatible with FUSE using libfuse headers. See https://github.com/dokan-dev/dokany/tree/master/dokan_fuse on https://github.com/dokan-dev/dokany project.
This makes your libfuse filesystem working on Windows too, I believe it is what you are looking for.

**Comment by yiylin** [comment]
Thanks for your reply. Is Dokan a Portable Application? @Maxhy

**Comment by Maxhy** [comment]
What do you mean by portable? It is highly related to Windows kernel and will only work on Windows then. But there is a fuse compatible API, by using it you should be able to have an user-mode file system on Linux using libfuse and on Windows using Dokan with dokan_fuse library.
