### ISSUE TITLE
Does libfuse support LVM?

### ISSUE THREAD

**Issue by ashione** [libfuse/libfuse#60]
I use fuse to design a software for mounting lvm on linux system. 
But faild and its log is folloing '
_warning: command line show the following error msg :
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
   missing codepage or helper program, or other error
   In some cases useful info is found in syslog - try
   dmesg | tail  or so_

**Comment by mrvn** [comment]
How has that got anything to do with fuse or lvm? Neither is involved in mounting /dev/loop0

**Comment by Nikratio** [comment]
The question does not make sense for me either

**Comment by Nikratio** [comment]
The question does not make sense for me either

**Comment by Nikratio** [comment]
The question does not make sense for me either
