### ISSUE TITLE
fuse_operations::utimens not called when updating modification time only

### ISSUE THREAD

**Issue by smessmer** [libfuse/libfuse#603]
When calling `touch -d` on a file under a fuse file system, it correctly calls `fuse_operations::utimens`, but when calling `touch -md` (i.e. instructing touch to only update modification time), I see the `SETATTR` call in the fuse log, but `fuse_operations::utimens` never gets called, giving the file system no chance to handle it.

Reported here: https://github.com/cryfs/cryfs/issues/379

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is fully volunteer driven. This means new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches.

In this case, my suggestion would be to write a unit test that reproduces this problem using one of the example filesystems (just to rule out it being an issue in cryfs).

**Comment by jpandre** [comment]
FYI I could not reproduce this supposed bug, maybe there are conditions for it to show.
(I asked for information on https://github.com/cryfs/cryfs/issues/379)
