### ISSUE TITLE
The 'Add' button is grayed out

### ISSUE THREAD

**Issue by stepnjump** [libfuse/libfuse#622]
Hi,

I just installed this app under Linux Mint 20.2 Cinnamon.
As prompted, I installed also gocryptfs and cryfs. Even though I see them both 
populating the dropdown box, even though I fill all the fields requested, the top-right button 
labeled: 'Add' stays grayed-out so it's not clickable.

Great project. It's awesome. Great initiative.
I would love for this to work. I've been waiting for an easy solution to encrypt a few files here and there under gnome and when I found your application, I was quite hopeful.

Thank you.
I hope this will help.
Please let me know if I might do anything else to help in possibly providing with more info as needed.

![vaults](https://user-images.githubusercontent.com/8755316/129377434-56d870be-994f-4ad5-a513-f2c299a028fa.png)

**Comment by Nikratio** [comment]
Hi! I'm afraid you are on the wrong bugtracker. libfuse does not have any dialogs at all.

**Comment by stepnjump** [comment]
Ooops... I'm so sorry... thanks for letting me know Nikratio
