### ISSUE TITLE
Hardcoded /etc in install script

### ISSUE THREAD

**Issue by JayDoubleu** [libfuse/libfuse#643]
Please consider https://github.com/libfuse/libfuse/blob/master/util/install_helper.sh#L43 `%{_sysconfdir}` instead of hardcoded `/etc`. When building fuse3 as dependency for some other apps flatpak builds will fail as they don't use /etc

**Comment by Nikratio** [comment]
Sorry, this has been discussed at length. Please look at previous bugs and pull requests. In short, _sysconfdir defaults to `/usr/local/etc`, which means that udev rules and init scripts won't work on most systems.
