### ISSUE TITLE
libfuse can not work with seekdir function

### ISSUE THREAD

**Issue by TraumLou** [libfuse/libfuse#65]
here is the detailed discussion:
https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/AANLkTinZZqRJdow2kpJ-rdKmAiFwmGvkKNvmZw-kMMk_%40mail.gmail.com/#msg25715232

this is code:

```
#include <dirent.h>
#include <stdio.h>

int
main (int argc, char *argv[])
{
   DIR *d = opendir(argv[1]);
   printf("opened %s\n", argv[1]);
   struct dirent *e = readdir(d);
   long int pos = 0;
   int i = 0;
   while (e) {
       printf("%li %s\n", e->d_fileno, e->d_name);
       e = readdir(d);
       if (i == 5) {
           pos = telldir(d);
           printf(" => Position: %li\n", pos);
       }
       i++;
   }
   if (pos) {
       printf(" => read %s at Position %li:\n", argv[1], pos);
       seekdir(d, pos);
       e = readdir(d);
       printf("%li %s\n", e->d_fileno, e->d_name);
   }
   closedir(d);
   return 0;
}
```

the runtime environment is :centos6 and centos7
the libfuse version is:2.8.3 and 2.9.2
this program can be run normally in local filesystem like ext4,
but I use the fusexmp_fh.c to test this program, it will coredump,
and I also use the osxfuse to test it. everything is ok.
I think there might be some bugs in here, osxfuse fix it while libfuse not.

I hope you can find out and fix it.

**Comment by mrvn** [comment]
Please run fusexmp_fh with debug enabled and include its output. Also use gdb to create a stack backtrace of the crash and add both to this issue.

**Comment by TraumLou** [comment]
fuse debug output:

[root@TraumLou fuse]# ./a.out /mnt/myfuse -d
FUSE library version: 2.8.3
nullpath_ok: 1
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56
INIT: 7.13
flags=0x0000307b
max_readahead=0x00020000
   INIT: 7.12
   flags=0x00000013
   max_readahead=0x00020000
   max_write=0x00020000
   unique: 1, success, outsize: 40
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 45
LOOKUP /root
getattr /root
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: OPENDIR (27), nodeid: 2, insize: 48
opendir flags: 0x98800 /root
   opendir[139703944743712] flags: 0x98800 /root
   unique: 3, success, outsize: 32
unique: 4, opcode: READDIR (28), nodeid: 2, insize: 80
readdir[139703944743712] from 0
   unique: 4, success, outsize: 1176
unique: 5, opcode: READDIR (28), nodeid: 2, insize: 80
readdir[139703944743712] from 9223372036854775807
   unique: 5, success, outsize: 16
unique: 6, opcode: READDIR (28), nodeid: 2, insize: 80
   unique: 6, success, outsize: 16
unique: 7, opcode: RELEASEDIR (29), nodeid: 2, insize: 64
releasedir[139703944743712] flags: 0x0
   unique: 7, success, outsize: 16
unique: 8, opcode: FORGET (2), nodeid: 2, insize: 48
FORGET 2/1
DELETE: 2

[readdir-core.zip](https://github.com/libfuse/libfuse/files/373042/readdir-core.zip)

**Comment by mrvn** [comment]
What am I supposed to do with your core file?

Core was generated by `./readdir /mnt/myfuse/root'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004007d7 in ?? ()
(gdb) bt
#0  0x00000000004007d7 in ?? ()
#1  0x00007fff9637bfa8 in ?? ()
#2  0x0000000200400865 in ?? ()
#3  0x0000000001999010 in ?? ()
#4  0x0000000000000000 in ?? ()

That core file is pretty useless for anyone but you.

**Comment by Nikratio** [comment]
@TraumLou Please make sure that you compile fuse yourself from the tarball, and include  debugging info. Don't use the CentOS packages.

**Comment by TraumLou** [comment]
I'm so sorry...... I install fuse from CentOS yum, I will compile and try again.

**Comment by Nikratio** [comment]
I'll close this for now, please feel free to reopen with a more useful stacktrace. Thanks!
