### ISSUE TITLE
Was the option delay_connect removed?

### ISSUE THREAD

**Issue by SimonLiuhd** [libfuse/libfuse#650]
Hi all,

I need the "-o delay_connect" to wait for some dependent services, but the error message is "unknown option delay_connect".
Does the option "delay_connect" option have beem removed? Or is there other way to achieve the requirement?

Thanks in advance.
Simon

**Comment by Nikratio** [comment]
I think you got something mixed up. libfuse never had such a option. Maybe you are talking SSHFS? In that case you got the wrong Github project.
