### ISSUE TITLE
How can open testcase in fuse-2.9.9

### ISSUE THREAD

**Issue by hifi521** [libfuse/libfuse#663]
Hello, I want know how can I run testcase in fuse-2.9.9.

> [root@localhost libfuse]# cd test/
[root@localhost test]# ls
Makefile  stracedecode.c  test.c

Thanks in advance!

**Comment by Nikratio** [comment]
This is not supported, if I remember correctly.

**Comment by hifi521** [comment]
> 如果我没记错的话，这是不支持的。

 Thanks.

**Comment by hifi521** [comment]
> This is not supported, if I remember correctly.

If test cases are not supported, what is in the test directory
