### ISSUE TITLE
Is it possible to build libfuse without udev?

### ISSUE THREAD

**Issue by th0ma7** [libfuse/libfuse#668]
Up to release 2.9.9 it was possible to build libfuse using the old `configure` without the need for `udev` for embeded systems.  Is this still feasible with the 3.x version?

```
Found pkg-config: /usr/bin/pkg-config (0.29)
Found CMake: /usr/bin/cmake (3.13.4)
Run-time dependency udev found: NO (tried pkgconfig and cmake)

util/meson.build:19:2: ERROR: Dependency "udev" not found, tried pkgconfig and cmake

A full log can be found at /home/spksrc/borg-fuse/spksrc/cross/fuse3/work-x64-7.0/libfuse-fuse-3.10.5/builddir/meson-logs/meson-log.txt
```

**Comment by Nikratio** [comment]
udev is only used to determine `udevrulesdir`. You can set this manually, then Meson will not need udev.

**Comment by th0ma7** [comment]
Thnx @Nikratio much appreciated!

I probably passed by it but just can't find it, where can I find documentation on known args that can be passed to Meson for libfuser with examples?

**Comment by eli-schwartz** [comment]
As `./configure --help` is to autotools build options, so too `meson configure` is to Meson build options.

(Run it in the source tree to see options before building. Run it in the build tree to see options with their current values.)

**Comment by th0ma7** [comment]
I didn't knew that, thnx mate!
