### ISSUE TITLE
Document that pid may be zero

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#67]
The pid provided by the fuse kernel module is not always valid. For example, when a file system is accessed from a different pid namespace there is no valid pid that could be used. We should document this.

**Comment by mrvn** [comment]
Wouldn't it be better to add functions to fuse to access the pid namespace?
Also, is this relevant when letting the kernel to access checks?

**Comment by dsheets** [comment]
This issue confuses me. I believe the pid reported by fuse when accessed from a pid namespace is the mapped kernel thread id in the root namespace. I am currently using a fuse file system running in the root pid namespace and accessing it from Docker containers and the pid/tid is accurate.

Sometimes, the pid is 0 but this does not seem to do with namespaces. Rather, messages delivered with pid 0 indicate that the message was generated by the kernel itself. For instance, `FORGET` and `BATCH_FORGET` are issued directly by the kernel and don't have corresponding threads generating them.

Is there more to this issue that I'm missing? Thanks.

**Comment by Nikratio** [comment]
@dsheets Think about a fuse fs running in a new namespace that's accessed from the root namespace.

@mrvn This is (or rather, can be) relevant whenever you use the pid for something. Access checks are one good example.

**Comment by mrvn** [comment]
@Nikratio I'm aware of access checks but I always found the kernel does them better. I was asking if you had other use cases in mind.

**Comment by Nikratio** [comment]
@mrvn Not on top of my head. But I'd be surprised if there weren't file systems out there who used them for something. That's why I think it's important to document that the pid isn't always meaningful.
