### ISSUE TITLE
fusermount, fusermount3,... fusermountN compatibility guarantees? 

### ISSUE THREAD

**Issue by probonopd** [libfuse/libfuse#670]
Are there any compatibility guarantees with regard to `fusermount`, `fusermount3`,... `fusermountN`? 

AppImages currently rely on the `fusermount` binary being there. Some distributions are now shipping `fusermount3` by default. One day they might ship `fusermount4`,... `fusermountN`.

It would be very valuable to know for sure that future versions of `fusermount` will continue to be compatible to earlier ones, so that things like

https://github.com/hanwen/go-fuse/commit/934a183ed91446d218b5471c4df9f93db039f6e1

could be made to work not just for  `fusermount` and `fusermount3`, but also for future versions.

**Comment by Nikratio** [comment]
There are no compatibility guarantees. However, multiple major versions of libfuse are intended to be co-installable, and the right version of fusermount should be pulled in automatically through the dependency on the right libfuse shared library.

**Comment by Nikratio** [comment]
As I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

**Comment by probonopd** [comment]
Thanks for your response @Nikratio. Please consider to enable GitHub Discussions for this repository.

I tend to avoid mailing lists for multiple reasons:
* Mailing lists "spam" you with many mails about subjects you have no interest in. I only want notifications about this issue, not about everything
* Mailing lists expose your mail address
* Mailing lists don't let you edit your posts

GitHub Discussions doesn't have these disadvantages.

**Comment by probonopd** [comment]
Thank you very much for having enabled GitHub Discussions @Nikratio.

I have opened a discussion regarding this topic:

* https://github.com/libfuse/libfuse/discussions/1007
