### ISSUE TITLE
examples/passthrough hangs with max_idle_threads=0 (and maybe other filesystems too)

### ISSUE THREAD

**Issue by lan1120** [libfuse/libfuse#680]
When max_idle_threads is set to 0，and perform the deletion operation on the mount point，the only worker thread exits. Only the main thread is left, libfuse can not receive and process file op request.

In fuse_do_work function, when numavail equals 0, should call fuse_loop_start_thread.

**Comment by aakefbs** [comment]
max_idle_threads is not a good idea in general, see here:
https://github.com/libfuse/libfuse/pull/652

**Comment by Nikratio** [comment]
Not sure I follow. What do you mean with `delete operation on the mount point`? Do you mean `unlink` or `destroy`? And why does this result in the worker thread exiting?

**Comment by lan1120** [comment]
yes，I mean remove a file and I found it from a test.

**Comment by lan1120** [comment]
> Not sure I follow. What do you mean with `delete operation on the mount point`? Do you mean `unlink` or `destroy`? And why does this result in the worker thread exiting?

yes，I mean remove a file and I found it from a test.

**Comment by Nikratio** [comment]
Could you provide more detailed instructions for reproducing this? Why does the `unlink` operation result in worker threads exiting (and not being restarted)?

**Comment by lan1120** [comment]
![image](https://user-images.githubusercontent.com/24563500/177155133-2feaea23-dce8-4a69-85da-09b73917606f.png)

you can use passthrough for test as shown in the screenshot，The last operation hangs.

**Comment by lan1120** [comment]
> Could you provide more detailed instructions for reproducing this? Why does the `unlink` operation result in worker threads exiting (and not being restarted)?

you can use passthrough for test as shown in the screenshot，the last operation hangs.
![image](https://user-images.githubusercontent.com/24563500/177155818-7579f883-81e0-4711-a4df-3d2257fdac11.png)

**Comment by Nikratio** [comment]
I think this problem should be resolved with PR #652 - can you confirm?

**Comment by lan1120** [comment]
Yes， There must be at least one worker thread
