### ISSUE TITLE
free dangling pointer of module

### ISSUE THREAD

**Issue by nm004** [libfuse/libfuse#683]
`fuse_destroy()` calls `fuse_put_module(fuse_modules)` and then calls `fuse_session_destroy(f->se)`. `fuse_session_destroy()` calls `fuse_fs_destroy()` and it leads to freeing dangling pointer because `f->fs->m` still has non-null pointer.

I checked this by the following command (`hello` is a example code in this repo.).

```
./hello -f -o modules=iconv dir
```

I fount it seems that `fs->m` is no longer used, so we can remove it. Modules are now managed by var `fuse_modules`.

https://github.com/libfuse/libfuse/blob/2b7a6f065b6e30723d6cc8668cff198dbb62b914/lib/fuse.c#L5104-L5110

https://github.com/libfuse/libfuse/blob/2b7a6f065b6e30723d6cc8668cff198dbb62b914/lib/fuse.c#L2666-L2674

**Comment by Nikratio** [comment]
I believe this has been fixed with the above commit.

**Comment by nm004** [comment]
Thank you for merging PR.
