### ISSUE TITLE
Filesystems can't report on `devpts` filesystems

### ISSUE THREAD

**Issue by DUOLabs333** [libfuse/libfuse#688]
I've only checked this on Linux, so this might not be a problem on other platforms.

I've checked this with `bindfs`, but this also happens with every other "passthrough" fs that I've used.

`sudo bindfs -odev /dev test`, then `cat test/ptmx` fails with `No such file or directory`, even though `ls test` shows it. `sudo cat test/ptmx` gives me `cat: test/ptmx: No such device`. `cat test/pts/0` gives me `cat: test/pts/0: Input/output error` (`sudo` gives me the same thing). `/dev/pts` is on `devpts`.

**Comment by DUOLabs333** [comment]
Further discussion here: https://github.com/mpartel/bindfs/issues/111

**Comment by Nikratio** [comment]
Could you clarify what exactly you think the issue with libfuse is here? You are giving some examples from a filesystem that presumably uses libfuse internally, but I can't tell what you are doing with libfuse, what happens in practice, and what you were expecting to happen...

**Comment by Nikratio** [comment]
(will close this issue for now since it's almost certainly an issue with bindfs. /dev/pts contains character devices, and libfuse is not involved in accessing them)
