### ISSUE TITLE
Clarification for issue `nofail` not working in Debian Bullseye

### ISSUE THREAD

**Issue by viertelb** [libfuse/libfuse#691]
When I use `nofail` in `fstab` with `mp3fs` (which is a filesystem that mounts flac and others as mp3 on-the-fly), I get the error 

`fuse: unknown option 'nofail'`

My `fstab`:

`mp3fs#/mnt/mybook  /mnt/mp3fs    fuse nofail,noauto,allow_other,ro,bitrate=192,x-systemd.requires-mounts-for=/mnt/mybook 0 0`

**I was under the (false) impression that this already worked in Buster.** Am I mistaken or did I lose the ability to use  `nofail` by upgrading from 32bit Debian Buster to 64bit Bullseye (on a Raspberry Pi)?

---

I already read about this issue here: https://github.com/libfuse/libfuse/issues/211

So there seems to be libfuse 2.9.9 in Debian Bullseye: https://packages.debian.org/bullseye/fuse

The entry for Buster looks similar, except there is an extra mentioning of `fuse3`: https://packages.debian.org/buster/fuse

---

**So I installed** `apt install fuse3` and the options `nofail` is recognised properly. No boot hang when the mount does not work! 

Awesome!

However I got the message

```
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.
 exfat-fuse depends on fuse.
```

Is this maybe a problem or will work `fuse3` with them like `fuse`?

**Comment by Nikratio** [comment]
Thanks for reporting this issue. This does not look like a bug in libfuse, I would suggest reaching out to your distributions user forums / lists for advice.
