### ISSUE TITLE
[3.12.0][Ubuntu 20.04] Missing `fuse_parse_cmdline@FUSE_3.0` Symbol

### ISSUE THREAD

**Issue by hswong3i** [libfuse/libfuse#696]
I am packaging libfuse 3.12.0 in deb/rpm for multiple OS with OBS, used together with fuse-overlayfs + Kubernetes deployment:
* https://github.com/alvistack/libfuse-libfuse/commit/b74e2f8bda9cacf4ecc467a5b8191af18e59ea18
* https://build.opensuse.org/package/show/home:alvistack/libfuse-libfuse-3.12.0

When packaging libfuse 3.12.0 with Ubuntu 18.04 / Ubuntu 20.04 / Debian 10, I get the following error message:
```
[  135s] dpkg-gensymbols: error: some symbols or patterns disappeared in the symbols file: see diff output below
[  135s] dpkg-gensymbols: warning: debian/libfuse3-3/DEBIAN/symbols doesn't match completely debian/libfuse3-3.symbols
[  135s] --- debian/libfuse3-3.symbols (libfuse3-3_100:3.12.0-1_amd64)
[  135s] +++ dpkg-gensymbolsGUlak9	2022-09-11 00:55:38.548557941 +0000
[  135s] @@ -105,7 +105,7 @@
[  135s]   fuse_opt_insert_arg@FUSE_3.0 3.11.0
[  135s]   fuse_opt_match@FUSE_3.0 3.11.0
[  135s]   fuse_opt_parse@FUSE_3.0 3.11.0
[  135s] - fuse_parse_cmdline@FUSE_3.0 3.11.0
[  135s] +#MISSING: 100:3.12.0-1# fuse_parse_cmdline@FUSE_3.0 3.11.0
[  135s]   fuse_parse_cmdline@FUSE_3.12 3.12.0
[  135s]   fuse_parse_cmdline_30@FUSE_3.12 3.12.0
[  135s]   fuse_parse_cmdline_312@FUSE_3.12 3.12.0
[  135s] dh_makeshlibs: error: failing due to earlier errors
[  135s] make: *** [debian/rules:54: binary] Error 25
[  135s] dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

Only Ubuntu 22.10 and Debian 11 could provide both symbol as below:
```
fuse_parse_cmdline@FUSE_3.0 3.11.0
fuse_parse_cmdline@FUSE_3.12 3.12.0
```

Above missing `fuse_parse_cmdline@FUSE_3.0` symbol making my fuse-overlayfs used for Kubernetes failed with above OS, e.g.
* https://gitlab.com/alvistack/ansible-collection-kubernetes/-/jobs/3009891732
* https://gitlab.com/alvistack/ansible-collection-kubernetes/-/jobs/3009866358

**Comment by hswong3i** [comment]
For testing with podman + Ubuntu 20.04:
```
$ sudo podman run -ti --rm ubuntu:20.04 /bin/bash

apt update && apt -y full-upgrade
apt -y install git gettext libselinux-dev meson ninja-build pkg-config udev build-essential
git clone https://github.com/libfuse/libfuse.git && cd libfuse
git checkout fuse-3.12.0
mkdir build && cd build && meson ../ .
ninja
readelf -Ws ./lib/libfuse3.so.3.12.0 | grep fuse_parse_cmdline

   241: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
   256: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30@@FUSE_3.12
   266: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312@@FUSE_3.12
   540: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312
   562: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30
   653: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
```

For testing with podman + Ubuntu 22.04:
```
$ sudo podman run -ti --rm ubuntu:22.04 /bin/bash

apt update && apt -y full-upgrade
apt -y install git gettext libselinux-dev meson ninja-build pkg-config udev build-essential
git clone https://github.com/libfuse/libfuse.git && cd libfuse
git checkout fuse-3.12.0
mkdir build && cd build && meson ../ .
ninja
readelf -Ws ./lib/libfuse3.so.3.12.0 | grep fuse_parse_cmdline

   241: 000000000001e8d0   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
   243: 000000000001e9d0    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@FUSE_3.0
   257: 000000000001e9d0    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30@@FUSE_3.12
   267: 000000000001e8d0   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312@@FUSE_3.12
   488: 000000000001e8d0   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312
   510: 000000000001e9d0    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30
   597: 000000000001e8d0   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
   645: 000000000001e9d0    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@FUSE_3.0
```

**Comment by hswong3i** [comment]
After adding additional test, e.g. `readelf -Ws %{_vpath_builddir}/lib/*.so | grep "fuse_parse_cmdline@*FUSE_3.0"` to my build script (see https://github.com/alvistack/libfuse-libfuse/commit/47b98e9fbdbebba177959b2c09765109ed1436ca):
* https://github.com/alvistack/libfuse-libfuse/commit/47b98e9fbdbebba177959b2c09765109ed1436ca#diff-55361aa658ca6446639fae7e100bc784e492b1ac0fbfffb0273b9a7dc7157a3aR52
* https://github.com/alvistack/libfuse-libfuse/commit/47b98e9fbdbebba177959b2c09765109ed1436ca#diff-889c5495b68d2a0c0d1f238818716a71939918499efbc0fc6d2994319624fc67R50

I could figure out following OS are FAILED with this missing `fuse_parse_cmdline@FUSE_3.0` symbol (most likely, OS with basic libraries older or equal than Ubuntu 20.04 could fail):
* Ubuntu 20.04
* Ubuntu 18.04
* Debian 10
* CentOS 8 Stream
* CentOS 7
* openSUSE Leap 15.4
* openSUSE Leap 15.3

So I am now temporarily disable the build of 3.12.0 for these broken OS, and just cap their maximum supported version to 3.11.0:
![image](https://user-images.githubusercontent.com/780562/189514339-ab2bb062-6462-4c18-af7d-14b276b0cbf3.png)

**Comment by aakefbs** [comment]
@hswong3i see pull #697 . I had manually tested ABI compatibility under ubuntu 22.04, but older gcc version use a different way of version symboling

#ifndef __APPLE__
# if HAVE_SYMVER_ATTRIBUTE
#  define FUSE_SYMVER(sym1, sym2) __attribute__ ((symver (sym2)))
# else
#  define FUSE_SYMVER(sym1, sym2) __asm__("\t.symver " sym1 "," sym2);
# endif
#else
#define FUSE_SYMVER(sym1, sym2)
#endif


older gcc: define FUSE_SYMVER(sym1, sym2) __asm__("\t.symver " sym1 "," sym2)
newer gcc: FUSE_SYMVER(sym1, sym2) __attribute__ ((symver (sym2)))

With the newer way "sym1" is not used at all, with the older version "sym1" needs to match the function name, but I had typo there - mismatch and it then silently skipped the versioned symbol.

I guess we should add a test to check all the symbols in the version script.

**Comment by hswong3i** [comment]
For testing https://github.com/libfuse/libfuse/commit/b1290d4c091a5c590e61a6195e625eab33300673 with podman + Ubuntu 20.04, now looks good:
```
$ sudo podman run -ti --rm ubuntu:20.04 /bin/bash

apt update && apt -y full-upgrade
apt -y install git gettext libselinux-dev meson ninja-build pkg-config udev build-essential
git clone https://github.com/libfuse/libfuse.git && cd libfuse
git checkout b1290d4c091a5c590e61a6195e625eab33300673
mkdir build && cd build && meson ../ .
ninja
readelf -Ws ./lib/libfuse3.so.3.12.0 | grep fuse_parse_cmdline

   241: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
   243: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@FUSE_3.0
   257: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30@@FUSE_3.12
   267: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312@@FUSE_3.12
   540: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_312
   562: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline_30
   653: 000000000001d240   256 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@@FUSE_3.12
   700: 000000000001d340    98 FUNC    GLOBAL DEFAULT   15 fuse_parse_cmdline@FUSE_3.0
```

I am now packaging it as a 3.12.0 + patched version with OBS, and it also looks good and passing my newly added test for checking symbol:
* https://build.opensuse.org/package/show/home:alvistack/libfuse-libfuse-3.12.0+20220912b1290d4c
* https://github.com/alvistack/libfuse-libfuse/commit/7ccde62911f905de26e7593cc3dae86105d07033

@aakefbs and @Nikratio thank you very much ;-)
