### ISSUE TITLE
fusermount3 call umount2 failed，errno is 5

### ISSUE THREAD

**Issue by lan1120** [libfuse/libfuse#704]
Common User Operations：
（1）Running 512 passthrough_hp instances，That is, 512 directories are mounted.
（2）Stop all instances，for example：ps -ef | grep passthrough_hp | grep -v grep | awk '{print $2}' | xargs kill -15
（3）All passthrough_hp processes have exited.
（4）Execute mounts，some directories failed to be umounted.
![image](https://user-images.githubusercontent.com/24563500/196669324-746a1048-7671-4a14-99e7-f96b2fabfa4b.png)
![image](https://user-images.githubusercontent.com/24563500/196670150-965554f4-3859-4d97-9e22-ffa13a73a706.png)
（5）fusermount3 call umount2 failed， errno is 5

I think fusermount3 should has retry mechanism when call umount2！

**Comment by Nikratio** [comment]
Sorry, I do not understand this report. The error means that the fuse daemon has crashed (which isn't surprising since you killed the process). I do not see you running `fusermount3` anywhere, so how is this related to fusermount3?
