### ISSUE TITLE
sudo -u allows access to FUSE mounts without allow_root/allow_others

### ISSUE THREAD

**Issue by chrstphrchvz** [libfuse/libfuse#71]
The man page and READMEs claim that FUSE mounts cannot be accessed by other users including root unless the `allow_root` or `allow_others` options are specified when mounting.

But if a user can `sudo -u` to log in as another user, they are able to access the other user's FUSE mounts using filesystem operations, regardless of mount options. So my understanding of the mount options is that they only prevent casual access via filesystem operations.

Is this method considered known or intended behavior of FUSE and sudo, and/or is it something the FUSE documentation should take into consideration? Could system configuration affect whether this method applies?

Further, `sudo -u` is just a convenient method. There might be other methods that bypass FUSE mount options, such as access to a FUSE mount's underlying device file or user's process memory.

**Comment by Nikratio** [comment]
sudo turns you into another user. So yes, this behavior is expected.
