### ISSUE TITLE
fuse FIEMAP support

### ISSUE THREAD

**Issue by vitalif** [libfuse/libfuse#72]
Hi!
~2 years ago I've written simples patch for fuse kernel module, libfuse and ntfs-3g to support FIEMAP via a separate FUSE opcode.
https://sourceforge.net/p/fuse/mailman/message/32015139/
Is it possible to merge these patches at last?
What should I do to get them merged in kernel fuse, libfuse, and ntfs-3g?

**Comment by vitalif** [comment]
The feature itself is very useful for playing file file fragmentation utils etc.

**Comment by Nikratio** [comment]
Thanks for the report!

As far as I can tell, this is a patch for *FUSE*, the Linux kernel module. This GitHub project is primarily for *libfuse*, the userspace library. I'm happy to keep track of kernel issues in this  issue tracker as well, but please note that it's quite unlikely that reporting kernel issues here will be sufficient to get them fixed. 

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, e.g. [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) or [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel).

**Comment by vitalif** [comment]
In fact it consists of 3 patches - fuse kernel, libfuse and ntfs-3g. I was interested if there is a fuse/libfuse specific dev process. So you say I should just send the kernel patch to lkml and come back here when it's merged?

**Comment by Nikratio** [comment]
Exactly :-).

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please just submit a pull request when the kernel patches have been merged. Thanks!

**Comment by trapexit** [comment]
Off topic: Why do you close these kinds of tickets? The point of tickets is to be reminders and provide a point for workflow around a feature. Unless you have no intent of accepting these feature requests I'm not sure why you'd close them. Leaving them open makes it easier for people to know work is in flight or needs to be done.

**Comment by Nikratio** [comment]
I prefer to use the bugtracker to manage issues where there's actual activity - or at least the intention of activity from someone. Having a long list of open issues that no one is working on (and probably never will) gets in the way of that. 

I still have to encounter the situation where someone looks at the issue tracker to find something to work on rather than for report ing something that they think should be done. But even if that happens, there are already plenty of open tickets.
