### ISSUE TITLE
HAVE_LIBC_VERSIONED_SYMBOLS not set in installed headers

### ISSUE THREAD

**Issue by amesser** [libfuse/libfuse#724]
When libfuse detects symver support during build, it sets define HAVE_LIBC_VERSIONED_SYMBOLS for the build. However, when installing headers in the system, these headers do not know about that. Thus applications build against libfuse later, will not have this define set and may show unexpected behavior.

It would be better to use more project specific define name which is also placed in some "config.h" header file to be incoporated in development headers.

**Comment by bsbernd** [comment]
Hmm right, I didn't notice that config.h didn't get included into header files (and is also not distributed).

**Comment by Nikratio** [comment]
@bsbernd Would you have time to come up with a fix for that in the next 2 weeks? If not, then I'll make an intermediate release where HAVE_LIBC_VERSIONED_SYMBOLS is always set. That way, at least the more common case works reliably.

**Comment by bsbernd** [comment]
I will try today, latest over the weekend. Right now working on fuse anyway (you will see soon) - next week I will probably need to shift most time to another project.

**Comment by Nikratio** [comment]
Thanks a lot!

**Comment by bsbernd** [comment]
@amesser if you should have chance, could you please test this patch? https://github.com/libfuse/libfuse/pull/726

**Comment by amesser** [comment]
I'm sorry but i have not really something to test this with. I found the issue during code review while I was digging into a Devuan package bug. We observed a symbol issue with libvirts lxc module. It turned out, that libvirt built with libfuse 3.13 would show the issue when used with binary build of libfuse 3.12.

https://bugs.devuan.org/cgi/bugreport.cgi?bug=738
