### ISSUE TITLE
setxattr is broken

### ISSUE THREAD

**Issue by limetech** [libfuse/libfuse#730]
Likely this commit:
https://github.com/libfuse/libfuse/commit/7f430a39db5a30979d75a906af891a38ebce1a3c

The 'name' string passed to fs->op.setxattr has the first 8 characters missing.  Using the 'passthrough' example, start it up and try:

 setfattr -n user.myxattr -v myvalue /xmp/somefile
setfattr: /xmp/somefile: Operation not supported

This is because the string seen by xmp_setxattr() is "attr" instead of "user.myxattr".

To prove the name pointer is off by 8 bytes, inside xmp_setxattr() this works to change:
        int res = lsetxattr(path, name, value, size, flags);
to
        int res = lsetxattr(path, (char *)(name-8), value, size, flags);

**Comment by Nikratio** [comment]
I can confirm the problem. It seems to affect only setxattr, not getxattr:

```
# example/passthrough_ll -o debug,source=/tmp,xattr ~/tmp/mnt &
[....]
# setfattr -n user.foobar -v terminate ~/tmp/mnt/tmpy12rqp1r
unique: 534, opcode: SETXATTR (21), nodeid: 140044455121248, insize: 69, pid: 2080913
lo_setxattr(ino=140044455121248, name=bar value=terminate size=9)
   unique: 534, error: -95 (Operation not supported), outsize: 16

# getfattr -n user.foobar  ~/tmp/mnt/tmpy12rqp1r
unique: 548, opcode: GETXATTR (22), nodeid: 140044455121248, insize: 60, pid: 2081099
lo_getxattr(ino=140044455121248, name=user.foobar size=0)
   unique: 548, error: -95 (Operation not supported), outsize: 16
```

**Comment by Nikratio** [comment]
Reverting commit 7f430a3 fixes the problem (though it's not immediately obvious to me why).
