### ISSUE TITLE
Max size of read and write requests issued by kernel

### ISSUE THREAD

**Issue by vadlakondaswetha** [libfuse/libfuse#751]
Hi,

We have a fuse based filesystem for interacting with Google cloud storage  (https://github.com/GoogleCloudPlatform/gcsfuse/blob/6eb81bba0dc6011bd01d76c88bf1755f2208b296/vendor/github.com/jacobsa/fuse/connection.go#L117) and i have following questions wrt to read/write requests issued by kernel.

1. What is the max size of the write request issued by kernel. Right now, we are getting 1MB sized requests but want to check if it is 1MB or can we increase this limit?

2. Same for read requests. What is the max amount of data kernel can request in case of file reads. Irrespective of the IO size issued, we are getting requests to fetch 1MB of data from kernel.

**Comment by bsbernd** [comment]
You should really ask things like this on a mailing list - fsdevel or fuse-devel as your question unrelated to **lib**fuse. Max IO size is a kernel limitation 

<linux>/fs/fuse_i.h

```
/** Maximum of max_pages received in init_out */
#define FUSE_MAX_MAX_PAGES 256
```

Most systems have 4K pages, so 1MB IO sizes max.

**Comment by trapexit** [comment]
The only way to change the value above max 256 pages is to recompile the FUSE driver with a patched value. Same as with readdir message size currently.

**Comment by vadlakondaswetha** [comment]
Thanks for the clarification.
