### ISSUE TITLE
How to create more than one device file at once?

### ISSUE THREAD

**Issue by jiehou** [libfuse/libfuse#758]
Hi all,

Currently, I am using the library (libfuse) in my project. I tried to create more than one device file at once. Two different approaches are verified. They cannot work well.  Do you have some suggestions about how to make more than one device file at once?

I am looking forward to hearing from you.
Thank you very much in advance.

1) Approach 1
void init() {
  const char *devarg[3];
  devarg[0] = "DEVNAME=ttySPI0";
  devarg[1] = "DEVNAME=ttySPI1";
  devarg[2] = "DEVNAME=ttySPI2";
  const char *cusearg[] = { "example1" , "-f" };
  struct cuse_info ci;

  ci.dev_info_argc = 3;
  ci.dev_info_argv = devarg;

  struct cuse_lowlevel_ops ops = {};
  ops.read = cusexmp_read;
  ops.write = cusexmp_write;

  cuse_lowlevel_main(2, (char**)&cusearg, &ci, &ops, NULL);    
} 

2) Approach 2
void init(int id) {
  const char *devarg[1];
  string devFile = "DEVNAME=ttySPI" + to_string(id);
  cout << devFile << endl;
  devarg[0] = devFile.c_str();  
  const char *cusearg[] = {"example1", "-f"};
  struct cuse_info ci;

  ci.dev_info_argc = 1;
  ci.dev_info_argv = devarg;

  struct cuse_lowlevel_ops ops = {};
  ops.read = cusexmp_read;
  ops.write = cusexmp_write;

  cuse_lowlevel_main(2, (char**)&cusearg, &ci, &ops, NULL);    
}

int main() {
  cout << "<> init(0): ttySPI0\n"; //dev
  init(0); // device file: ttySPI0
 
  cout << "<> init(1): ttySPI1\n";
  init(1); // device file: ttySPI1
  return 0;
}

**Comment by Nikratio** [comment]
Thanks for your interest in libfuse! As far as I can tell, this is a question about how to use fuse rather than a bug report. Could you please send your question to the FUSE mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
