### ISSUE TITLE
Errors in Make

### ISSUE THREAD

**Issue by Aeirex** [libfuse/libfuse#76]
Won't make install or make -j8. I am using 10.12 macOS Sierra.

```
../include/fuse_compat.h:69:10: fatal error: 'sys/statfs.h' file not found
#include <sys/statfs.h>
         ^
error: use of 1 error generated.
undeclared identifier 'MS_RDONLY'
        if (!(flags & MS_RDONLY) && fuse_opt_add_opt(mnt_optsp, "rw") == -1)
                      ^
1 error generated.
mount.c:585:13: error: use of undeclared identifier 'MS_NOSUID'
        mo.flags = MS_NOSUID | MS_NODEV;
                   ^
mount.c:585:25: error: use of undeclared identifier 'MS_NODEV'
        mo.flags = MS_NOSUID | MS_NODEV;
```

**Comment by Nikratio** [comment]
I think you are looking for https://github.com/osxfuse/.

**Comment by Aeirex** [comment]
@Nikratio I get a compile error, which mentions I am missing LibFuse. Is LibFuse provided in OSXFuse? I can't compile something without LibFuse.

**Comment by Aeirex** [comment]
It was actually fuse-2.9.7.

**Comment by Nikratio** [comment]
osxfuse is for MacOS what libfuse is for linux. Whatever problems you have, you won't find the solutions here unless you're using Linux.

**Comment by Aeirex** [comment]
I see, thanks.
