### ISSUE TITLE
`example/notify_inval_entry --only-expire` fails on modern kernels

### ISSUE THREAD

**Issue by matthiasgoergens** [libfuse/libfuse#769]
On Linux 5.15.49 `example/notify_inval_entry --only-expire` works just fine, but on 6.2.9 it fails as follows:

```
~/p/f/l/build (master-ful)$ ./example/notify_inval_entry --only-expire -s -d -f example/mountpoint
[snip]
notify_inval_entry: ../example/notify_inval_entry.c:261: update_fs_loop: Assertion `fuse_lowlevel_notify_expire_entry (se, FUSE_ROOT_ID, old_name, strlen(old_name), FUSE_LL_EXPIRE_ONLY) == 0' failed.
Aborted (core dumped)
```

I strongly suspect https://github.com/torvalds/linux/commit/4f8d37020e1fd0bf6ee9381ba918135ef3712efd is the responsible kernel commit.

(The two kernel versions in question are what I'm getting from running Docker on a MacOSX laptop for the old kernel, and my Archlinux desktop for the new kernel.)

I noticed the problem, because `test/test_examples.py::test_notify_inval_entry[True-expire_entries] ` fails on the newer kernel.

I'm working on understanding what's happening and writing a fix.

**Comment by matthiasgoergens** [comment]
`test_notify1` in `test_ctests.py` might also be affected, but I'm not so sure.

**Comment by Nikratio** [comment]
I believe this has since been fixed in the above commits.
