### ISSUE TITLE
Run automated tests on modern kernels

### ISSUE THREAD

**Issue by matthiasgoergens** [libfuse/libfuse#778]
At the moment, we are testing only on the github provided runner, which has a slightly older kernel.  See eg https://github.com/libfuse/libfuse/issues/769

I have a Linode server that I'm using only lightly.  I'm running Archlinux on it, and keep it up-to-date.  If there's interest, I can set up a 'self-hosted' github runner there for libfuse.

For the beginning, I'd suggest we make it just advisory, and not mandatory for PRs to pass this check.  That's mostly because I don't want to make any guarantees on availability, and also so that I'm not holding anything up.

What do you think?

I'm running Archlinux on the server, but we can run everything via Docker.  So the only kernel version would be the only thing that comes from the underlying server.

**Comment by Nikratio** [comment]
If you're willing to do that, that would be great! Thank you.

**Comment by matthiasgoergens** [comment]
So the implicit question is: do you know what I need to do?

If not, I guess I'll just set it up for my fork to figure everything out, and then we transfer the setup here.

**Comment by Nikratio** [comment]
Yep, I have no idea what needs doing :-).

**Comment by matthiasgoergens** [comment]
I poked a bit at how to set this up, and it wasn't immediately obvious.

However, I found something that probably better!  Have a look at [what the fine folks of Rust-for-Linux are doing](https://github.com/Rust-for-Linux/linux/blob/rust/.github/workflows/ci.yaml): they are using qemu to test with different kernels despite only having the same free GitHub-hosted runners available.

We should be able to copy their homework.

**Comment by matthiasgoergens** [comment]
I've asked for suggestions on https://github.com/actions/runner-images/discussions/7439

**Comment by matthiasgoergens** [comment]
I'm currently trying to make user-mode-linux work.

**Comment by matthiasgoergens** [comment]
OK, user-mode Linux seems a bit too hard and annoying.  But https://github.com/archlinuxhardened/selinux/blob/master/.github/workflows/main.yml seems really useful.

**Comment by Nikratio** [comment]
@matthiasgoergens Is work on this still ongoing, or can we close this issue?

**Comment by matthiasgoergens** [comment]
You can close the issue, I haven't had time to look into this.
