### ISSUE TITLE
How to tailor FUSE to support big file read/write?

### ISSUE THREAD

**Issue by MRYingLEE** [libfuse/libfuse#78]
There is a related option, as the following:
"    -o big_writes          enable larger than 4kB writes\n"

I am developing a fuse application. In my situation, the files are always big and clients prefer performance. So I am thinking to use 1M as a size unit to read/write. 

I am working out the way to tailor libfuse options, even source code, to my situation.

But I couldn't find other related options, and I checked the source code, but I had no idea where to change.

Can you show me a direction?

Thank you in advance,
Ying

**Comment by Nikratio** [comment]
Thanks for your interest in FUSE! Could you please send your question to FUSE mailing list
(https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion/support.
