### ISSUE TITLE
Kernel deadlock when unlinking

### ISSUE THREAD

**Issue by xandrus** [libfuse/libfuse#8]
Hi,

We have problem with one software running on sshfs.
Each time when we starting sshfs-folder/SPAdes-3.6.2-Linux/bin/spades.py --test it's hang after few seconds.
We notice that this problem apperas only on linux kernel 3.16.0 and newer and probably any FUSE fs (we tested SSHFS and MooseFS).
When we are running this software on standard hard disk it's working correctly on any kernel.

To repeat error please download:
- http://spades.bioinf.spbau.ru/release3.6.2/SPAdes-3.6.2-Linux.tar.gz
- extract tar file inside mouted SSHFS folder
- run this command: sshfs-mouted-folder/SPAdes-3.6.2-Linux/bin/spades.py --test
- after 2-3 seconds program will freeze. 

Our configration:
- Ubuntu 14.04.1 x86_64
- kernel 3.19.0-43-generic
- libfuse 2.9.4

Kernel log:
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116703] INFO: task python:6559 blocked for more than 120 seconds.
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116848]       Not tainted 3.19.0-43-generic #49~14.04.1-Ubuntu
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116897] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116958] python          D ffff8801754bbd88     0  6559   3837 0x00000000
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116963]  ffff8801754bbd88 ffff88007fab0000 0000000000013e80 ffff8801754bbfd8
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116965]  0000000000013e80 ffff880172b24e80 ffff88007fab0000 0000000000000000
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116967]  ffff8800b0dd29a8 ffff8800b0dd29ac ffff88007fab0000 00000000ffffffff
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116969] Call Trace:
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116978]  [<ffffffff817b3879>] schedule_preempt_disabled+0x29/0x70
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116981]  [<ffffffff817b5565>] __mutex_lock_slowpath+0x95/0x100
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116983]  [<ffffffff817b55f3>] mutex_lock+0x23/0x37
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116987]  [<ffffffff811fa4ad>] vfs_unlink+0x4d/0x170
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116990]  [<ffffffff811fcd9b>] do_unlinkat+0x2bb/0x300
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116995]  [<ffffffff81015cd3>] ? do_device_not_available+0x33/0x70
Jan 12 11:38:47 blueocean252 kernel: [ 5885.116998]  [<ffffffff811fde46>] SyS_unlink+0x16/0x20
Jan 12 11:38:47 blueocean252 kernel: [ 5885.117000]  [<ffffffff817b770d>] system_call_fastpath+0x16/0x1b

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue! Unfortunately there is very little chance for someone to address this here. You have found an issue in the FUSE kernel module, while this is the GitHub project for the FUSE userspace library. I recommend that you report this problem to the linux kernel mailing list instead.

**Comment by xandrus** [comment]
Thank you for this information.
We have sent this issue directly to Miklos Szeredi.
Right now we are waiting for answer.
If we do not receive any information from Miklos we will report this to LKML.
