### ISSUE TITLE
Musl patch causes build regression with 3.15.0 in cross compiling

### ISSUE THREAD

**Issue by heitbaum** [libfuse/libfuse#803]
../meson.build:180:12: ERROR: Can not run test applications in this cross environment.

- simple fix is to revert #761

**Comment by Nikratio** [comment]
Thanks for the report. I guess feature tests are fundamentally incompatible with cross compiling. In this case I am not sure which one is more important though. Perhaps there are more people compiling with an old musl bug than people attempting to cross-compile?

**Comment by heitbaum** [comment]
> Thanks for the report. I guess feature tests are fundamentally incompatible with cross compiling. In this case I am not sure which one is more important though. Perhaps there are more people compiling with an old musl bug than people attempting to cross-compile?

I would think that much of ARM and RISCV targets are cross compiled.

You could potentially wrapper the following with `if not meson.is_cross_build()` https://mesonbuild.com/Cross-compilation.html#introspection-and-system-checks

https://github.com/libfuse/libfuse/blob/6d08472ea47db895748d5ca7d3daf032c3fefcf8/meson.build#L180-L184

e.g.

```
diff --git a/meson.build b/meson.build
index 7aa4e0d..9707ea3 100644
--- a/meson.build
+++ b/meson.build
@@ -177,10 +177,12 @@ int main()
 }
 '''
 
-result = cc.run(detect_getmntent_needs_unescape)
-if result.compiled() and result.returncode() == 0 and result.stdout().strip() == 'needs escaping'
-  message('getmntent does not unescape')
-  add_project_arguments('-DGETMNTENT_NEEDS_UNESCAPING', language: 'c')
+if not meson.is_cross_build()
+  result = cc.run(detect_getmntent_needs_unescape)
+  if result.compiled() and result.returncode() == 0 and result.stdout().strip() == 'needs escaping'
+    message('getmntent does not unescape')
+    add_project_arguments('-DGETMNTENT_NEEDS_UNESCAPING', language: 'c')
+  endif
 endif
 
 # Write private test results into fuse_config.h (stored in build directory)
```

**Comment by heitbaum** [comment]
> Yeah, that sounds like a good idea. Would you mind sending a pull request?

Updated the PR
