### ISSUE TITLE
Was `fuse-3.15.1.tar.gz` re-uploaded?

### ISSUE THREAD

**Issue by ZhongRuoyu** [libfuse/libfuse#816]
Hi! [Homebrew](https://github.com/Homebrew/brew) maintainer here. As reported to us in https://github.com/Homebrew/homebrew-core/issues/136487, the [`fuse-3.15.1.tar.gz`](https://github.com/libfuse/libfuse/releases/download/fuse-3.15.1/fuse-3.15.1.tar.gz) tarball from the [3.15.1 release page](https://github.com/libfuse/libfuse/releases/tag/fuse-3.15.1) now has a different checksum than what was downloaded from the same URL on 2023-07-05 at 15:02 UTC (see https://github.com/Homebrew/homebrew-core/pull/135851). I noticed that the tarball currently listed on the release page was uploaded on 2023-07-05 at 17:55 UTC (i.e., ~3 hours after we built and shipped the 3.15.1 release). So, I would like to check if the tarball was modified and re-uploaded somehow. Thanks!

**Comment by Nikratio** [comment]
Yes, the first tarball for some reason did not pass GPG verification, so both signature and tarball was re-uploaded. I am surprised you caught the checksum change, but not the fact that the original tarball couldn't be verified.

**Comment by ZhongRuoyu** [comment]
Thanks for the confirmation, @Nikratio!

> I am surprised you caught the checksum change, but not the fact that the original tarball couldn't be verified.

We verify tarballs' SHA256, not their signatures.

**Comment by Nikratio** [comment]
Yeah, but how do you know what the checksum should be?

**Comment by ZhongRuoyu** [comment]
It's usually calculated from a downloaded copy, rather than provided upstream (which not every package maintainer do). To bump a formula (package) to a new version, one updates the tarball URL and its SHA, and then submit a PR like Homebrew/homebrew-core#135851. CI verifies the checksum, builds the software from source, and performs a bunch of other checks.

For this reason, we need to communicate with upstream maintainers when we see checksum changes to understand why. More often (not in this case, but in cases where there are no release assets so a git archive is used), they are caused by re-tagging.
