### ISSUE TITLE
Official release not updated on linux package managers

### ISSUE THREAD

**Issue by vibhansa-msft** [libfuse/libfuse#828]
I see libfuse latest release has reached 3.15+ but on Ubuntu or few other linux distro if I do "sudo apt install fuse3" it still installs 3.9 version only.
I do not want to update the version manually. Any reason why the package managers are not reflecting back on the latest versions.

**Comment by trapexit** [comment]
Because that's how non-rolling release distros work.

**Comment by Nikratio** [comment]
In any case, this is not something that libfuse maintainers can help with. You'll need to get in touch with the folks who are packaging libfuse for the distributions you are interested in.
