### ISSUE TITLE
Release 3.16.1 re-updated

### ISSUE THREAD

**Issue by giuliobenetti** [libfuse/libfuse#829]
Just to point out that Release 3.16.1 tarball .tar.gz has been re-uploaded where doc/html/ folder has been dropped while .github/ folder has been added for CI/CD as well as some other .gitignore files.
So tarball Sha256 changed.

This is only to let people know about it.

Best regards

**Comment by Nikratio** [comment]
I believe you are mistaken. https://github.com/libfuse/libfuse/releases/download/fuse-3.16.1/fuse-3.16.1.tar.gz has only been uploaded once and still contains eg. `doc/html`.

Perhaps you accidentally downloaded a snapshot of the Git repo instead?

**Comment by giuliobenetti** [comment]
> I believe you are mistaken. https://github.com/libfuse/libfuse/releases/download/fuse-3.16.1/fuse-3.16.1.tar.gz has only been uploaded once and still contains eg. `doc/html`.
> 
> Perhaps you accidentally downloaded a snapshot of the Git repo instead?

@Nikratio you're right, I don't know how it happened but I've downloaded source code tarball.
Sorry for the noise!
