### ISSUE TITLE
Check return value of pthread_cond_wait and pthread_mutex_lock

### ISSUE THREAD

**Issue by elfring** [libfuse/libfuse#83]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html) ⇒ [wait_path](https://github.com/libfuse/libfuse/blob/ecc291b7beb8020f0b4b729458144057ca4f9d74/lib/fuse.c#L1178)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) ⇒ [fuse_chan_get](https://github.com/libfuse/libfuse/blob/ecc291b7beb8020f0b4b729458144057ca4f9d74/lib/fuse_loop_mt.c#L68)

**Comment by Nikratio** [comment]
Thanks for spotting this! Pull requests are welcome :-).

**Comment by elfring** [comment]
I imagine that your change of the title for this issue can be inappropriate.

I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by Nikratio** [comment]
On Linux, *pthread_cond_wait(3)* guarantees that it will never return an error code, and *pthread_mutex_lock(3)* can only return `EINVAL` if the mutex hasn't been initialized. I don't think this is worth addressing.
