### ISSUE TITLE
Searching a Single var String

### ISSUE THREAD

**Issue by Snake69** [libfuse/libfuse#835]
fuse doesn't seem to be able to handle searching a single var string (i.e., it needs an array of strings).  Is this correct?  And if so, shouldn't it be able to search a single var string?

**Comment by Nikratio** [comment]
I'm not sure what you mean. Could you elaborate? (ideally with code example or link to relevant documentation)

**Comment by Snake69** [comment]
I am new to JavaScript so perhaps I'm thinking wrong or doing something wrong.
I'm using fuse in node.js.  I'm running Node.js v20.0.0 on Linux.

const Fuse = require('fuse.js');

    const FuseOptions = {
        isCaseSensitive: true,
        includeScore: true,
        findAllMatches: true,
        threshold: 0.6,
    };

    var fuseme = "The quick brown fox jumps over the lazy dog.";
    const fuse = new Fuse(fuseme.split(" "), FuseOptions);

    const searchResult = fuse.search('jump');


The above code works as I expect it to.  But, with a "new Fuse" line of:

const fuse = new Fuse(fuseme, FuseOptions);

I get:

/home/mlake/public_html/node_modules/fuse.js/dist/fuse.common.js:539
        this.docs.forEach(function (doc, docIndex) {
                       ^

TypeError: this.docs.forEach is not a function
    at FuseIndex.create (/home/mlake/public_html/node_modules/fuse.js/dist/fuse.common.js:539:19)
    at createIndex (/home/mlake/public_html/node_modules/fuse.js/dist/fuse.common.js:685:11)
    at Fuse.setCollection (/home/mlake/public_html/node_modules/fuse.js/dist/fuse.common.js:1918:32)
    at new Fuse (/home/mlake/public_html/node_modules/fuse.js/dist/fuse.common.js:1906:10)

**Comment by Nikratio** [comment]
libfuse has no JavaScript components at all. I'm afraid you are looking for a completely unrelated project.
