### ISSUE TITLE
Review `allow_root` check in `fuse_session_process_buf_int()`

### ISSUE THREAD

**Issue by Nikratio** [libfuse/libfuse#86]
What is this code supposed to achieve?

```
    err = EACCES;
    if (se->allow_root && in->uid != se->owner && in->uid != 0 &&
         in->opcode != FUSE_INIT && in->opcode != FUSE_READ &&
         in->opcode != FUSE_WRITE && in->opcode != FUSE_FSYNC &&
         in->opcode != FUSE_RELEASE && in->opcode != FUSE_READDIR &&
         in->opcode != FUSE_FSYNCDIR && in->opcode != FUSE_RELEASEDIR &&
         in->opcode != FUSE_NOTIFY_REPLY &&
         in->opcode != FUSE_READDIRPLUS)
        goto reply_err;
```

**Comment by jpandre** [comment]
IMHO This is intended, when allow_root is enabled, to prevent users which are neither root nor the mount owner to access files. The listed opcodes are excluded from error because they can only be issued as a consequence of another opcode which is rejected (open() or the like). If they are received, this is a signal of a kernel malfunction with fuse_reply_err() must not aggravate.

**Comment by Nikratio** [comment]
I am assuming something along these lines as well, but what confuses me is why it explicitly checks for `allow_root`.  If the kernel is *not* already filtering out requests from other users, why don't we have to ensure that we don't give access to other users when `allow_root` is not set?

It seems to be that either there should be a second check along the following lines:

    if ( in->uid != se->owner && !se->allow_root &&
       [...]
         in->opcode != FUSE_READDIRPLUS)
        goto reply_err;

...or both of che checks are unneccessary.

**Comment by jpandre** [comment]
I suppose the kernel is permissive when allow_root is set and the mounter is not root, so the library has to prevent non-mounters from accessing files, whereas when allow_root is not set, the kernel does the job (note : needs to be checked).

**Comment by Nikratio** [comment]
Hmm. Looking at `mount.c`, it looks as if when `allow_root` is specified, `allow_other` is forwarded to the kernel. Maybe the kernel only knows about `allow_other`, and `allow_root` is implemented exclusively in libfuse?

**Comment by Nikratio** [comment]
If there was a way to avoid this check, the entire low-level interface would not need to be aware of allow_root anymore. Thus `parse_mount_opts()` would no longer need to pass-through this option, and we would no longer need to include it in `fuse_ll_opts` and `struct fuse_session`.

**Comment by Nikratio** [comment]
I've looked into this. The kernel indeed only knows about `allow_other`, and userspace is responsible for implementing `allow_root` on top of that. So the code behaves as it should.
