### ISSUE TITLE
Can fuse support directI/O or O_DIRECT

### ISSUE THREAD

**Issue by pahome** [libfuse/libfuse#87]
when I tried to use fio to test the filesystem and it always show error when I open directI/O 
and somebody said fuse didn't support directIO 
https://sourceforge.net/p/fuse/mailman/message/27377600/

is that true?

thx

**Comment by Nikratio** [comment]
Thanks for your interest in FUSE! Could you please send your question to FUSE mailing list
(https://lists.sourceforge.net/lists/listinfo/fuse-devel), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.
