### ISSUE TITLE
FUSE_CAP_HANDLE_KILLPRIV setting is missing  when init

### ISSUE THREAD

**Issue by bigbrotherwei** [libfuse/libfuse#884]
```
source file: lib/fuse_lowlevel.c
method: void do_init(fuse_req_t req, fuse_ino_t nodeid, const void *inarg)
line: about 2149 (master)
```

when init some flag that the `se->conn->want` want, libfuse forget the flag `FUSE_CAP_HANDLE_KILLPRIV`.

 I'm confused about whether libfuse missed it or shouldn't have set it. In my case, l need add this flag manually and recompile  libfuse.  otherwise, even if l set this flag in `se->conn->want`, it doesn't work.

![image](https://github.com/libfuse/libfuse/assets/67535186/63af21ba-713e-4662-a485-2a959063da4d)

**Comment by bsbernd** [comment]
Yeah, that is missing, but I also think it would be very troublesome to enable it by default as currently done - as documented
```
/**
 * Indicates that the filesystem is responsible for unsetting
 * setuid and setgid bits when a file is written, truncated, or
 * its owner is changed.
 *
 * This feature is enabled by default when supported by the kernel.
 */
```

Now I don't see anything in commit 05de3c98c07e636e007e7ecf6516508426d02c83 that would adding automatic kill-priv support to *libfuse* - it task of the file system to implement that feature - libfuse MUST NOT set it by default.

If you plan to submit a pull request, please remove this line
`LL_SET_DEFAULT(1, FUSE_CAP_HANDLE_KILLPRIV);

**Comment by bsbernd** [comment]
Actually, `LL_SET_DEFAULT(1, FUSE_CAP_HANDLE_KILLPRIV;` should already enable it. Hmm, do we have a security issue?

**Comment by bsbernd** [comment]
@Nikratio why did you enable KILLPRIV by default?

**Comment by Nikratio** [comment]
I have no memories of my thinking in 2016, but if you asked me today then I would argue that this is something that can be expected of the filesystem (just like we expect that link() truly creates a hardlink), that it was only added in the kernel as a (race-prone) workaround to not break backwards-compatibility, and that libfuse 3 was a good opportunity to start requiring filesystems to take responsibility for setuid/setgid handling.

**Comment by bsbernd** [comment]
Problem is that is introduces a security issues - by default it only save for overlay file systems that have their metadata on another vfs file system.... Persoanlly I doubt that all people who ported from libfuse2 to libfuse3 noticed that impact and I also doubt that even new file systems would know about that issue - it requires to fully understand the impact of that flag (and first to know about it...).

**Comment by bigbrotherwei** [comment]
@bsbernd Thank you for your reply, may I assume that libfuse does not implement the specific function of `FUSE_CAP_HANDLE_KILLPRIV` as documented ?

 l think `LL_SET_DEFAULT(1, FUSE_CAP_HANDLE_KILLPRIV` just set the flag to `se->conn.want`, what really works is the following variable `outargflags`. So we need to set the `FUSE_CAP_HANDLE_KILLPRIV` flag to `outargflags` if I understand correctly.

What l see is, add or not add the missing code does not behave the same. I summarize them as follows：

by default
1.set FUSE_CAP_HANDLE_KILLPRIV, libfuse will send set_attributes before write
2.unset FUSE_CAP_HANDLE_KILLPRIV, libfuse will send set_attributes before write

when l add the missing code
3.set FUSE_CAP_HANDLE_KILLPRIV, libfuse `will not` send set_attributes before write
4.unset FUSE_CAP_HANDLE_KILLPRIV, libfuse will send set_attributes before write

In fact, the case 3 is what l wanted since l can deal the suid、sgid by myself.

```
if (se->conn.want & FUSE_CAP_HANDLE_KILLPRIV)
		outargflags |= FUSE_HANDLE_KILLPRIV;
```

**Comment by bsbernd** [comment]
@bigbrotherwei Yeah right, I had mixed up what LL_SET_DEFAULT actually does. At least that simplies security impact - would you mind to submit a patch? And that also removes the LL_SET_DEFAULT for FUSE_CAP_HANDLE_KILLPRIV?

 Otherwise I will do tomorrow.

**Comment by bigbrotherwei** [comment]
@bsbernd Thank you, I am honored to submit a patch to fix this issue， l will do it later

**Comment by bigbrotherwei** [comment]
@bsbernd this is my patch:https://github.com/libfuse/libfuse/pull/885

**Comment by bsbernd** [comment]
Patch merged, issue fixed. Thanks for your contribution @bigbrotherwei !
