### ISSUE TITLE
Where is the FUSE kernal model repository

### ISSUE THREAD

**Issue by E6ren** [libfuse/libfuse#922]
I am wondering how the OS filesystem is working. FUSE maybe a good start. According to README 

> the fuse kernel module (maintained in the regular kernel repositories) and the libfuse userspace library (maintained in this repository)

I'm not sure if the kernel part of the code is public, if so, please provide a link to the repositories.

**Comment by trapexit** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/fs/fuse?h=v6.8.2
