### ISSUE TITLE
signify: signature verification failed for 3.16.2

### ISSUE THREAD

**Issue by brianjmurrell** [libfuse/libfuse#933]
Should `fuse-3.16.2.tar.gz` verify successfully in the same way as `fuse-3.16.1.tar.gz` does/did?

It doesn't seem to be do so:

```
$ signify -V -m fuse-3.16.2.tar.gz -p fuse-3.16.pub
signify: signature verification failed
$ signify -V -m fuse-3.16.1.tar.gz -p fuse-3.16.pub
Signature Verified
```

**Comment by bsbernd** [comment]
Hi Brian,

will check tomorrow.

**Comment by brianjmurrell** [comment]
Hello again @bsbernd.  Long time no chat.

In any case, NVM on this issue.  I seem to have a corrupted archive here that I was testing the signature against.  Not sure why I didn't double check the validity of the archive that I had before opening an issue here.  Apologies for the noise.
