### ISSUE TITLE
[libFuse 3.16.2]Compilation failure on freeBSD

### ISSUE THREAD

**Issue by abtiwari123** [libfuse/libfuse#936]
Despite the creation of the header file fuse_config.h during LibFUSE version 3.16.2's Meson build process, the BSD mount_bsd.c file continues to reference config.h. Consequently, this discrepancy results in compilation failures.

**Failure :**
[14/62] Compiling C object lib/libfuse3.so.3.16.2.p/mount_bsd.c.o
FAILED: lib/libfuse3.so.3.16.2.p/mount_bsd.c.o
cc -Ilib/libfuse3.so.3.16.2.p -Ilib -I../lib -Iinclude -I../include -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -D_REENTRANT -DHAVE_LIBFUSE_PRIVATE_CONFIG_H -Wno-sign-compare -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -fPIC -pthread -DFUSE_USE_VERSION=312 '-DFUSERMOUNT_DIR="/usr/local/bin"' -MD -MQ lib/libfuse3.so.3.16.2.p/mount_bsd.c.o -MF lib/libfuse3.so.3.16.2.p/mount_bsd.c.o.d -o lib/libfuse3.so.3.16.2.p/mount_bsd.c.o -c ../lib/mount_bsd.c
../lib/mount_bsd.c:11:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.
[15/62] Compiling C object lib/libfuse3.so.3.16.2.p/modules_iconv.c.o

**Comment by bsbernd** [comment]
Yeah, we don't have test for BSD - would you mind to submit a patch that works for you?

**Comment by abtiwari123** [comment]
Sure will do .

**Comment by abtiwari123** [comment]
Fix merged in master.
