### ISSUE TITLE
[FreeBSD] Compilation of libfuse fails on FreeBSD due to an unrecognized type/codes

### ISSUE THREAD

**Issue by abtiwari123** [libfuse/libfuse#941]
FAILED: example/notify_inval_inode.p/notify_inval_inode.c.o
cc -Iexample/notify_inval_inode.p -Iexample -I../example -Iinclude -I../include -Ilib -I../lib -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -D_REENTRANT -DHAVE_LIBFUSE_PRIVATE_CONFIG_H -Wno-sign-compare -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -pthread -MD -MQ example/notify_inval_inode.p/notify_inval_inode.c.o -MF example/notify_inval_inode.p/notify_inval_inode.c.o.d -o example/notify_inval_inode.p/notify_inval_inode.c.o -c ../example/notify_inval_inode.c
**../example/notify_inval_inode.c:289:44: error: use of undeclared identifier 'EBADFD'**
                 ret != -ENOENT && ret != -EBADFD && ret != -ENODEV) {

.**/example/notify_store_retrieve.c:355:43: error: use of undeclared identifier 'EBADFD'**
                ret != -ENOENT && ret != -EBADFD && ret != -ENODEV) {

[20/62] Compiling C object example/hello_ll_uds.p/hello_ll_uds.c.o
../example/hello_ll_uds.c:287:11: **warning: implicit declaration of function 'splice' is invalid in C99** [-Wimplicit-function-declaration]
                int i = splice(fdin, offin, fdout, offout, len - count, flags);

2/13] Compiling C object test/test_write_cache.p/test_write_cache.c.o
FAILED: test/test_write_cache.p/test_write_cache.c.o
cc -Itest/test_write_cache.p -Itest -I../test -Iinclude -I../include -Ilib -I../lib -I. -I.. -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -D_REENTRANT -DHAVE_LIBFUSE_PRIVATE_CONFIG_H -Wno-sign-compare -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -pthread -MD -MQ test/test_write_cache.p/test_write_cache.c.o -MF test/test_write_cache.p/test_write_cache.c.o.d -o test/test_write_cache.p/test_write_cache.c.o -c ../test/test_write_cache.c
.**./test/test_write_cache.c:217:5: error: unknown type name 'loff_t'; did you mean 'off_t'?**
    loff_t off = 0;
    ^~~~~~

**Comment by bsbernd** [comment]
Thank you, let's fix these, after 3.17.0 is out.
