### ISSUE TITLE
no way to set sane permissions

### ISSUE THREAD

**Issue by gandalfs-cat** [libfuse/libfuse#975]
since fuse uses the `umask` value to *set* the permission bits of st_mode, rather than as a mask, it is not possible to achieve typical permissions like 0644 for regular files and 0755 for directories (as you would normally get with umask 022); instead you get the same permission bits on all files and directories always.
 
my shell environment's $LS_COLORS hilights executable files and writable directories specially, which makes any fuse-mounted filesystem rather eye-watering to look at no matter how i set `umask`..

since there is precedent in other filesystems to have separate fmask and dmask options (for files and directories respectively), perhaps that is a viable solution that isn't intrusive (i.e. could be even potentially perhaps be backported?)

to that end, i've opened the following pull-requests:
https://github.com/libfuse/libfuse/pull/973
https://github.com/libfuse/libfuse/pull/974

here are various more real-world issues which may also solved by this addition:
- https://dev.arvados.org/issues/7831
- https://github.com/vmware/open-vm-tools/issues/490
- https://github.com/s3fs-fuse/s3fs-fuse/issues/680

**Comment by calestyo** [comment]
@bsbernd any estimate when a new release will be made which contains this nice treat? :-)

**Comment by bsbernd** [comment]
I need to find time to test and review myself this commit again: https://github.com/libfuse/libfuse/commit/2aba73e8bb9e0ed39ff4208ac5b99967b053f5d5

We have unfortunate ABI imcompat issue in latest versions, this commit should work it around, but I was too busy with other work... I hope I come to it till Sunday, otherwise probably only in 2 weeks.

**Comment by bsbernd** [comment]
@calestyo Aren't you involved (or haven't you) in debian packaging? If you have some ideas about so version bump and distribution handling of that, would you mind to chime in here? https://github.com/libfuse/libfuse/pull/1038

**Comment by calestyo** [comment]
@bsbernd, I’m afraid I’m not involved (or have been) in the Debian packaging of fuse.

It’s maintainer is Laszlo Boszormenyi, which I think should be @gcsideal (ping :-) ).

**Comment by bsbernd** [comment]
@calestyo Thank you! I already got a reply from László by mail - no issue for Debian. Just RHEL maintainers have some issues due to 3rd party software.
